### ISSUE TITLE
`FuturesUnordered` and missed wakeups

### ISSUE THREAD

**Issue by twittner** [rust-lang-nursery/futures-rs#1006]
When futures are added to `FuturesUnordered`, it is necessary to call `poll_next` in order to receive wakeups [[1][1]]. In particular, a `FuturesUnordered::push` will enqueue a `Node` with `queued` set to true to its ready list and if that `Node` is notified by the `Future`'s `Waker` before `FuturesUnordered::poll_next` has been called, the wakeup will be skipped [[2][2]]:

```rust
let prev = me.queued.swap(true, SeqCst);
if !prev {
    inner.enqueue(&**me);
    inner.parent.wake();
}
```

This behaviour makes it difficult to use `FuturesUnordered` as part of another `Future` whose `poll` method calls `FuturesUnordered::poll_next` as the missed wakeup may prevent `Future::poll` from being called. I wonder, why instead of the above, the wakeup is not unconditionally passed on to `FuturesUnordered::Inner::parent`:

```rust
let prev = me.queued.swap(true, SeqCst);
if !prev {
    inner.enqueue(&**me);
}
inner.parent.wake();
```

[1]: https://github.com/rust-lang-nursery/futures-rs/blob/6810513e6a2cede0a2746db12becec86757a1124/futures-util/src/stream/futures_unordered.rs#L26-L27
[2]: https://github.com/rust-lang-nursery/futures-rs/blob/6810513e6a2cede0a2746db12becec86757a1124/futures-util/src/stream/futures_unordered.rs#L601-L605

**Comment by tikue** [comment]
In https://github.com/libp2p/rust-libp2p/issues/190 it doesn't look like `FuturesUnordered::poll` is always called after `FuturesUnordered::push`, which means that the newly-pushed future won't ever trigger a wakeup. Documentation for `FuturesUnordered` says `poll()` needs to call for new futures to become managed, so this seems to be working as intended -- do I misunderstand?

**Comment by tomaka** [comment]
> this seems to be working as intended -- do I misunderstand?

It is indeed working as intended. The point of this issue is that what is intended should be modified.

**Comment by tikue** [comment]
Sorry, to clarify, my confusion is whether or not there was a solution to your problem other than fixing the data structure, because looking at the code it seems you can fix it by adding calls to `poll()` where none are made after `push()`?

**Comment by tomaka** [comment]
> it seems you can fix it by adding calls to poll() where none are made after push()?

We cannot do that because we may be outside of a tokio task, in which case polling would panic. 😕

**Comment by tikue** [comment]
Can you say more about why that's not feasible? At least, that's the pattern I've seen in poll impls and the pattern I use myself. I have a loop that continually polls sub-futures until they all return NotReady.

If you're worried about fairness and giving other futures the chance to run, you can return NotReady when there's more work that can be done, but you must schedule your own wakeup before returning. i.e. `task::current().notify()`. I don't think this is specific to `FuturesUnordered`. Any future impl needs to do this when returning `NotReady` while work remains.

**Comment by twittner** [comment]
In the end a loop is what has been used as well: https://github.com/libp2p/rust-libp2p/pull/198/files.
I admit that it feels a bit like a workaround to me and yes, I am specifically worried about fairness issues. I understand your suggestion to reschedule a wakeup but I keep wondering if the initially suggested change to `FuturesUnordered` would not make it easier to use.
