### ISSUE TITLE
try_future! macro

### ISSUE THREAD

**Issue by illicitonion** [rust-lang-nursery/futures-rs#1008]
On a project I work on, we've been using a `try_future!` macro, which acts just like the standard `try` macro, but returns a `future::err` instead or a `Result::Err`:

```
macro_rules! try_future {
( $x:expr ) => {
    {
        match $x {
            Ok(value) => value
            Err(error) => {return future::err(error);}
        }
    }
};
}
```

this is useful in `and_then` blocks which return `Future`s, as you cannot use a `?` in those contexts.

I've just wanted to use it in another project, too; would there be any interest in putting this into one of the `futures` crates somewhere? If so, where should it live?

**Comment by tikue** [comment]
You can use `?` in `and_then` blocks, because the fn passed to `and_then` has to return a type that impls `IntoFuture`, and `Result` impls `IntoFuture`.

**Comment by tikue** [comment]
I don't see how the macro could work -- wouldn't `do_some_io` have to return `FutureResult` for the return type to align with the type returned by `future::err`?

**Comment by illicitonion** [comment]
Aargh, yes - our version currently returns a `Box<Future>`, and I was thinking that `impl Trait` would make this work better in a library, but you're right, it's still pretty limited without the `Box` :(
