### ISSUE TITLE
Make `FuturesUnordered`'s polled-while-empty behavior configurable.

### ISSUE THREAD

**Issue by khuey** [rust-lang-nursery/futures-rs#1009]
I have a `FuturesUnordered` which is basically a pool of ongoing work. I also have a channel that represents incoming work. I would like to write:

```rust
  let mut new_work; // Stream<Item=NewWork>
  let mut ongoing_work; // FuturesUnordered<Future<Item=WorkUnit>>

  loop {
    match executor::block_on(new_work.into_future().select2(ongoing_work.into_future())).expect("No errors") {
      Either::A(((new_work_piece, returned_new_work), ongoing_work_fut)) => {
        new_work = returned_new_work;
        ongoing_work = ongoing_work_fut.into_inner().unwrap();

        ongoing_work.push(make_ongoing(new_work));
      },
      Either::B(((ongoing_work_piece, returned_ongoing_work), new_work_fut)) => {
        new_work = new_work_fut.into_inner().unwrap();
        ongoing_work = returned_ongoing_work;

        // Do something with `ongoing_work_piece`
      },
    }
  }
```

I can't do this as is because `FuturesUnordered`, when empty, returns `Async::Ready(None)` instead of `Async::NotReady`, so this code effectively busy waits. I solved this with a silly little wrapper but it might be worth doing something more generally applicable.

**Comment by cramertj** [comment]
This is possible today using `select!`, which is aware of `FuturesUnordered`'s `FusedStream` status.
