### ISSUE TITLE
`mpsc::sync::UnboundedSender` should expose `poll_ready`

### ISSUE THREAD

**Issue by olix0r** [rust-lang-nursery/futures-rs#1012]
As discussed in [conduit#956](https://github.com/runconduit/conduit/pull/956#issuecomment-389652468), I think that `mpsc::sync::UnboundedSender` should be extended to expose a `poll_ready()` implementation (that delegates to the inner `Sender`) so that senders can test whether the `UnboundedReceiver` is still alive without necessarily having an item to be sent.

This is probably a pretty trivial change (that I would need for futures-0.1). I'd be happy to prepare this PR, but I would like to know if there are any objections before proceeding.

**Comment by olix0r** [comment]
Additionally (maybe this is worth a separate issue), what we _really_ want is both sender types to implement `poll_close` so that it's possible to ask to be notified when the receiver has been dropped.  This is necessary because, in the case of UnboundedSender, `poll_ready` _always_ returns `Ready` when the receiver exists.  We need something to return `NotReady` so that we can anticipate the task to be notified when the receiver is dropped.

**Comment by cramertj** [comment]
Both of these seem like totally reasonable requests-- I'd be happy to accept a PR for them!

**Comment by cramertj** [comment]
@olix0r is this still wanted? I haven't heard anything about this in a while, just pinging to see if there is still interest.

**Comment by olix0r** [comment]
@cramertj I think this behavior is still desirable, yes; however, in the places we rely on it we've worked around it with a reverse-oneshot dance.

**Comment by cramertj** [comment]
Closing-- this is exposed in 0.3.
