### ISSUE TITLE
No LICENSE files are included in sub-crates

### ISSUE THREAD

**Issue by ignatenkobrain** [rust-lang-nursery/futures-rs#1015]
Please include them and release new version.

**Comment by cramertj** [comment]
It is common for subcrates in a repo not to include their own license files. I'd recommend using the "repository" key in the Cargo.toml of the crate to look for matching licenses in the crate's repo.

**Comment by Nemo157** [comment]
I believe Apache at least technically requires distributing the license file when distributing the source (such as the crate archive). It’s pretty trivial to add symlinks from the sub crates back into the main folder to do so.
