### ISSUE TITLE
Build failures in Nightly due to Proc macro API 1.2

### ISSUE THREAD

**Issue by tirkarthi** [rust-lang-nursery/futures-rs#1018]
Project fails with Nightly compiler due to the recent proc macro API changes made that renames some of the components. It seems the release of proc macros 2 library with the changes already merged will fix the issue. I searched for issues here and couldn't find anything related to this. Hence I am opening this as a reminder. Feel free to close this if it's tracked elsewhere. 

Upstream rustc issue reference : https://github.com/rust-lang/rust/pull/50473#issue-186182501
Upstream proc macros 2 PR (merged) : https://github.com/alexcrichton/proc-macro2/pull/90

Thanks

**Comment by hcpl** [comment]
I made an update in https://github.com/rust-lang-nursery/futures-rs/pull/1021. Please check out my branch and see whether that fixes the problem!

**Comment by cramertj** [comment]
Fixed by https://github.com/rust-lang-nursery/futures-rs/pull/1021
