### ISSUE TITLE
Release for 0.1?

### ISSUE THREAD

**Issue by rubdos** [rust-lang-nursery/futures-rs#1038]
Since #998 five weeks ago, no other commits have entered the 0.1 branch... but could I still request a release?

Also, I wonder what the source for 0.1.21 is; 0.1.20 is tagged, but 0.1.21 is not. Just a side note, nothing too important I suppose.

**Comment by MajorBreakfast** [comment]
@cramertj just released 0.1.22

**Comment by dekellum** [comment]
See also #993.
