### ISSUE TITLE
0.3: How can I return a Future from a trait function?

### ISSUE THREAD

**Issue by ngg** [rust-lang-nursery/futures-rs#1058]
With 0.1.x and 0.2.x it was possible to return `Box<Future<Item = ..., Error = ...>>`, but with the 0.3 branch it's no longer possible.
```rust
trait T {
    fn f() -> Box<Future<Output = ()>>;
}
```
This code gives the following compile error:
```
error[E0038]: the trait `std::future::Future` cannot be made into an object
 --> src/main.rs:4:5
  |
4 |     fn f() -> Box<Future<Output = ()>>;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::future::Future` cannot be made into an object
  |
  = note: method `poll` has a non-standard `self` type
```

Returning with `impl Trait` is not allowed in trait functions, so that method does not work on any branch.

**Comment by MajorBreakfast** [comment]
The plan is that this limitation will one day be lifted. In the meantime we have `TaskObj` and `LocalTaskObj` to store a `Future<Output = ()> + Send` and `Future<Output = ()>` respectively.

See https://github.com/rust-lang-nursery/futures-rs/blob/0.3/futures-core/src/task/mod.rs#L42

**Comment by ngg** [comment]
I think the `impl Trait` limitation will not be lifted too soon. (probably not in the Rust 2018 release)

I would need something like this but with a generic output type to be able to migrate our current project that now uses the `0.2` series, but this is a blocking issue for that.

What do you think about converting `TaskObj` and `LocalTaskObj` to have generic outputs? So `TaskObj<T>` would store `Future<Output = T> + Send + 'static` and `LocalTaskObj<T>` would store `Future<Output = T> + 'static`? It's not too late to change this in `core`.

**Comment by MajorBreakfast** [comment]
`dyn Trait` (trait object), not `impl Trait` BTW. And I also think that it won't be lifted for Rust 2018. However, that's not a big deal and certainly no roadblock for stabilization. `Executor::spawn_obj` has specifically a name that ends with `_obj`, so that we can use the nice name at some point in the future.

**Comment by ngg** [comment]
Yeah I don't see a problem with a generic T either, but the generic lifetime seems much trickier (because of the `*mut ()` magic in `UnsafeTask`. If `*mut ()` is replaced with something that captures the lifetime as well (ex. a struct with the pointer and a `PhantomData<&'a ()>`) then it might work.

It can obviously be replicated into `futures-util` with a generic output if we don't want to change `core`. (It might even be simplified if it would support only `PinBox` and not a generic `UnsafeTask`)

**Comment by MajorBreakfast** [comment]
I tabled the lifetime thing for now. We should look into it however at some point.

Here's my PR https://github.com/rust-lang/rust/pull/51944

**Comment by ngg** [comment]
I checked our project and currently we do use custom lifetimes.

A simple use case that's currently working for us with the 0.2.x branch:
```rust
trait T {
    fn f<'a>(&'a self) -> PinBox<Future<Item = u32, Error = MyError> + 'a>;
}
struct S;
impl T for S {
    #[async(boxed)]
    fn f(&self) -> MyResult<u32> {
        await!(/*...*/);
        Ok(())
    }
}
```

So it would be great to be able to write this with 0.3:
```rust
trait T {
    fn f<'a>(&'a self) -> LocalFutureObj<'a, MyResult<u32>>;
}
struct S;
impl T for S {
    fn f<'a>(&'a self) -> LocalFutureObj<'a, MyResult<u32>> {
        LocalFutureObj::new(PinBox::new(async {
            await!(/*...*/);
            Ok(())
        }))
    }
}
```

**Comment by MajorBreakfast** [comment]
Now that this is merged we just need to wait for the next nightly. Currently there seem to be some troubles with the build infrastructure.

https://rust-lang-nursery.github.io/rust-toolstate/

In the meantime, a version of `FutureObj` and `LocalFutureObj` is already available under `futures::future::FutureObj` and `futures_core::future::FutureObj`. It's not a reexport from libcore yet, though. `Executor::spawn_obj` still expects the `TaskObj`. This will change as soon as we have a new nightly.
