### ISSUE TITLE
Give `Stream` separate `Yield` and `Return` types.

### ISSUE THREAD

**Issue by canndrew** [rust-lang-nursery/futures-rs#1059]
The current `Stream` API has several related problems.

Firstly, there's no way to know whether errors on a stream are fatal or not. For some streams, an error may indicate that the stream is now in an invalid state and shouldn't be polled again. Other streams may want to return any number of errors interleaved with normal items. Yet other streams may want to have both fatal and non-fatal errors, and have these distinguished at the type level.

Another is that there's no way to specify that a stream is never-ending. Too much of my futures code has `Ok(Async::Ready(None)) => unreachable!()` in it, and it makes me uncomfortable.

Another is that it can often be useful to return a different kind of item at the end of a stream, indicating that the stream is finished. For example, a long-running operation may want to return intermediate status updates before eventually returning the result of the operation.

The solution to all these problems is to give `Stream` two associated types: one for intermediate values and one for the final value.

```rust
enum PollStream<Y, R> {
    Yield(Y),
    Return(R),
    NotReady,
}

trait Stream {
    type Yield;
    type Return;

    fn poll_next(self: PinMut<Self>, cx: &mut task::Context) -> PollStream<Self::Yield, Self::Return>;
}
```

This allows you to use `Result` in both positions to indicate fatal vs non-fatal errors, you can use `Return = !` to have infinite streams, `Return = ()` to get the current behaviour, or `Return = T` to make a stream end with whatever you want.

**Comment by Nemo157** [comment]
Do you have any thoughts on how to handle looping over a stream that returns a non-unit return value? Currently you can use

```rust
while let Some(foo) = stream.next() {
}
```

I could see having the same `next` combinator for `Stream<Return = ()>`, and something similar for infinite streams, but I’m struggling to think how to nicely handle a stream that could return a fatal error.

**Comment by MajorBreakfast** [comment]
@canndrew 
- I think we should consider `Yield` and `Return` types for async generators. I imagine that one day we'll likely get both a `Stream` and an `AsyncGenerator` (Name TBD) trait. (Or just one of them, who knows? ^^')
- An extra `PollStream` enum is unlikely. The `Poll` enum was put into `core::task`, so that we can reuse it in the stream API. For async generators it will then likely contain something similar to [`GeneratorState`](https://doc.rust-lang.org/std/ops/enum.GeneratorState.html)
- Currently, we're mostly concerned with the `Future` trait because we won't be able to change it after we put it into libcore. OTOH there's no rush to settle on a final design for the stream API ATM.

**Comment by vorot93** [comment]
Concerns voiced by @canndrew resonate very much with me.

It does occur to me that current Stream was modeled after Iterators that were never geared toward fallible use cases. Therefore they are no good fit for asynchronous use cases.

On the other hand, generator-based design seems to map much closer to what occurs in production.

**Comment by Ralith** [comment]
A similar discussion regarding generators: https://internals.rust-lang.org/t/pre-rfc-generator-integration-with-for-loops/6625

**Comment by cramertj** [comment]
Closing-- I don't think we're going to change this API, and it has been discussed thoroughly in a number of places.
