### ISSUE TITLE
Clarify the relationship between a Task and a Stream

### ISSUE THREAD

**Issue by bharrisau** [rust-lang-nursery/futures-rs#1070]
I've just started having a poke around after coming from an Akka Streams world. I'm just trying to clarify whether the `Stream::poll_next(cx)` can be called by different tasks/contexts/executors. The docs only reference the task in passing.

> Attempt to pull out the next value of this stream, registering the current task for wakeup if the value is not yet available, and returning `None` if the stream is exhausted.

And many of the stream combinators only have 1 slot for `cx.waker` instead of a queue.

Sorry if the relationship is obvious to others, I've only just started having a look wasn't sure if fan-in/out topologies are OK with just locking/thread-safety, or if the upstream Streams need to be polled by a stable task.

**Comment by MajorBreakfast** [comment]
> I'm just trying to clarify whether the Stream::poll_next(cx) can be called by different tasks/contexts/executors

- Yes, streams and futures have to call `wake()` on the waker that the received last. Calling them with a new context that contains a different waker is fine.
- However, the exchange is not synchronized. This means that until poll returns you cannot be sure that the stream/future exclusively calls the new waker. It can happen that it also calls the old waker. It's unlikely, but not guaranteed.

@cramertj Does that sound right?

**Comment by cramertj** [comment]
Sounds about right. Just to clarify this bit:
> However, the exchange is not synchronized. This means that until poll returns you cannot be sure that the stream/future exclusively calls the new waker. It can happen that it also calls the old waker. It's unlikely, but not guaranteed.

If `Stream::poll_next` is called and returns `Pending`, it is guaranteed that it already has or will call `wake()` on the waker in the context passed to the latest invocation of `Stream::poll_next`. Spurious wakeups are always allowed, so it may at any point call `wake()` on an old waker that was previously passed to `poll_next`, but it is *guaranteed* that the latest waker passed to `poll_next` will receive a wakeup when the stream is ready to make progress.

**Comment by bharrisau** [comment]
Thanks, that clarifies things a bit. I guess in the situation where the stream is partitioning itself into multiple substreams, it needs to guarantee that is calls the latest waker for a substream when that substream is ready.
