### ISSUE TITLE
0.2 fails to compile with latest nightly

### ISSUE THREAD

**Issue by sdroege** [rust-lang-nursery/futures-rs#1096]
See e.g. `cargo +nightly test --features nightly` with latest git master (and the 0.2.2/0.2.3 versions on crates.io). This is `rustc 1.29.0-nightly (4f3c7a472 2018-07-17)`

```
error[E0432]: unresolved import `futures::prelude::await`
 --> futures/tests/async_await/pinned.rs:4:5
  |
4 | use futures::prelude::await;
  |     ^^^^^^^^^^^^^^^^^^^^^^^ no `await` in `prelude`

[...]

error[E0658]: attribute procedural macros are experimental (see issue #38356)
 --> futures/tests/async_await/elisions.rs:6:1
  |
2 | use futures::prelude::*;
  |     ------------------- procedural macro imported here
...
6 | #[async]
  | ^^^^^^^^
  |
  = help: add #![feature(proc_macro)] to the crate attributes to enable

[...]

error[E0659]: `await` is ambiguous
  --> futures/tests/async_await/smoke.rs:71:5
   |
71 |     await!(foo())
   |     ^^^^^
   |
note: `await` could refer to the name imported here
  --> futures/tests/async_await/smoke.rs:14:5
   |
14 | use futures::prelude::*;
   |     ^^^^^^^^^^^^^^^^^^^
   = note: `await` is also a builtin macro
   = note: consider adding an explicit import of `await` to disambiguate
```

**Comment by Nemo157** [comment]
```
error[E0432]: unresolved import `futures::prelude::await`
 --> futures/tests/async_await/pinned.rs:4:5
  |
4 | use futures::prelude::await;
  |     ^^^^^^^^^^^^^^^^^^^^^^^ no `await` in `prelude`
```

This requires `#![feature(use_extern_macros)]`, that seems to have been split off `proc_macro` since `use_extern_macros` is stable in Edition 2018 while `proc_macro` is still unstable. 

```
error[E0658]: attribute procedural macros are experimental (see issue #38356)
 --> futures/tests/async_await/elisions.rs:6:1
  |
2 | use futures::prelude::*;
  |     ------------------- procedural macro imported here
...
6 | #[async]
  | ^^^^^^^^
  |
  = help: add #![feature(proc_macro)] to the crate attributes to enable
```

Probably just needs `feature(proc_macro)` in the test file, I guess the fact that it's a procedural macro is no longer hidden behind the re-export.

```
error[E0659]: `await` is ambiguous
  --> futures/tests/async_await/smoke.rs:71:5
   |
71 |     await!(foo())
   |     ^^^^^
   |
note: `await` could refer to the name imported here
  --> futures/tests/async_await/smoke.rs:14:5
   |
14 | use futures::prelude::*;
   |     ^^^^^^^^^^^^^^^^^^^
   = note: `await` is also a builtin macro
   = note: consider adding an explicit import of `await` to disambiguate
```

This needs an explicit `use futures::prelude::await;` to disambiguate, which will also need a `#![features(use_extern_macros)]`.

(You can see some relevant discussion related to the 0.1 version in https://github.com/alexcrichton/futures-await/issues/106)

**Comment by sdroege** [comment]
Adding `use_extern_macros` to `futures/tests/async_await_tests.rs` fixes this specific problem, but leaves the doctests failing. Not sure what the magic is to get the `await` macro from the futures crate in there instead of the one from std.

**Comment by MajorBreakfast** [comment]
@sdroege It is possible to add feature flags to doc tests:

https://github.com/rust-lang-nursery/futures-rs/blob/3beee842cb0f1d61cac8a6094c7bfc7b93489d77/futures-util/src/future/mod.rs#L107

**Comment by sdroege** [comment]
Thanks, https://github.com/rust-lang-nursery/futures-rs/pull/1098 fixes that
