### ISSUE TITLE
0.3 preview renaming

### ISSUE THREAD

**Issue by MajorBreakfast** [rust-lang-nursery/futures-rs#1099]
- `Cargo.toml` (7 files)
  - `package.name`
  - `package.documentation`
  - `dependencies`
- `lib.rs` (7 files)
  - `#![doc(html_root_url = "...")]`
- Code examples:
  - All use statements should refer to the preview crates

Question: Why do the `extern crate` statements in the current master branch (0.2) never use `as`, e.g. `extern crate futures-preview as futures;`? It seems to work, but I don't quite understand how it finds the crates if their actual name is different.

**Comment by Nemo157** [comment]
As @withoutboats recently mentioned on the 2018 stabilisation thread having https://github.com/rust-lang/cargo/issues/5653 would be amazing for this. You could use and recommend `futures = { package = "futures-preview", version = "0.3.0-alpha.1" }` as the way to depend on the preview. Unfortunately there’s been no confirmation one way or the other whether this cargo feature could be stabilised for the first 2018 release.

**Comment by MajorBreakfast** [comment]
Implemented by https://github.com/rust-lang-nursery/futures-rs/pull/1103/files

Renaming of the use statements was not required
