### ISSUE TITLE
Thread pool NUMA/cache optimization

### ISSUE THREAD

**Issue by MajorBreakfast** [rust-lang-nursery/futures-rs#1117]
The thread pool could be made even more performant if each future tended to stick to a specific thread. That approach would be better for caching, because it makes it more likely that data can be reused from the cache. And it makes it better suited for processors with NUMA, like Threadripper or server processors. NUMA stands for non-uniform memory access and it means that the memory access time depends on the memory location relative to the processor, i.e. the connection from a memory stick is faster to one set of cores than it is to others. This optimization should lead to better performance. Only way to find out is to try it :)

(ATM this is not a priority. It's meant as a challenge for anyone that seeks one 🙂)

**Comment by carllerche** [comment]
I'm sure you are already aware, but I will post for any who comes across this issue and is curious.

There already is a future executor / thread pool that has good structure for NUMA and cache optimization: [tokio-threadpool](https://github.com/tokio-rs/tokio)
