### ISSUE TITLE
LocalExecutor trait and minimal executors cleanup

### ISSUE THREAD

**Issue by MajorBreakfast** [rust-lang-nursery/futures-rs#1139]
I would like to do the following restructuring:
- Define a `LocalExecutor` trait in `futures_core::task`. It has a `spawn_local_obj` method which takes a `LocalFutureObj` as input.
- Add `impl<T: LocalExecutor> Executor for T`
- I want to remove `SpawnLocalObjError` from libcore and define it in`futures_core` instead. We don't need it in libcore, defining it in `futures_core` is enough.

Next, I'd like to modify our executors like this:
- `LocalPool`:
  - should implement `LocalExecutor` and thus `Executor`. It currently doesn't implement `Executor` and that's awkward
  - I want to discuss the usefulness of the `executor` method which returns a `!Send`, `!Sync` "clonable handle to the pool as an executor". Why do we have that?
  - We can add:
    - `impl<T: LocalExectutor> LocalExectutor for Rc<T>`
    - `impl<T: LocalExectutor> LocalExectutor for Weak<T>` which returns an error with `SpawnErrorKind::shutdown()` if it can't upgrade
    - and the same for `Arc`/`Weak` and `Executor` (=> 4 combinations in total or 3 if we leave out `Arc` + `LocalExecutor`). I hope that there are no orphan rule conflicts
    - alternatively if orphan rules prevent that or that's deemed too radical we can also just add these impls for for `Rc<LocalPool>`/`Weak<LocalPool>` or not at all. Let's discuss this (the benefit is the shutdown error for `Weak`)

**Comment by Nemo157** [comment]
Is `LocalExecutor` stable enough for `futures-core`, or should it spend some time baking in `futures-executor` first?

**Comment by MajorBreakfast** [comment]
I think it's stable enough to be put into `futures-core`:
- The trait mirrors the `Executor` trait with the only difference that it's for non-`Send` futures.
- `SpawnLocalObjError` has even made it into libcore. I just want to move it out again because the `LocalExecutor` stuff really isn't needed in libcore for any technical reasons.
