### ISSUE TITLE
Move spawn, spawn_with_handle into futures-util as macros

### ISSUE THREAD

**Issue by MajorBreakfast** [rust-lang-nursery/futures-rs#1140]
These are currently in `futures-executor/src/spawn.rs` but they don't depend on anything from the `futures-executor` crate => they should live in `futures-util` because they're general purpose and similar to the kind of stuff in `futures-util`

**Comment by cramertj** [comment]
Yeah, that sounds good! I'd also +1 `spawn!` and `spawn_with_handle!` macros for wrapping them in `await!`s.

**Comment by MajorBreakfast** [comment]
I also favor the macro versions and would like to replace these with macro versions. However, @Nemo157 mentioned this use case once:
```rust
let handle = await!(spawn_with_handle(future).with_executor(...));
```

How could this work with macros?

**Comment by MajorBreakfast** [comment]
@aajtodd You're right. It should say "the context's executor"

**Comment by MajorBreakfast** [comment]
@cramertj How about providing only macros, but with an optional `executor` parameter?

```rust
spawn!(future);
spawn!(future, executor);
```

**Comment by cramertj** [comment]
@MajorBreakfast if you have an executor and a future, you don't need a macro-- you can write `executor.spawn_obj(Box::new(future).into())` (eventually `executor.spawn(future)`). I guess we'd be saving a few characters by avoiding the whole `Box::new(...).into()` dance, but we could do the same by providing an extension trait that delegated to `spawn_obj` internally (similar to [the existing one for `Context`](https://github.com/rust-lang-nursery/futures-rs/blob/master/futures-util/src/task/context.rs#L18)).

**Comment by MajorBreakfast** [comment]
@cramertj You're right, the macro isn't needed for this use case. I've created an [issue for `ExecutorExt`](https://github.com/rust-lang-nursery/futures-rs/issues/1142) with an approach that I think would work. Once we have `ExecutorExt`, we can build easy to use `spawn!` and `spawn_with_handle!` macros around it.

**Comment by Nemo157** [comment]
> The documentation on spawn says that the function will spawn the given future as a task onto the default executor, maybe I'm missing something but I don't see where this happens.

> You're right. It should say "the context's executor"

I had the same initial reaction, eventually I figured out that "the default executor" _is_ "the current context's executor", there's nothing else for it to refer to. :+1: for clarifying this a bit more.

**Comment by MajorBreakfast** [comment]
Closed by https://github.com/rust-lang-nursery/futures-rs/pull/1156
