### ISSUE TITLE
impl Future instead of AndThen?

### ISSUE THREAD

**Issue by kornelski** [rust-lang-nursery/futures-rs#1150]
The `AndThen` combinator type creates ugly long types, which make errors painfully verbose.

Would it be possible to change the `.and_then()` method to return `impl Future` instead?

**Comment by MajorBreakfast** [comment]
All of our combinator methods return nameable types so that it is possible:
- to store them them inside struct fields. You need to name the type when you define a struct field
- that some of them can have additional methods on them, e.g. `FuturesUnordered::push`

**Comment by kornelski** [comment]
I see. That makes sense, although shame about the huge type names :/

**Comment by MajorBreakfast** [comment]
I recommend using async functions. Async functions are the perfect remedy against deeply nested futures.
