### ISSUE TITLE
Build `task_local!` data from a `Future`

### ISSUE THREAD

**Issue by Ekleog** [rust-lang-nursery/futures-rs#1187]
# Conversation moved to https://github.com/rust-lang-nursery/wg-net/issues/7

I am currently designing a crate. In this crate, I have a `lazy_static!` `HashMap`, that I'm filling with one piece of data per task, in the `task_local!` constructor.

As a consequence, I have to handle locking to this `HashMap`. Which would seem to be handled cleanly only by constructing the actual piece of data from a `Future`, so that the executor loop doesn't have to stop waiting for the `RwLock` when spawning a task.

What do you think about this idea? (also, is there maybe some other way I don't know of to associate each task with a serializable ID and additional metadata, and my problem is void?)

**Comment by tikue** [comment]
Should conversation converge on https://github.com/rust-lang-nursery/wg-net/issues/7?

**Comment by Ekleog** [comment]
Good point, leaving this open until https://github.com/rust-lang-nursery/wg-net/issues/7 is solved so that people who search for it find it, plan to close once that's solved :)

**Comment by cramertj** [comment]
rustasync/team#7 has been closed
