### ISSUE TITLE
Suggested rename for spawn macros (bikeshedding)

### ISSUE THREAD

**Issue by jonhere** [rust-lang-nursery/futures-rs#1204]
My suggestion, using familiar shell syntax;
`spawn_with_handle!` -> `bg!`
`spawn!` -> `bg_disown!`

p.s. If I understand correctly the current `spawn!` can outlive an async function, so while more performant has the added risk. (Same goes with the other too if dropped i.e. not dealt with later in a `await!`/`join!`)

**Comment by Nemo157** [comment]
Probably an appropriate place to include @eddyb's suggestion [from reddit](https://www.reddit.com/r/rust/comments/97dtn3/futures_030alpha3/e4a894j):

> Maybe the detached `spawn!` shouldn't be the default, since I don't see it being that useful? If `spawn_with_handle!` was renamed to `spawn!` it would match `thread::spawn` better, and we can use the name `spawn_detached!` for the other (less common, hopefully) case.

Note that the current `spawn_with_handle!` returns a `JoinHandle` which is `#[must_use]`, that should hopefully avoid most cases of accidentally dropping it without awaiting it.

**Comment by MajorBreakfast** [comment]
- The increased length of the name `spawn_with_handle!` makes it intuitively clear that that macro is more costly than the other one.
- `Spawn::spawn` exists and it's nice that the macros and methods have consistent naming. I'm not entirely against renaming these methods, but consistent naming between the macros and the methods is IMO a must.

**Comment by eddyb** [comment]
Maybe the trait itself should have two methods?
Either way, even though there's a cost... how useful is spawning a detached future?

**Comment by cramertj** [comment]
These macros don't exist anymore :)
