### ISSUE TITLE
code size

### ISSUE THREAD

**Issue by aep** [rust-lang-nursery/futures-rs#1222]
why is futures so large? It's even bigger than std.

this is with lto, in release mode. 

```
$ cargo bloat --release --crates -w -n 0 --full-fn
    Finished release [optimized] target(s) in 0.13s
   Analyzing target/release/carrier

 File  .text     Size Name
 9.6%  20.9% 606.3KiB futures
 9.2%  20.1% 584.0KiB std
...
```

```
 0.3%   0.8% 22.0KiB                futures <futures::stream::fold::Fold<S, F, Fut, T> as futures::future::Future>::poll::h3c2b7ae24026580c

 0.3%   0.6% 17.8KiB                futures <futures::future::or_else::OrElse<A, B, F> as futures::future::Future>::poll::hf6b5022846370fb2

 0.3%   0.6% 16.8KiB                futures <futures::future::into_stream::IntoStream<F> as futures::stream::Stream>::poll::h01f8c585ae211b25

```

**Comment by cramertj** [comment]
All of the functions in futures are monomorphized for your particular usage of them, so any code that you wrote using futures combinators will show up as monomorphized futures code. Your `cargo bloat` invocation above is likely showing the size of all the futures code that is generated as a result of compiling your application, as well as any of your non-futures code that is inlined into the futures functions.

**Comment by aep** [comment]
So do I understand correctly that's this cannot be fixed because it's an inherit property of the typing system?
