### ISSUE TITLE
Future#select doc wrong.

### ISSUE THREAD

**Issue by xialvjun** [rust-lang-nursery/futures-rs#1237]
https://docs.rs/futures/0.1/futures/future/trait.Future.html#method.select

> The returned future will finish with both the value resolved and a future representing the completion of the other work.

It seems the doc of `Future#select` is wrong, change `both` to `either`.

**Comment by Nemo157** [comment]
From the [`futures::future::Select` docs](https://docs.rs/futures/0.1/futures/future/struct.Select.html)

```rust
impl<A, B> Future for Select<A, B>
where
    A: Future,
    B: Future<Item = A::Item, Error = A::Error>
type Item = (A::Item, SelectNext<A, B>)
```

the result of the future is a tuple containing the value resolved and another future, why do you think this should be `either`?

**Comment by xialvjun** [comment]
1. https://docs.rs/futures/0.1/futures/future/struct.Select.html
> Future for the select combinator, waiting for one of two futures to complete.

2. https://docs.rs/futures/0.1/futures/future/trait.Future.html#method.select
> This function will return a new future which awaits for either this or the other future to complete.

**Comment by Arnavion** [comment]
@xialvjun There is no mistake. The sentence with "either" is saying that the future completes when either of the two original futures complete. The sentence with "both" is saying that the *result* of the future has two values; one value is the result of one of the original futures and the other value is the other future itself.
