### ISSUE TITLE
Yank 0.3.0-alpha.4

### ISSUE THREAD

**Issue by blueridanus** [rust-lang-nursery/futures-rs#1255]
From the [changelog](https://github.com/rust-lang-nursery/futures-rs/blob/master/CHANGELOG.md):

```markdown
# 0.3.0-alpha.4 - 2018-09-02
**Note: This release does not work, use `0.3.0-alpha.5` instead**
```

It should be appropriate, then, to yank `0.3.0-alpha.4` from [crates.io](https://crates.io/crates/futures-preview/versions), with an accompanying note on the [blog post](https://rust-lang-nursery.github.io/futures-rs/blog/2018/09/02/futures-0.3.0-alpha.4.html).

**Comment by sagebind** [comment]
Yes please! The existence of this version is causing docs.rs to choke on parsing the crate's manifest, which means no docs for me. :cry: https://docs.rs/crate/chttp/0.2.0/builds/116754

**Comment by Thomasdezeeuw** [comment]
Well alpha 5 doesn't work on latest nightly anymore either. I think it might be too much overhead to publish v *n* and then yank *n-1* for every breaking change in the (expiremental parts of the) standard library.

Also people might need to use an older nightly for there own code, so leaving them up seems fine to me.

**Comment by sagebind** [comment]
I believe `This release does not work` does not mean that the code itself is broken, but rather the crate metadata is broken (failed attempt at using crate aliases IIRC) and cannot be used at all. I agree it would be unnecessary to yank every alpha that doesn't work on nightly any more.

**Comment by cramertj** [comment]
Done.
