### ISSUE TITLE
Docs should include tutorials

### ISSUE THREAD

**Issue by ghost** [rust-lang-nursery/futures-rs#1258]
Hello,

While working on an [old version](https://docs.rs/futures/0.1.24/futures/stream/trait.Stream.html), its docs lead to a non-existent webpage: https://tokio.rs/docs/getting-started/streams-and-sinks/

May I ask if you could consider adding tutorials directly to the docs? The `std` crate is doing good at this. It would be great if you do the same. Website changes, but as my experiences with crate docs, it's better to put tutorials directly inside docs.

Thanks,

P.S: It's a "may I ask" question, to suggest some changes. I don't intend to ask developers to do anything. I'm saying this because in the past, in other projects, original developers tended to think that I was asking them to do something for me. I'm sorry beforehand for any misunderstanding.

**Comment by cramertj** [comment]
There're a number of examples in the docs, as well as links to the async book. I don't think we're planning on changing anything here, but I'm always interested in PRs for documentation improvements if you're interested in making some!
