### ISSUE TITLE
Update to latest pinning API

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang-nursery/futures-rs#1265]
PR https://github.com/rust-lang/rust/pull/53877 change the pinning API, breaking futures as well. Is someone working on fixing this? Or should I make an attempt?

**Comment by cramertj** [comment]
I was planning to wait on this until https://github.com/rust-lang/rust/pull/54339 landed, which includes more breaking changes.

**Comment by JesseWright** [comment]
@cramertj I believe this can be closed now that #1268 and #1273 have been merged and #1266 closed.
