### ISSUE TITLE
Express ordering requirement in stream on type level

### ISSUE THREAD

**Issue by dominikwerder** [rust-lang-nursery/futures-rs#1293]
The order of items in a `Stream` can be very important for correctness.

There should be a way to express this requirement on type level so that we can check at compile time whether it is allowed to wrap a stream in a stream adaptor like `BufferUnordered` or other custom stream adaptors which may want to ignore the order in favor of performance.

**Comment by dominikwerder** [comment]
> This can be done in the `Stream` impl without any type changes, simply only produce one future at a time and block waiting on that future completing before producing the next one. You would then still be able to wrap the stream in `BufferUnordered`, but the stream itself would enforce the buffer only operates on a single item at a time.

But that would render `stream::Buffered` applied to such a kind of stream useless as well?

Please let me try to express more clearly what I'm looking for:

Assume that I provide some

```rust
fn create_stream() -> impl Stream<Item=Stuff, Error=Fail>
```

how can I express on type level that the users of that returned `Stream` are not allowed to change the order of items in that stream? As far as I can see, I can not do that with the current API.

Now, just as a naive example, if there would exist some `trait ReorderableStream: Stream`, then if `buffer_unordered` would be implemented only for `ReorderableStream` then I could express that.

**Comment by Nemo157** [comment]
@dominikwerder that wouldn't be affected by `buffer_unordered` as it's basically

```rust
fn buffer_unordered<T>(s: impl Stream<Item = impl Future<Item = T>>) -> impl Stream<Item = T>
```

i.e. it's converting a stream of futures into a stream of the futures items. (This is using 0.3's error-less types, it's equivalent in 0.1 just more verbose to declare the error equivalencies everywhere). `create_stream` is returning a stream of items not futures.

If someone calls `create_stream` there's no way for you to force them to process items in the order you provide them, they could easily do something like

```rust
let stream = create_stream();
let first = await!(stream.next());
let second = await!(stream.next());
process(second);
process(first);
```

(again, using 0.3 + await for brevity, it's possible to construct the same situation in 0.1) and I'm not sure why you would want to explicitly disallow this.

---

The only situation that comes to mind is wanting to return items that borrow from the stream, this will have the consequence of not allowing reordering of the items, but that's just a side-effect of the borrowing not an endgoal in itself. This has the same issue that streaming iterators have in that it's dependent on generic associated types to be able to declare the trait for it:

```rust
trait StreamingStream {
    type Item<'a>;
    fn poll_next(self: Pin<&mut Self>, lw: &mut LocalWaker) -> Poll<Option<Self::Item<'_>>>;
}
```

If that trait existed it _could_ be used for the side-effect you want, and it seems likely to be experimented with once it's possible to implement.

**Comment by dominikwerder** [comment]
The processing of my stream items can, and should be done independently of each other and concurrently. But the order of the derived items must be the same as in the input stream:

```
[a, b, c, d] -> [f(a), f(b), f(c), f(d)]
```

not:

```
[a, b, c, d] -> [f(b), f(a), f(d), f(c)]
```

so, I want to use `Stream::buffered` so that N futures get polled "in parallel", but I want to make it hard to accidentially use `Stream::buffer_unordered`.

Or am I trying to use streams in a way they were never created for?

Even better would be if my stream adaptor could automatically choose between `buffered` and `buffer_unordered`, depending on what the requirements of the input stream are.

> If someone calls `create_stream` there's no way for you to force them to process items in the order you provide them, they could easily do something like

Of course, nothing can. Likewise neither the language nor type system can prevent any module of my program to accidentially memset my process memory. But it can be made harder to do such mistakes, and this is what I want.

I hope that we agree that the usage of `Stream::buffered` can be very beneficial, while an accidential `Stream::buffer_unordered` can lead do disastrous, non-deterministic and hard-to-find bugs. I want to make it harder to introduce such bugs. If you don't agree, maybe I'm using streams for the wrong purpose?

The mere existence of `Stream::buffered` seems like a sign to me that also other people have streams with ordering requirements in practice.

> (again, using 0.3 + await for brevity, it's possible to construct the same situation in 0.1) and I'm not sure why you would want to explicitly disallow this.

Simple artificial example: Data frames are coming in, each frame is an item in the stream. Some post-processing has to be done, which can be done independently for each frame and can block and is therefore a future. But after that post-processing, the frames must be in the same order as before, so that the network protocol or the file format stay valid. A bit contrived, this example, but I hope it illustrates what I mean. 😃

**Comment by Nemo157** [comment]
Thanks, that example is great, I can definitely see something like that happening if processing needs to hit some sort of database.

Personally I think in cases like this it would be obvious enough to not use `buffer_unordered` that the additional traits or whatever would be needed would add more friction than utility (e.g. having to propagate those traits through other adaptors like `.map`), I would be glad to be proved wrong though.

**Comment by cramertj** [comment]
Closing-- I'm not planning any changes here.
