### ISSUE TITLE
Stream::filter_map().collect() collects None(s)

### ISSUE THREAD

**Issue by kolbma** [rust-lang-nursery/futures-rs#1304]
In the [docs](https://docs.rs/futures/0.1.25/futures/stream/trait.Stream.html#method.filter_map) you can read "but if the predicate returns `None` then the next value will be produced".

I return `Some("string".to_string())` and sometimes `None`.
After the collect I have a `Vec` with e.g. ["string", "string", **"none"**, "string", **"none"**, "string"].

I don't think this is the purpose of the filter_map.

**Comment by tikue** [comment]
Do you have a small reproduction of this problem?

**Comment by kolbma** [comment]
This is a test which reproduces this (can't upload rs-files, so you have to rename the file):

[filter_map_test_rs.txt](https://github.com/rust-lang-nursery/futures-rs/files/2538054/filter_map_test_rs.txt)

The test reads a "log"-file and so I provide a sample log...
This file needs to be in place ./tests/filter_map_test.log or you'll have to edit the above test.rs file!

[filter_map_test.log](https://github.com/rust-lang-nursery/futures-rs/files/2538047/filter_map_test.log)

The test `filter_map_double_filter_test()` uses an additional `filter()`-call to workaround the **"none"** problem.
The test `filter_map_test()` fails with the **"none"** string after `collect()`.

So, @tikue what do you say...

**Comment by kolbma** [comment]
Ah, sorry, now I see that the problem is before. Seems that one of the idx is set to None after the unwrap. But strange that the string_slice[None..None] or whatever works and doesn't panic.

**Comment by Nemo157** [comment]
@kolbma you can use the playground for distributing easily runnable example code, [here's your test on it](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=761c99c132487e0714f4497bd1394598).

**Comment by kolbma** [comment]
Doooh. There is a relay=none in the log-file ;-)

**Comment by kolbma** [comment]
@Nemo157 I've written this with the files...

**Comment by Nemo157** [comment]
@kolbma yep, but getting files onto the playground is difficult
