### ISSUE TITLE
JoinAll / join_all() in futures-preview 0.3 ?

### ISSUE THREAD

**Issue by jamadazi** [rust-lang-nursery/futures-rs#1322]
`futures-preview` `0.3` is lacking the `JoinAll` combinator that is present in `futures` `0.1`. Why is this? Could it be implemented? If not, what is the alternative? This is useful functionality.

**Comment by alex** [comment]
It looks like the code still exists: https://github.com/rust-lang-nursery/futures-rs/blob/master/futures-util/src/future/disabled/join_all.rs but it's in a `disabled` subdirectory.

**Comment by Matthias247** [comment]
If you use async/await you can use the [join!](https://github.com/rust-lang-nursery/futures-rs/blob/d040a57521ca09d7eb162840bfb084d90d72db03/futures-util/src/async_await/join.rs) macro

**Comment by alex** [comment]
join handles a fixed number of futures, not a vec of futures

**Comment by cramertj** [comment]
There's no reason for this not having been ported other than that no one has done it yet.

**Comment by alex** [comment]
Looks like this was implemented in https://github.com/rust-lang-nursery/futures-rs/pull/1341, but it's not exposed as `futures::future::join_all`, was that intentional, or an oversight?

**Comment by Nemo157** [comment]
Definitely an oversight, a PR to expose it would be great.
