### ISSUE TITLE
Contract violation of poll_ready for Buffer

### ISSUE THREAD

**Issue by jsancio** [rust-lang-nursery/futures-rs#1344]
According to the documentation for Sink's [poll_ready](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.9/futures/sink/trait.Sink.html#required-methods)

> This method returns Poll::Ready once the underlying sink is ready to receive data. If this method returns Poll::Pending, the current task is registered to be notified (via lw.waker()) when poll_ready should be called again.

Yet there are cases in Buffer's [poll_ready](https://github.com/rust-lang-nursery/futures-rs/blob/d040a57521ca09d7eb162840bfb084d90d72db03/futures-util/src/sink/buffer.rs#L85) implementation where it doesn't register the task to be notified.

**Comment by Nemo157** [comment]
It's not very easy to see, but to get to that line it will have first called `try_empty_buffer` which must have received `Poll::Pending` from the wrapped `Sink`. That wrapped `Sink` will have registered the task to be notified once it has some capacity available. The `Buffer` itself will never acquire capacity which would require the task to be notified, it's only when the wrapped `Sink` has more space available that it can make progress.

I'm not 100% confident on that, as I mention it's not the cleanest control flow to prove it, but I'm reasonably certain it's correct.

**Comment by jsancio** [comment]
Yes. You are correct. Thanks for pointing out that subtle behavior.

**Comment by Thomasdezeeuw** [comment]
Maybe the could use a comment for people looking at it in the future.
