### ISSUE TITLE
Remove StreamObj and soft-deprecate FutureObj

### ISSUE THREAD

**Issue by Nemo157** [rust-lang-nursery/futures-rs#1352]
For some prior context see https://github.com/rust-lang-nursery/futures-rs/pull/1348

Now that futures and streams are object safe there should be no reason to use `FutureObj`/`StreamObj` directly. There are currently two reasons I know of to use these:

1. Passing around owned dynamically typed futures/streams. This can be replaced with use of the aliases below.
2. Spawning futures via [`Spawn::spawn_obj`](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.9/futures/task/trait.Spawn.html#tymethod.spawn_obj). Rather than using this directly most users can use [`SpawnExt::spawn`](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.9/futures/task/trait.SpawnExt.html#method.spawn) instead to automatically convert the future into a `FutureObj` (the only exception I know of is `no_std` use).

(am I missing any other use cases? I admit I've personally never used `FutureObj`)

Proposed additions to `futures`:

```rust
type BoxFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;
type BoxStream<'a, T> = Pin<Box<dyn Stream<Item = T> + Send + 'a>>;
```

Using `SpawnExt::spawn` for a `BoxFuture<'static, ()>` will cause a double indirection, this can be mitigated by either specialization (maybe, I don't know whether this is specializable) or an additional `SpawnExt::spawn_box` method that directly converts the boxed future into a `FutureObj`.

```rust
trait SpawnExt {
    fn spawn_box(&mut self, future: BoxFuture<'static, ()>) -> Result<(), SpawnError> { ... }
}
```

**Comment by Nemo157** [comment]
For comparison, [here's a branch](https://github.com/rust-lang-nursery/futures-rs/compare/master...Nemo157:remove-obj) adding the aliases to `futures`, and [here's a branch using that](https://github.com/rust-net-web/tide/compare/master...Nemo157:remove-obj?w=1) to remove all use of `*Obj` from `tide`.

**Comment by Nemo157** [comment]
(cc @aturon, @cramertj)

**Comment by cramertj** [comment]
it'd be nice if we could somehow default to `'static` like trait objects do naturally. Ah well, not too big of an issue I suppose.

**Comment by Nemo157** [comment]
Yeah, I did try out `type BoxFuture<'a = 'static, T>` but it appears default lifetimes aren't a thing 🙁

**Comment by ebkalderon** [comment]
I'm running into a minor problem with `futures-preview` 0.3.0-alpha.11 which prevents me from adopting `Box<dyn Future<Output = _> + Send + 'a>` over `FutureObj<'a, _>`. I can't seem to call `FutureExt::shared()` on the trait object:

```
error: the `shared` method cannot be invoked on a trait object
  --> src/main.rs:98:28
   |
98 |         future.shared()
   |                ^^^^^^
help: another candidate was found in the following trait, perhaps add a `use` for it:
   |
66 | use futures_util::future::FutureExt;
   |
```

I already have `futures::future::FutureExt` imported, and I'm able to use it elsewhere in the current module, but this one occurrence is keeping me from switching away from `FutureObj`. Any idea what might be going wrong?

**Comment by Nemo157** [comment]
@ebkalderon is this code public somewhere, I can try and track down what's going wrong (my understanding is it should be calling `shared` on the `Box<..>` since that implements `Future`, but it looks like it's instead `Deref`ing the `Box` and trying to call `shared` on the `dyn Future`).

**Comment by ebkalderon** [comment]
@Nemo157 Unfortunately, no. But I have successfully reproduced the error in a minimal verifiable example and pushed it up to a new repository here, if you would like to take a look: [ebkalderon/shared-box-future-example](https://github.com/ebkalderon/shared-box-future-example)

**Comment by Nemo157** [comment]
@ebkalderon thanks, that helped a lot.

The issue is that `Box<F>` only implements `Future` where `F: Future + Unpin`, so Rust skips `<Box<_> as FutureExt>::shared` as a candidate method and instead attempts to use a deref coercion to call `shared` directly on the `dyn Future` (because `shared` doesn't require an `Unpin` future).

The best fix for this would be to use `Pin<Box<F>>` everywhere, that should be the canonical replacement for `FutureObj`. The only difference is that it removes the ability for you to take the value out of the box in the future, but without the unstable unsized locals feature that's impossible for trait objects anyway.

I don't know if there's any way to improve the error message here, somehow tell Rust that the `impl Future for Box<F> where F: Future + Unpin` constraint failure is a higher priority to show an error message for?

**Comment by yoshuawuyts** [comment]
Relevant discussion on Runtime's use of `FutureObj` happening here: https://github.com/rustasync/runtime/issues/6#issuecomment-485391730.
