### ISSUE TITLE
Add a sink::for_each function to create a Sink from a closure

### ISSUE THREAD

**Issue by canndrew** [rust-lang-nursery/futures-rs#1360]
I want to create a `Sink` from a closure that takes values and asynchronously processes them. There should be a function in `futures::sink` which does this. I imagine the function signature looking something like this:

```rust
fn for_each<F, Fut, T, E>(f: F) -> ForEach<T, E>
where
    F: FnMut(T) -> Fut,
    Fut: Future<Output = Result<(), E>>,
{ ... }

impl Sink for ForEach<T, E> {
    type SinkItem = T;
    type SinkError = E;
    ...
}
```

**Comment by cramertj** [comment]
Closing as per the discussion on #1493.
