### ISSUE TITLE
LocalPool::poll_pool is private - how does one advances the pool as much as possible without blocking ?

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/futures-rs#1369]
I'd like to advance `LocalPool` as much as possible without blocking, i.e., I don't want to use `block_on` to block until all task finish, but I want to do as much work as can be done, and when no more work can be done, I want to do some other computation and then some time later poll the pool again. 

It appears that `LocalPool::poll_pool` is what I need, but it is private. Is there another way to do this ?

**Comment by SrTobi** [comment]
I think `LocalPool::poll_pool` does some internal stuff.

I myself needed a method that polls exactly one ready future and returns afterwards or if none is ready returns as well. I think those methods should be added to local pool. Like `poll_at_most(n: i32) -> i32` and `poll_available() -> i32`.

For the moment I used `FuturesUnordered`. @gnzlbg maybe this code helps you:

```rust
let mut pool = stream::FuturesUnordered::<FutureObj<'static, ()>>::new();

let f = async {
    println!("first");
    3
};

let handle = pool.spawn_with_handle(f).unwrap();

let mapped_f = async {
    let res = await!(handle);
    println!("second: {}", res);
};

pool.spawn(mapped_f);

// this never resolves and will stay in the pool forever.
// nevertheless the loop below will exit, as after the two previous futures
// have been resolved, no more ready futures remain in pool
pool.spawn(future::empty());


block_on(future::lazy(|lw| {
    loop {
        if let Poll::Ready(Some(_)) = pool.poll_next_unpin(lw) {
            // found one more
            println!("done one more");
        } else {
            // either more ready futures (or none at all)
            println!("nothing to do");
            break;
        }
    }
}));
```

prints:

```
first
done one more
second: 3
done one more
nothing to do
```
