### ISSUE TITLE
Release 0.1.25 source code is missing

### ISSUE THREAD

**Issue by asomers** [rust-lang-nursery/futures-rs#1400]
0.1.25 was released in October, but I can't find the source anywhere.  Both the 0.1 branch and the 0.1.25 tag are still at version 0.1.24.  Did somebody forget to push?

**Comment by teozkr** [comment]
Not a great fix, but as a workaround you can use [download a source dump from Crates](https://github.com/rust-lang/crates.io/issues/65#issuecomment-281749089) using the https://crates.io/api/v1/crates/name/version/download syntax. For example, Futures 0.1.25 would be https://crates.io/api/v1/crates/futures/0.1.25/download.

**Comment by mexus** [comment]
Just checked it out locally and found out that actually that `0.1.25` crate from https://crates.io/ corresponds to the `0.1.25` tag (with the only difference in the crate's version), so if you need to explore the source code in git just check out that tag and you'll be good.

But still it's funny that the version change has not been committed :)

**Comment by cramertj** [comment]
WONTFIXing this-- yeah, it should have been pushed, sorry, but it wasn't.
