### ISSUE TITLE
How to decode futures-rich stack traces?

### ISSUE THREAD

**Issue by asomers** [rust-lang-nursery/futures-rs#1401]
I'm writing an application using tokio.  My stack traces are mostly filled with generic functions from the futures crate like `MyApp_<futures::sync::oneshot::Receiver<T> as futures::future::Future>::poll::h5c46c2194c2bbdbf` and `MyApp_<futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::h4bb286e1fd66ba15`.  Panic messages usually have a couple of meaningful function names, so I can usually figure out what's going on.  But stack traces from my profiler are almost 100% filled with futures functions like that.  Try as I might, I can't figure out how to relate these to my code.  I think the biggest problem is that most of my futures are closures, and the closures all get inlined into their callers, where their callers are usually methods like `Future::map` or `Future::AndThen`.

I can't be the only person experiencing this problem.  How do other people profile their futures-based code?

**Comment by cramertj** [comment]
While I agree this is a concern, I don't think it's super actionable for this library. Something like the `tracing` crate might be a good fit here.
