### ISSUE TITLE
Travis CI reports “Expected - Waiting for status to be reported” on the GitHub Status API, but the status never arrives

### ISSUE THREAD

**Issue by taiki-e** [rust-lang-nursery/futures-rs#1408]
This happened at #1407.

Details and solutions are [here](https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154).

Probably only members and collaborators can fix this.

**Comment by Nemo157** [comment]
@pietroalbini are you able to fix this? I assume it's related to the migration.

**Comment by pietroalbini** [comment]
Yeah, fixed this. Sorry!
