### ISSUE TITLE
StreamExt::select is not round robin in certain cases

### ISSUE THREAD

**Issue by puckipedia** [rust-lang-nursery/futures-rs#1413]
I have a small futures 0.3 program that takes an `AllowStdIo` with stdin, which sadly blocks the event loop. Due to this, to `StreamExt::select`, one of the streams is always ready, which seems to starve the other stream. This seems to indicate (to my knowledge) that it isn't actually round robin...

**Comment by puckipedia** [comment]
(it seems that blocking the event loop in this way seems to break more than just the Select, keeping this open since i still think the documentation for StreamExt::select is unclear on this)

**Comment by Matthias247** [comment]
The `select!` macro randomizes the inputs, which prevents this. Is there actually still any good use for the old select?

**Comment by Nemo157** [comment]
Trivial merging of two streams. In fact, it seems to me that creating a new `impl Stream` using the `select!` macro easily would require something like "async generators" to allow yielding the items.

**Comment by Nemo157** [comment]
Also, this should have been fixed by #1414

**Comment by puckipedia** [comment]
looks like it! thanks!
