### ISSUE TITLE
Possible regression with mpsc channels closing early

### ISSUE THREAD

**Issue by ebkalderon** [rust-lang-nursery/futures-rs#1440]
I have a simple project which spawns a directed acyclic graph of tasks which each feed data into a `futures::channel::mpsc::Sender` while the main thread `await`s the `futures::channel::mpsc::Receiver` for progress reported from each task. The DAG is constructed by calling `future::join_all()` on a set of dependencies and then chaining the task itself with `.then()`. I have a minimal verifiable example for the code in question at [ebkalderon/sink-futures-example](https://github.com/ebkalderon/sink-futures-example).

Given the following task graph:

```
+-------+   +--------+
| first |   | second |
+-------+   +--------+
       \     /
      +-------+
      | final |
      +-------+
```

Each future forwards a `stream::once(future::ok(...))` to the `Sender`. When the code was written with `futures` 0.1.25, the `Receiver` stream results in the output:

```
Ok("first")
Ok("second")
Ok("final")
```

However, when the code is ported to `futures` 0.3.0-alpha.12, with very minimal changes, the `Receiver` stream unexpectedly closes early after the first element:

```
Ok("first")
```

I would hazard a guess that the `stream::once()` in `futures` 0.3.0-alpha.12 is causing the sink to close early, whereas the `stream::once()` in 0.1.25 does not, but I'm not familiar enough with the implementation of the `mpsc` channels to know if this is the case.

**Comment by ebkalderon** [comment]
@Nemo157 Interesting. According to the documentation for [StreamExt::forward](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.12/futures/stream/trait.StreamExt.html#method.forward), the sink is _not_ supposed to close. It should flush, but not close.

**Comment by Nemo157** [comment]
Oh, yes, that's probably the main issue here then. (I still think closing one of the senders (at least via `Sink::poll_close`) should not shut down the channel, but that wouldn't matter if `forward` was fixed).

**Comment by ebkalderon** [comment]
I updated [`StreamExt::forward`](https://github.com/rust-lang-nursery/futures-rs/blob/ebbc6be1b72b70af33e37f4106a66f8872e8c1cb/futures-util/src/stream/forward.rs#L93) to call `poll_flush()` instead of `poll_close()` on my own personal clone, but that didn't affect the output. I'll investigate `poll_close()` as well, as I'm thinking it's still being called somewhere.

**Comment by ebkalderon** [comment]
Looks like [`StreamExt::forward`](https://docs.rs/futures/0.1.25/src/futures/stream/forward.rs.html#100) in `futures` 0.1.25 also calls `close()` on the sink once it's finished forwarding. My guess is that the correct solution here is to update `poll_close()` with the correct behavior you described.

**Comment by Nemo157** [comment]
To rule out `forward` I tried changing your example code with:

```diff
diff --git src/bin/new.rs src/bin/new.rs
index e998019..e64ad4a 100644
--- src/bin/new.rs
+++ src/bin/new.rs
@@ -18,13 +18,10 @@ type MySender = Sender<Result<String, ()>>;
 pub struct JobFuture(Pin<Box<dyn Future<Output = ()> + Send>>);

 impl JobFuture {
-    fn new<S: Stream<Item = Result<String, ()>> + Send + 'static>(inner: S, tx: MySender) -> Self {
-        let future = inner
-            .map(|result| Ok(result))
-            .forward(tx.sink_map_err(|_| ()))
-            .map(|_| ());
-
-        JobFuture(Box::pin(future))
+    fn new<S: Stream<Item = Result<String, ()>> + Send + Unpin + 'static>(mut inner: S, mut tx: MySender) -> Self {
+        JobFuture(Box::pin(async move {
+            await!(tx.send(await!(inner.next()).unwrap())).unwrap();
+        }))
     }
 }

```

that gives the same result (and is definitely not closing the senders), so it looks like there's something more going on here...

**Comment by ebkalderon** [comment]
In `futures` 0.1.25, `Sender::close()` only returns `Ok(Async::Ready(()))` ([source](https://docs.rs/futures/0.1.25/src/futures/sync/mpsc/mod.rs.html#667-669)) and does _not_ close the channel. But in `futures` 0.3.0-alpha.12, it calls `Sender::close_channel()` instead ([source](https://github.com/rust-lang-nursery/futures-rs/blob/ebbc6be1b72b70af33e37f4106a66f8872e8c1cb/futures-sink/src/channel_impls.rs#L23)).

**Comment by ebkalderon** [comment]
I tried removing the `self.close_channel()` from `Sender::poll_close()` to see what would happen, and it still doesn't seem to fix the problem.

**Comment by ebkalderon** [comment]
After discussing the matter on Discord with @Nemo157, we found a solution. The way the stream was being iterated in my example code was incorrect, but it was also found that changing `StreamExt::forward` to call `poll_flush()` instead of `poll_close()` indeed fixed the issue.
