### ISSUE TITLE
no api docs

### ISSUE THREAD

**Issue by tinaun** [rust-lang-nursery/futures-rs#1459]
alpha.13 is on too new a nightly for docs.rs to build correctly, and the website is still on alpha.12

**Comment by taiki-e** [comment]
@cramertj It seems that stage2 (publish docs) was canceled because clippy failed https://github.com/rust-lang-nursery/futures-rs/runs/66484822

**Comment by Nemo157** [comment]
Just published https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.13/futures/
