### ISSUE TITLE
Possibly false information in docs

### ISSUE THREAD

**Issue by PvdBerg1998** [rust-lang-nursery/futures-rs#1464]
https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.13/futures/executor/fn.block_on.html states:
`The default spawner for the future is a thread-local executor` but I don't see a thread local executor defined and to my knowledge there is no way to `spawn` globally, so not as a method (`spawner.spawn()`).

Is this just a leftover from long ago? Or am I missing something?

**Comment by Matthias247** [comment]
Yes, it's outdated. It's just an executor on the stack, which uses an `Arc`d thread-handle for wakeups.

**Comment by PvdBerg1998** [comment]
Closing because there are/will be enough issues about outdated docs.
