### ISSUE TITLE
Document best practice for providing a futures interface to APIs which only support polling

### ISSUE THREAD

**Issue by asajeffrey** [rust-lang-nursery/futures-rs#1466]
Futures 0.3 is based on polling + wakers, where 0.1 was based on just polling. It is not obvious how to upgrade libraries which implemented futures from 0.1 to 0.3, in the case that the underlying API only supports polling and blocking.

As a concrete instance, IPC channels provided an interface to futures 0.1, but it is not obvious how to upgrade this to futures 0.3, as the underlying IPC mechanism doesn't support wakers. (https://github.com/servo/ipc-channel/issues/219) Dedicating a thread per IPC channel to supporting wakers is probably infesible (especially for one-shot channels), but it is not obvious how else to implement the futures 0.3 contract.

Is there documentation for best practice of how to deal with cases like this?

**Comment by seanmonstar** [comment]
The waker part was also present in 0.1, just tracked through a thread-local (via `task::current()`) instead of passed as an argument. Upgrading to 0.3 only means passing a `Waker` to poll methods. If underneath, the operation would actually block, then you would do nothing with the `Waker`, just like before you weren't doing anything with the `task::current()`.

However, if simply polling will park the thread, that shouldn't be exposed with async interface, since it's expected that polling is quick and won't block.

**Comment by asajeffrey** [comment]
Hmm, so in cases like ipc, where there is a non-blocking `try_recv()` and a blocking `recv()` similar to mpsc channels, what should the implementation of `poll` be? Something like:
```
fn poll(self: Pin<&mut Self>, waker: &Waker) -> Poll<Self::Output> {
    match self.try_recv() {
        Ok(val) => Poll::Ready(val),
        Err(_) => Poll::Pending,
}
```
drops the waker on the floor, will this result in the future never being re-polled, so will never be resolved? Or can futures expect that the executor will re-poll them?

**Comment by seanmonstar** [comment]
The situation is the same in 0.1 and 0.3: returning `NotReady` or `Pending` means you should have scheduled some way to notify the task/waker when it *is* ready, and most executors will **not** poll the future again until notified.

The future may sometimes be polled again anyways, such as if part of a larger future (like `join` or `select`) if another part of it notified, and it's `poll` just blindly polls all its sub-futures.

Returning `NotReady` without scheduling to notify is a common reason futures hang indefinitely.

**Comment by asajeffrey** [comment]
So what's the best practice for avoiding unresolved futures? Spinning up a per-process thread which does something like binary exponential backoff for polling?

**Comment by asajeffrey** [comment]
For the particular case of IPC, the underlying API allows selecting between IPC channels, so the cost is one thread per process to wake up IPC futures. I guess that's the best we can hope for.

So, back to the orignal question... the best practice is to spin up a thread dedicated to waking up futures?

**Comment by Matthias247** [comment]
That depends on the API that you wrap. Futures always require that some mechanism that signals completion. That one is typically already available if another asynchronous API is wrapped.

The challenge is obviously that asynchronous code always requires that
- the code below it is also asynchronous
- the code above it is also asynchronous

There is no general solution for what to do if that's not the case. Polling might with some timeout might work for some scenarios, having a thread that e.g. blocks on something (e.g. in combination with a select or WaitForMultipleObjects) and signals Future completions when required might work for other scenarios.

**Comment by asajeffrey** [comment]
Yeah, in this case the problem is that IPC channels aren't provided with a waker by the OS, so a thread is needed. Ah well, perhaps there isn't general advice about how to do this.
