### ISSUE TITLE
early return from `AndThen` struct

### ISSUE THREAD

**Issue by GopherJ** [rust-lang-nursery/futures-rs#1474]
Hello, I'm new to rust and sometimes I need to return earlier from a function which return `impl Future` but have no idea how to create an `AndThen` value. Any idea and any help will be appreciated. Thanks.

`code`
![Screenshot from 2019-03-11 12-02-14](https://user-images.githubusercontent.com/33961674/54172720-50e17900-447f-11e9-8f2d-8edf5938282d.png)

`error message`
![Screenshot from 2019-03-11 12-07-08](https://user-images.githubusercontent.com/33961674/54172700-3effd600-447f-11e9-8b15-09b1a28f7041.png)

**Comment by realcr** [comment]
@GopherJ : Welcome to the world of Rust, great adventures are lying ahead!
The first thing you should know is that any Rust function can return only one type, even if you are using `impl X` as the return value. In your case your function attempts to return two different return values, which is impossible.

I can think of two options you can go here. You could Box your result (But this will cost you an allocation), or you could use a wrapper type, something like [Either](https://docs.rs/either/1.5.1/either/). I wrote about this a while ago, not for futures but for iterators. It might get you started though. Check this post: https://www.freedomlayer.org/offst/option-iterator/

I am pretty sure we used to have an Either inside futures-rs, and also inside Rust std, but I couldn't find them now. Maybe they were removed. I am not sure if the implementation of Either create automatically derives Future. If it doesn't, you can create your own one.

**Comment by Pauan** [comment]
With Futures 0.3, another option is to use async/await, which supports pretty much all of Rust's features (`if`, `match`, looping, etc.)

**Comment by GopherJ** [comment]
@realcr @Pauan Thanks for your help, I still can't find a way to solve this problem.

**Comment by laizy** [comment]
try `return Box::new(yourFuture)`

**Comment by GopherJ** [comment]
![Screenshot from 2019-03-13 12-04-28](https://user-images.githubusercontent.com/33961674/54274380-3c3cd800-4588-11e9-857d-c62287359959.png)
