### ISSUE TITLE
0.1.24 adds dependency on nightly

### ISSUE THREAD

**Issue by tsuckow** [rust-lang-nursery/futures-rs#1480]
0.1.24 added a dependency on nightly with feature(pin) which was is slightly unexpected and not documented on the 0.1 branch and crates.io pushes people to 0.1.25.

**Comment by seanmonstar** [comment]
Is there an issue to report here? 0.1.24 doesn't *require* nightly, it added an optional cargo feature *called* "nightly".

**Comment by tsuckow** [comment]
You are right. I pulled in a different package that wanted tokio async-await-preview which in turn triggered futures/nightly. Then I misinterpreted the "#![feature] may not be used on the stable release channel" not understanding the feature guard.

My apologies
