### ISSUE TITLE
impl AsyncWrite for Cursor<Vec<u8>> doesn't extend vector as needed

### ISSUE THREAD

**Issue by Nemo157** [rust-lang-nursery/futures-rs#1510]
This implementation is currently provided by [`impl<T: AsMut<[u8]>> AsyncWrite for Cursor<T>`](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.13/futures/io/trait.AsyncWrite.html#impl-AsyncWrite-1) which doesn't allow it to know that the vector is extendable. `std` provides a separate [`impl io::Write for Cursor<Vec<u8>>`](https://doc.rust-lang.org/nightly/std/io/trait.Write.html#impl-Write-2) which extends the vector as needed, but this means it can't provide a generic version.

We're also missing the direct `impl AsyncWrite for Vec<u8>` which could be used instead (EDIT: Added in #1511). It almost seems like we should drop the `Cursor` wrapped implementations until we get an `AsyncSeek` trait available?

**Comment by Nemo157** [comment]
Actually the `Cursor` implementations are still useful as they allow reading off how many bytes were read/written after operating on it.

---

One thing that may be worth looking into is whether `std` plans to use specialization to get both generic implementations and an override that extends `Vec` as needed, that seems to me to be the best endpoint, but maybe there are reasons not to do it.

**Comment by yoshuawuyts** [comment]
>  until we get an AsyncSeek trait available?

Chiming in here: I've def been missing an `AsyncSeek` impl. We've been looking to implement a filesystem API for Romio, and that's one of the traits we need. Tokio has [a counterpart](https://docs.rs/tokio-fs/0.1.6/tokio_fs/file/struct.File.html#method.poll_seek) directly implemented on the File struct, but it seems being able to generalize it would be ideal.

**Comment by Nemo157** [comment]
Test commit providing this behaviour via specialization: https://github.com/rust-lang-nursery/futures-rs/commit/7997066642e5120db44f9eb7ceac612ca7411316.

**Comment by cramertj** [comment]
@Nemo157 
> It almost seems like we should drop the Cursor wrapped implementations until we get an AsyncSeek trait available?

https://github.com/rust-lang-nursery/futures-rs/pull/1553 added `AsyncSeek`-- what would you like to see happen on this issue?

**Comment by Nemo157** [comment]
The main issue is still that `impl std::io::Write for Cursor<Vec<u8>>` and `impl futures::io::AsyncWrite for Cursor<Vec<u8>>` behave differently, the former will extend the vector as data is written to fit it, the latter will return EOF when attempting to write past the current length.
