### ISSUE TITLE
AsyncSeek trait

### ISSUE THREAD

**Issue by Nemo157** [rust-lang-nursery/futures-rs#1512]
I've def been missing an `AsyncSeek` impl. We've been looking to implement a filesystem API for Romio, and that's one of the traits we need. Tokio has [a counterpart](https://docs.rs/tokio-fs/0.1.6/tokio_fs/file/struct.File.html#method.poll_seek) directly implemented on the File struct, but it seems being able to generalize it would be ideal.

_Originally posted by @yoshuawuyts in https://github.com/rust-lang-nursery/futures-rs/issues/1510#issuecomment-479420306_

**Comment by Nemo157** [comment]
@yoshuawuyts do you know if there are actual async implementations of seeking available anywhere? I assume the FS API for Romio would just be doing something like a blocking seek on a thread-pool?

I guess it still makes sense to add the trait as an operation that code will want to use, even if there aren't any implementations that can cheaply support it yet.

**Comment by yoshuawuyts** [comment]
> @yoshuawuyts do you know if there are actual async implementations of seeking available anywhere? I assume the FS API for Romio would just be doing something like a blocking seek on a thread-pool?

Yeah, that's our thinking for Romio currently. Ideally we could later investigate using AIO / io_uring to have _true_ async fs calls, but until then having the trait available would be nice for all implementations (:

**Comment by LucioFranco** [comment]
Just gonna leave this here, we have a PR open in tokio for sometime around this, may be useful https://github.com/tokio-rs/tokio/pull/785

**Comment by yoshuawuyts** [comment]
Thanks so much @taiki-e! 🎉

**Comment by cramertj** [comment]
Yeah-- huge thanks @taiki-e! All of your recent work on futures-rs has been incredibly helpful <3
