### ISSUE TITLE
Does futures_cpupool still exist? (in futures 0.3)

### ISSUE THREAD

**Issue by DCjanus** [rust-lang-nursery/futures-rs#1517]
Does [futures_cpupool](https://crates.io/crates/futures-cpupool) still exist in this repo? Or is there anything that can replace it?

**Comment by yoshuawuyts** [comment]
@DCjanus perhaps [Juliex](https://docs.rs/juliex/0.3.0-alpha.2/juliex/) might fit your needs.

It has a `spawn` shorthand method that sets up a backing threadpool behind the scenes and just work.

And it has a `Threadpool` constructor that can come in handy when you need to setup thread-locals for your app.

**Comment by DCjanus** [comment]
Thanks! @yoshuawuyts

**Comment by DCjanus** [comment]
It seems that juliex does not cover all futures_cpupool usage. 

For example, If I want to implement a async file IO library, and I don't want to use AIO in Linux, which means I have to put block task to separate thread pool and await this task in main executor.

futures_cpupool provided a good abstraction for this: "await a Future in other executor".

**Comment by taiki-e** [comment]
CpuPool has been renamed to [ThreadPool](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.16/futures/executor/struct.ThreadPool.html) and incorporated to `futures::executor` (see https://github.com/rust-lang-nursery/futures-rs/commit/8198563d7aa970fda052f9d09e2837da89d062dc).

**Comment by laizy** [comment]
@DCjanus , I think what you want is [spawn_with_handle](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.16/futures/task/trait.SpawnExt.html#method.spawn_with_handle), then the code use cpupool :
```rust
let result_fut = cpu_pool.spawn(long_running_future);
```
can be replaced with `ThreadPool` or `juliex`:
```rust 
let result_fut = thread_pool.spawn_with_handle(long_running_future).unwrap();
```

**Comment by Nemo157** [comment]
Is `futures::executor::ThreadPool` appropriate to run blocking work on though? The purpose of `futures-cpupool` was a place to run blocking synchronous work and get a handle that will resolve with the result. As far as I'm aware `ThreadPool` is intended as a very basic futures executor, which means it will likely be making tradeoffs targeted at running non-blacking asynchronous work.

**Comment by DCjanus** [comment]
@laizy Thanks for your help, spawn_with_handle is do helpful to me.

**Comment by DCjanus** [comment]
@Nemo157 My problem has been solved, but seems that you got more idea about this, I am not sure if I should close this issue.

If you think this issue could be done, please just close this issue; if you want to keep track this idea in this issue, maybe you want to keep this issue open.
