### ISSUE TITLE
Missing method errors using AsyncRead 

### ISSUE THREAD

**Issue by chmln** [rust-lang-nursery/futures-rs#1536]
This may not be the correct place to post this, but I am running into weird errors trying to use `AsyncRead`.

Here is a narrowed down snippet illustrating the error (also uploaded at https://github.com/chmln/fut-err):

```rust
use futures;

pub struct LineStream<T: futures::io::AsyncRead> {
    inner: T,
}

impl<T: futures::io::AsyncRead> LineStream<T> {
    pub fn new(inner: T) -> Self {
        inner.poll_read();
        Self { inner }
    }
}
```

Error:
```
error[E0599]: no method named `poll_read` found for type `T` in the current scope
 --> src/main.rs:9:15
  |
9 |         inner.poll_read();
  |               ^^^^^^^^^
  |
  = help: items from traits can only be used if the trait is implemented and in scope
  = note: the following trait defines an item `poll_read`, perhaps you need to implement it:
          candidate #1: `futures_io::if_std::AsyncRead`

error: aborting due to previous error
```

Based on the suggestion I've tried adding `std` and `nightly` feature flags but that did not help either.

Extra Info:
```
$ rustc +nightly --version
rustc 1.36.0-nightly (3c3d3c177 2019-04-17)
```

```
[dependencies]
futures-preview = { version = "0.3.0-alpha.14" }
```

**Comment by Nemo157** [comment]
This is because `poll_read` takes `self: Pin<&mut Self>`, you need to explicitly wrap `inner` into a pinned reference (unlike `&mut self` etc. this is not done automatically by Rust):

```rust
core::pin::Pin::new(&mut inner).poll_read(unimplemented!(), unimplemented!());
```

This is a pretty terrible error message for forgetting that though, I'll make sure there's an upstream issue about improving the error message to mention the expected type.

**Comment by taiki-e** [comment]
> This is a pretty terrible error message for forgetting that though, I'll make sure there's an upstream issue about improving the error message to mention the expected type.

https://github.com/rust-lang/rust/issues/59269

**Comment by Nemo157** [comment]
Opened https://github.com/rust-lang/rust/issues/60086

**Comment by chmln** [comment]
Thanks for clearing that up @Nemo157 :+1:
