### ISSUE TITLE
FusedFuture::is_terminated is called on wake in select before poll

### ISSUE THREAD

**Issue by DoumanAsh** [rust-lang-nursery/futures-rs#1540]
I've been playing with `futures::select` for my test and noticed a bit unexpected behavior for how `select` macro uses the `FusedFuture`

Currently it seems that before polling `select` macro calls `is_terminated` to check whether the future is already inactive.
But the thing is that when I wake task, my future completes and ready (the way it is done, if future is ready, then it is terminated too).

Is it intentional that `is_terminated` called before `poll` instead of being called on `Pending` after `poll`?

**Comment by Nemo157** [comment]
This is the correct behaviour, `is_terminated` returns `true` _when the future should no longer be polled_, for a normal future this must be _after_ it has returned `Poll::Ready`, if it hasn't yet returned its value it should still be polled.

The documentation on `FusedFuture` should probably be improved to make this clearer to implementors.

**Comment by DoumanAsh** [comment]
I see, very well, then it is not suitable trait for my futures.

But you're right about docs, `FusedFuture` need to expand on its contract to emphasis that it is always should be used before `Future::poll`

**Comment by cramertj** [comment]
> if future is ready, then it is terminated too

That's not quite how the `FusedFuture` trait works. As [mentioned in the docs](https://docs.rs/futures-preview/0.3.0-alpha.14/futures/future/trait.FusedFuture.html), ``is_terminated` returns true if a future should no longer be polled, a state that is usually reached after polling results in `Poll::Ready`. `is_terminated` shouldn't return true if your future should still be polled.
