### ISSUE TITLE
`SinkExt::send` and `send_all`, and `StreamExt::next` should not need `Self: Unpin`

### ISSUE THREAD

**Issue by Ekleog** [rust-lang-nursery/futures-rs#1547]
There is, as far as I understand, no theoretical reason for `send` or `send_all` to require `Self: Unpin`.

The only reason being that the current implementation requires it, changing the implementation to not require `Self: Unpin` would be great.

**Comment by taiki-e** [comment]
If you want to remove `Self: Unpin` from `send` or `send_all`, it needs to change that method to consume `self`. IMO, I do not think it is convenient for those methods to consume `self` (If it does not want to consume, it need to take a mutable reference, that requires `Self: Unpin`).

**Comment by Nemo157** [comment]
Yeah, this is sort of the same situation as `StreamExt::next` that you will want to manually pin an `Unpin` stream so that you have the choice between the more-powerful-less-performant heap pinning and the less-powerful-more-performant stack pinning. These methods should probably have a paragraph like that included in `next`'s documentation:

> Note that because next doesn't take ownership over the stream, the Stream type must be Unpin. If you want to use next with a !Unpin stream, you'll first have to pin the stream. This can be done by boxing the stream using Box::pin or pinning it to the stack using the pin_mut! macro from the pin_utils crate.

Although, since this is a relatively common requirement it could be good to have a more expanded section in some central docs about pinning that all these methods link to?

**Comment by Ekleog** [comment]
Couldn't these functions just take `Pin<&mut Self>`, and not consume ownership of the stream/sink?

**Comment by Nemo157** [comment]
That's more annoying to work with than taking `&mut Self`. With the current signature you can call it with an `Unpin` sink without pinning it, or with a `?Unpin` sink by pinning it and calling the method on the pinned reference (which causes a double indirection, but this should be easily eliminated by the compiler). If it took `Pin<&mut Self>` you would still need to pin a `?Unpin` sink to call it (and then use `sink.as_mut().send(foo)` every time to re-borrow the pin), but you would also need to pin an `Unpin` sink to call it. You would reduce the compilers work by eliminating the double indirection, but that seems very easy to optimize.

**Comment by Ekleog** [comment]
Pinning an `Unpin` sink is almost free, though: it's a safe `Pin::new(&mut sink)` away.

OTOH, it's basically impossible to use these functions from a `!Unpin` sink if one does not want to be adding meaningless indirections all around.

**Comment by Nemo157** [comment]
It still adds code-readability overhead

```rust
await!(sink.send(foo))?;
let bar = process(await!(stream.next())?);
await!(sink.send(bar))?;
```

vs

```rust
await!(Pin::new(&mut sink).send(foo))?;
let bar = process(await!(Pin::new(&mut stream).next())?);
await!(Pin::new(&mut sink).send(bar))?;
```

or

```rust
let (sink, stream) = (Pin::new(&mut sink), Pin::new(&mut stream));
await!(sink.as_mut().send(foo))?;
let bar = process(await!(stream.as_mut().next())?);
await!(sink.as_mut().send(bar))?;
```

The majority of concrete `Sink`s are likely to be `Unpin`, and when working with generic sinks you will commonly want to request an `Unpin` sink and push the pinning requirement up to your callers (it will probably be worth having some guidelines around when you want to have `+ Unpin` and when you should stack-pin yourself once there's more familiarity with which is better).

**Comment by Ekleog** [comment]
Well, it does add code-readability overhead, but with the current implementation handling generic `Sink`s is basically impossible. And I definitely do *not* want to request an `Unpin` sink from my caller if I don't need to, as that's against Rust's 0-cost philosophy.

I could see some use in a `.send_unpin()` that requires `Self: Unpin`, but having it being the only provided one appears wrong to me. Also, it's trivial to write `.send_unpin()` as a wrapper over `.send()`, while the opposite is not true.

Finally, I would like to contest this claim:
> The majority of concrete Sinks are likely to be Unpin,

While this might be true *today*, it will certainly no longer be true once async `Stream`s are finally there. And designing code while knowing it will become unusable when the `Future` ecosystem finally become usable sounds like a weird idea to me.

**Comment by taiki-e** [comment]
> While this might be true _today_, it will certainly no longer be true once async `Stream`s are finally there. And designing code while knowing it will become unusable when the `Future` ecosystem finally become usable sounds like a weird idea to me.

Assuming that the stream generated by `#[async_stream]` is likely not to implement `Unpin`, the following method may be useful. (but, the existing method is useful in many situations, so I prefer not to change it.)

```rust
pin_mut!(stream);
while let Some(item) = await!(stream.as_mut().next_pinned()) {
     /* ... */
}
```

**Comment by Ekleog** [comment]
I kind of agree that the existing method should still exist, what I argue is for it to exist under another name, so that the most obvious name is also the 0-cost one, to try and follow Rust's philosophy. Hence my suggestion of making `send` & co. take `Pin<&mut Self>` without requiring `Self: Unpin` and to add a `send_unpin` that does require `Self: Unpin` like:
```rust
fn send_unpin(&mut self, item: Item) -> Send<Self, Item> {
    Pin::new(&mut self).send(item)
}
```

As for the stream generated by `#[async_stream]`, if it is like futures then it will be `!Unpin` as soon as a borrow will live across an `await` point, which will quite likely be pretty often (after all that's exactly the reason why `Pin` was introduced in the first place, though other use cases also called for it)

**Comment by Nemo157** [comment]
@taiki-e Note that because `Pin<&mut impl Stream>: Stream + Unpin` this already works for `!Unpin` streams:

```rust
pin_mut!(stream);
while let Some(item) = await!(stream.next()) {
     /* ... */
}
```

**Comment by taiki-e** [comment]
@Nemo157 Oops, you are right.

**Comment by cramertj** [comment]
Closing this-- the choice of these methods taking `&mut self` and requiring `Self: Unpin` was intentional. If you wish to use these methodson `!Unpin` types, you have to first pin them, either by boxing or by using `pin_utils::pin_mut`.

**Comment by Ekleog** [comment]
@cramertj So the choice to adopt an interface that goes in frontal opposition with rust's philosophy (ie. pointlessly making it way harder to do things the 0-cost way by not providing a more general method) was a design choice? That's sad, I must say I can only hope these will not get upstream to `std`, and people won't foolishly do like me and assume that as `futures-rs` is under `rust-lang-nursery` it's following that philosophy…

**Comment by cramertj** [comment]
It's not a more general method. It allows exactly the same functionality as would be allowed in the other case (taking `Pin<&mut Self>` on `T` vs. taking `&mut Self` on a `Pin<&mut T>`). It's making the API more ergonomic in the common case with an `Unpin` `Self` type.

**Comment by Ekleog** [comment]
Then why is https://doc.rust-lang.org/std/future/trait.Future.html#tymethod.poll taking `Pin<&mut Self>` and not `&mut Self where Self: Unpin`? This choice is even inconsistent with the choice stdfutures made.

And your point about “the common case with an `Unpin` `Self`” has already been answered above: https://github.com/rust-lang-nursery/futures-rs/issues/1547#issuecomment-486229706.

Anyway, I understand that you won't change your mind and this is my last message here, as I'm pointlessly losing energy arguing.
