### ISSUE TITLE
`proc_macro_span` feature used on "stable" builds

### ISSUE THREAD

**Issue by Nemo157** [rust-lang-nursery/futures-rs#1564]
With the changes from #1555 we are now attempting to build with something equivalent to what will be the 1.36 compiler. Unfortunately https://github.com/rust-lang/rust/pull/60289 has revealed that `proc-macro2` is using an unstable feature when it's built on nightly, which has broken those CI builds.

I've opened https://github.com/alexcrichton/proc-macro2/issues/175 to see if we can get a way to disable that feature in `proc-macro2`, but if we can't do that soon I'll probably revert the Travis changes from #1555 until it happens.

**Comment by taiki-e** [comment]
I think we can use `RUSTFLAGS="-Z allow-features=proc_macro_span"` temporarily.

**Comment by Nemo157** [comment]
@taiki-e great idea, I’ll open a PR in a bit.

**Comment by Nemo157** [comment]
#1565 added that workaround, leaving this open till we hear back about `proc-macro2` changing so we can hopefully remove that.

**Comment by taiki-e** [comment]
(We probably can remove `proc_macro_span` from allow-features because https://github.com/alexcrichton/proc-macro2/pull/176 merged and proc-macro2 4.29 released.)
