### ISSUE TITLE
thread panicked at 'Receiver::next_message called after `None`'

### ISSUE THREAD

**Issue by tokahuke** [rust-lang-nursery/futures-rs#1567]
Hello! I have been getting this strange panic here working with futures 0.3 MPSC channels. The following code (details omitted) panics while polling `self.receiver.next()`. I find it strange. It has never happened to me before. Besides, I have lurked through the documentation and found that `Receiver<T>` implements `FusedStream`. So... that condition of calling `poll_next` (or `next_message` (private method?), in my case) after `None` should not happen... right?

```rust
pub async fn fetch(&mut self) -> Result<Vec<I::Content>, Error> {
        let mut batch = Vec::with_capacity(self.stride as usize);
        for _ in 0..self.stride {
            match await!(self.receiver.next()) {
                Some(Ok(event_bits)) => {
                    /* deserialize stuff here */?;
                    batch.push(/* deserialized stuff */?);
                }
                Some(Err(err)) => return Err(Error::Storage(err)),
                None => return Ok(batch),
            }
        }

        Ok(batch)
    }
```

The stack trace in debug mode is the following (again, details omitted):

```
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::option::expect_failed
             at src/libcore/option.rs:1036
   9: core::option::Option<T>::expect
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288/src/libcore/option.rs:314
  10: futures_channel::mpsc::Receiver<T>::next_message
             at /home/pedro/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-channel-preview-0.3.0-alpha.14/src/mpsc/mod.rs:840
  11: <futures_channel::mpsc::Receiver<T> as futures_core::stream::Stream>::poll_next
             at /home/pedro/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-channel-preview-0.3.0-alpha.14/src/mpsc/mod.rs:910
  12: <futures_util::stream::next::Next<St> as core::future::future::Future>::poll
             at /home/pedro/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.14/src/stream/next.rs:34
  13: std::future::poll_with_tls_context::{{closure}}
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288/src/libstd/future.rs:113
  14: std::future::get_task_context
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288/src/libstd/future.rs:104
  15: std::future::poll_with_tls_context
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288/src/libstd/future.rs:113
  16: event_api::db::indexed_cursor::IndexedCursor<I>::fetch::{{closure}}
             at src/db/indexed_cursor.rs:81
(...)
```

My specs are the following:

- Ubuntu 18, x64.
- rustc 1.35.0-nightly (70f130954 2019-04-16)
- futures-preview 0.3.0-alpha.14 (checksum bb4443b7b07cb01f3e9ad819456b0a9f3625b5dd885e8f8da6141c6b929fc07d in Cargo.lock)
- `LocalPool` executor, _not_ the usual `ThreadPool`.

I will try and see if using `Fused` will fix this for the time being, although this behaviour has been unexpected.

**Comment by Nemo157** [comment]
`FusedStream` doesn't have the same meaning as `FusedIterator`, it allows a user of the type to check whether the stream has been completed before polling, but doesn't guarantee that the stream will return `Async::Ready(None)` if it is polled again.

The `Fuse` adaptor does have this guarantee, so you should be using that if you might be calling `fetch` again after the underlying `receiver` has finished.

**Comment by tokahuke** [comment]
Thanks! It worked.

... though I would still complain that it is pretty hard to guess that from the documentation. In special, there is nowhere explicitly warning that calling `next` on a `Receiver<T>` might result in a panic on such conditions.

**Comment by seanmonstar** [comment]
https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.15/futures/stream/trait.Stream.html#tymethod.poll_next

**Comment by cramertj** [comment]
Closing as WAI.
