### ISSUE TITLE
The lib needs more example to show how to use/learn 

### ISSUE THREAD

**Issue by zys864** [rust-lang-nursery/futures-rs#1581]
The newest lib(0.3 alpha) has a few example/demonstrates to help the beginners learning easily.

**Comment by yoshuawuyts** [comment]
Perhaps https://rust-lang.github.io/async-book/ might be of help.

If we aren't linking to it from the README, we probably should.

**Comment by cramertj** [comment]
I don't think we should link it before it is updated, but now is probably a good time to start updating the book given that there is a rough consensus on `async`/`await` syntax and the `futures_api` feature has stabilized.
