### ISSUE TITLE
using select on an async fn that was into_streamed does not compile

### ISSUE THREAD

**Issue by JuanPotato** [rust-lang-nursery/futures-rs#1582]
I'm trying to experiment with the new futures library and was trying to use select on an async fn and another stream when I found that trying to use it on an async fn that was into_streamed (not sure what other ways I could make the future into a stream) doesn't compile.

```rust
#![feature(async_await, await_macro)]

use std::io;
use futures::{executor, FutureExt, StreamExt};

fn main() -> io::Result<()> {
    executor::block_on(async {
        let a = bar();
        let b = foo();

        let s = futures::stream::select(a.into_stream(), b.into_stream());
        await!(s.next());

        Ok(())
    })
}

async fn bar() -> u32 {
    return 20;
}

async fn foo() -> u32 {
    return 10;
}
```

Originally I wanted to use this to have a function that was receiving packets from a server and the async fn would return the new packets while another stream was receiving user requests from a channel.

the `await!(s.next());` line causes this not to build. The Error being

```
error[E0277]: the trait bound `std::future::GenFuture<[static generator@src/main.rs:19:23: 21:2 {}]>: std::marker::Unpin` is not satisfied in `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`
```

<details><summary>Full error log</summary>

<pre>
error[E0277]: the trait bound `std::future::GenFuture<[static generator@src/main.rs:19:23: 21:2 {}]>: std::marker::Unpin` is not satisfied in `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`
  --> src/main.rs:13:18
   |
13 |         await!(s.next());
   |                  ^^^^ within `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`, the trait `std::marker::Unpin` is not implemented for `std::future::GenFuture<[static generator@src/main.rs:19:23: 21:2 {}]>`
   |
   = help: the following implementations were found:
             <std::future::GenFuture<T> as std::marker::Unpin>
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required because it appears within the type `std::option::Option<impl core::future::future::Future>`
   = note: required because it appears within the type `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`
   = note: required because of the requirements on the impl of `std::marker::Unpin` for `futures_util::stream::select::Select<futures_util::future::into_stream::IntoStream<impl core::future::future::Future>, futures_util::future::into_stream::IntoStream<impl core::future::future::Future>>`

error[E0277]: the trait bound `std::future::GenFuture<[static generator@src/main.rs:23:23: 25:2 {}]>: std::marker::Unpin` is not satisfied in `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`
  --> src/main.rs:13:18
   |
13 |         await!(s.next());
   |                  ^^^^ within `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`, the trait `std::marker::Unpin` is not implemented for `std::future::GenFuture<[static generator@src/main.rs:23:23: 25:2 {}]>`
   |
   = help: the following implementations were found:
             <std::future::GenFuture<T> as std::marker::Unpin>
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required because it appears within the type `std::option::Option<impl core::future::future::Future>`
   = note: required because it appears within the type `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`
   = note: required because of the requirements on the impl of `std::marker::Unpin` for `futures_util::stream::select::Select<futures_util::future::into_stream::IntoStream<impl core::future::future::Future>, futures_util::future::into_stream::IntoStream<impl core::future::future::Future>>`

error[E0277]: the trait bound `std::future::GenFuture<[static generator@src/main.rs:19:23: 21:2 {}]>: std::marker::Unpin` is not satisfied in `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`
  --> src/main.rs:13:9
   |
13 |         await!(s.next());
   |         ^^^^^^^^^^^^^^^^^ within `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`, the trait `std::marker::Unpin` is not implemented for `std::future::GenFuture<[static generator@src/main.rs:19:23: 21:2 {}]>`
   |
   = help: the following implementations were found:
             <std::future::GenFuture<T> as std::marker::Unpin>
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required because it appears within the type `std::option::Option<impl core::future::future::Future>`
   = note: required because it appears within the type `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`
   = note: required because of the requirements on the impl of `std::marker::Unpin` for `futures_util::stream::select::Select<futures_util::future::into_stream::IntoStream<impl core::future::future::Future>, futures_util::future::into_stream::IntoStream<impl core::future::future::Future>>`
   = note: required because of the requirements on the impl of `core::future::future::Future` for `futures_util::stream::next::Next<'_, futures_util::stream::select::Select<futures_util::future::into_stream::IntoStream<impl core::future::future::Future>, futures_util::future::into_stream::IntoStream<impl core::future::future::Future>>>`
   = note: required by `std::future::poll_with_tls_context`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0277]: the trait bound `std::future::GenFuture<[static generator@src/main.rs:23:23: 25:2 {}]>: std::marker::Unpin` is not satisfied in `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`
  --> src/main.rs:13:9
   |
13 |         await!(s.next());
   |         ^^^^^^^^^^^^^^^^^ within `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`, the trait `std::marker::Unpin` is not implemented for `std::future::GenFuture<[static generator@src/main.rs:23:23: 25:2 {}]>`
   |
   = help: the following implementations were found:
             <std::future::GenFuture<T> as std::marker::Unpin>
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required because it appears within the type `std::option::Option<impl core::future::future::Future>`
   = note: required because it appears within the type `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`
   = note: required because of the requirements on the impl of `std::marker::Unpin` for `futures_util::stream::select::Select<futures_util::future::into_stream::IntoStream<impl core::future::future::Future>, futures_util::future::into_stream::IntoStream<impl core::future::future::Future>>`
   = note: required because of the requirements on the impl of `core::future::future::Future` for `futures_util::stream::next::Next<'_, futures_util::stream::select::Select<futures_util::future::into_stream::IntoStream<impl core::future::future::Future>, futures_util::future::into_stream::IntoStream<impl core::future::future::Future>>>`
   = note: required by `std::future::poll_with_tls_context`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `awaitesting`.

To learn more, run the command again with --verbose.
error[E0277]: the trait bound `std::future::GenFuture<[static generator@src/main.rs:19:23: 21:2 {}]>: std::marker::Unpin` is not satisfied in `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`
  --> src/main.rs:13:18
   |
13 |         await!(s.next());
   |                  ^^^^ within `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`, the trait `std::marker::Unpin` is not implemented for `std::future::GenFuture<[static generator@src/main.rs:19:23: 21:2 {}]>`
   |
   = help: the following implementations were found:
             <std::future::GenFuture<T> as std::marker::Unpin>
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required because it appears within the type `std::option::Option<impl core::future::future::Future>`
   = note: required because it appears within the type `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`
   = note: required because of the requirements on the impl of `std::marker::Unpin` for `futures_util::stream::select::Select<futures_util::future::into_stream::IntoStream<impl core::future::future::Future>, futures_util::future::into_stream::IntoStream<impl core::future::future::Future>>`

error[E0277]: the trait bound `std::future::GenFuture<[static generator@src/main.rs:23:23: 25:2 {}]>: std::marker::Unpin` is not satisfied in `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`
  --> src/main.rs:13:18
   |
13 |         await!(s.next());
   |                  ^^^^ within `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`, the trait `std::marker::Unpin` is not implemented for `std::future::GenFuture<[static generator@src/main.rs:23:23: 25:2 {}]>`
   |
   = help: the following implementations were found:
             <std::future::GenFuture<T> as std::marker::Unpin>
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required because it appears within the type `std::option::Option<impl core::future::future::Future>`
   = note: required because it appears within the type `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`
   = note: required because of the requirements on the impl of `std::marker::Unpin` for `futures_util::stream::select::Select<futures_util::future::into_stream::IntoStream<impl core::future::future::Future>, futures_util::future::into_stream::IntoStream<impl core::future::future::Future>>`

error[E0277]: the trait bound `std::future::GenFuture<[static generator@src/main.rs:19:23: 21:2 {}]>: std::marker::Unpin` is not satisfied in `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`
  --> src/main.rs:13:9
   |
13 |         await!(s.next());
   |         ^^^^^^^^^^^^^^^^^ within `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`, the trait `std::marker::Unpin` is not implemented for `std::future::GenFuture<[static generator@src/main.rs:19:23: 21:2 {}]>`
   |
   = help: the following implementations were found:
             <std::future::GenFuture<T> as std::marker::Unpin>
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required because it appears within the type `std::option::Option<impl core::future::future::Future>`
   = note: required because it appears within the type `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`
   = note: required because of the requirements on the impl of `std::marker::Unpin` for `futures_util::stream::select::Select<futures_util::future::into_stream::IntoStream<impl core::future::future::Future>, futures_util::future::into_stream::IntoStream<impl core::future::future::Future>>`
   = note: required because of the requirements on the impl of `core::future::future::Future` for `futures_util::stream::next::Next<'_, futures_util::stream::select::Select<futures_util::future::into_stream::IntoStream<impl core::future::future::Future>, futures_util::future::into_stream::IntoStream<impl core::future::future::Future>>>`
   = note: required by `std::future::poll_with_tls_context`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0277]: the trait bound `std::future::GenFuture<[static generator@src/main.rs:23:23: 25:2 {}]>: std::marker::Unpin` is not satisfied in `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`
  --> src/main.rs:13:9
   |
13 |         await!(s.next());
   |         ^^^^^^^^^^^^^^^^^ within `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`, the trait `std::marker::Unpin` is not implemented for `std::future::GenFuture<[static generator@src/main.rs:23:23: 25:2 {}]>`
   |
   = help: the following implementations were found:
             <std::future::GenFuture<T> as std::marker::Unpin>
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required because it appears within the type `std::option::Option<impl core::future::future::Future>`
   = note: required because it appears within the type `futures_util::future::into_stream::IntoStream<impl core::future::future::Future>`
   = note: required because of the requirements on the impl of `std::marker::Unpin` for `futures_util::stream::select::Select<futures_util::future::into_stream::IntoStream<impl core::future::future::Future>, futures_util::future::into_stream::IntoStream<impl core::future::future::Future>>`
   = note: required because of the requirements on the impl of `core::future::future::Future` for `futures_util::stream::next::Next<'_, futures_util::stream::select::Select<futures_util::future::into_stream::IntoStream<impl core::future::future::Future>, futures_util::future::into_stream::IntoStream<impl core::future::future::Future>>>`
   = note: required by `std::future::poll_with_tls_context`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `awaitesting`.

To learn more, run the command again with --verbose.
</pre>

</details>

**Comment by JuanPotato** [comment]
I now realize I could use `futures::future::select` but that breaks too.

<details><summary>Full error log</summary>

<pre>
error[E0277]: the trait bound `std::future::GenFuture<[static generator@src/main.rs:18:23: 20:2 {}]>: std::marker::Unpin` is not satisfied in `impl core::future::future::Future`
  --> src/main.rs:12:17
   |
12 |         let s = futures::future::select(a, b);
   |                 ^^^^^^^^^^^^^^^^^^^^^^^ within `impl core::future::future::Future`, the trait `std::marker::Unpin` is not implemented for `std::future::GenFuture<[static generator@src/main.rs:18:23: 20:2 {}]>`
   |
   = help: the following implementations were found:
             <std::future::GenFuture<T> as std::marker::Unpin>
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required by `futures_util::future::select::select`

error[E0277]: the trait bound `std::future::GenFuture<[static generator@src/main.rs:22:23: 24:2 {}]>: std::marker::Unpin` is not satisfied in `impl core::future::future::Future`
  --> src/main.rs:12:17
   |
12 |         let s = futures::future::select(a, b);
   |                 ^^^^^^^^^^^^^^^^^^^^^^^ within `impl core::future::future::Future`, the trait `std::marker::Unpin` is not implemented for `std::future::GenFuture<[static generator@src/main.rs:22:23: 24:2 {}]>`
   |
   = help: the following implementations were found:
             <std::future::GenFuture<T> as std::marker::Unpin>
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required by `futures_util::future::select::select`

error[E0277]: the trait bound `std::future::GenFuture<[static generator@src/main.rs:18:23: 20:2 {}]>: std::marker::Unpin` is not satisfied in `impl core::future::future::Future`
  --> src/main.rs:12:17
   |
12 |         let s = futures::future::select(a, b);
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ within `impl core::future::future::Future`, the trait `std::marker::Unpin` is not implemented for `std::future::GenFuture<[static generator@src/main.rs:18:23: 20:2 {}]>`
   |
   = help: the following implementations were found:
             <std::future::GenFuture<T> as std::marker::Unpin>
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required by `futures_util::future::select::Select`

error[E0277]: the trait bound `std::future::GenFuture<[static generator@src/main.rs:22:23: 24:2 {}]>: std::marker::Unpin` is not satisfied in `impl core::future::future::Future`
  --> src/main.rs:12:17
   |
12 |         let s = futures::future::select(a, b);
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ within `impl core::future::future::Future`, the trait `std::marker::Unpin` is not implemented for `std::future::GenFuture<[static generator@src/main.rs:22:23: 24:2 {}]>`
   |
   = help: the following implementations were found:
             <std::future::GenFuture<T> as std::marker::Unpin>
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required by `futures_util::future::select::Select`

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `awaitesting`.
</pre>
</details>

**Comment by cramertj** [comment]
Yes, as the error says, these futures are not `Unpin`, and so cannot b used with `futures::stream::select`.

**Comment by JuanPotato** [comment]
I'm sorry, I'm pretty new to async, could you explain what exactly that means and how I could accomplish something similar?

**Comment by JuanPotato** [comment]
I'm new to async, what exactly is pinning?

**Comment by cramertj** [comment]
https://github.com/rust-lang/async-book/blob/master/src/pinning/chapter.md has an introduction
