### ISSUE TITLE
Unbounded try_for_each_concurrent

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang-nursery/futures-rs#1586]
In https://github.com/rustasync/runtime/pull/24/ we've added `try_for_each_concurrent` to  Runtime's examples in order to spawn items from a stream in parallel.

Something that stood out was that this method requires an upper bound, which effectively makes it bounded. When we want to express we _actually_ want unbounded parallelism we can more or less emulate that by passing a very high number as the upper bound, but this feels like it doesn't quite capture the intent. From [our code](https://github.com/rustasync/runtime/pull/24/files#diff-633608b66cafdfb86435918f3a48bea5R19):

```rust
await!(listener
    .incoming()
    .try_for_each_concurrent(!0, async move |stream| {
        await!(runtime::spawn(async move { /* */ })
    }))
}))?;
```
Using `usize::max_value()` or `!0` is both valid, but for someone unfamiliar with the function it doesn't quite capture the intent of what's going on.

Instead having the upper bound be something akin to `Option<usize>` feels like it would better convey the intended purpose of the parameter.

This design would have precedent in Node's [map-limit](https://www.npmjs.com/package/map-limit) and [async](http://caolan.github.io/async/docs.html#mapLimit) packages where bounded parallelism is expressed by using a number, and unbounded parallelism is expressed by using JS's [`Infinity`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity) value:

```js
var arr = [1, 2, 3, 4, 5]
var iter = (i, cb) => cb(null, i * i)
mapLimit(arr, Infinity, iter, (err, res) => {
    if (err) throw err
    console.log(res)
})
```

Thanks! :sparkles:

**Comment by yoshuawuyts** [comment]
Ah, nevermind. It looks like this already works this way. I got confused by the current rendering of docs.rs, and didn't read the sibling `for_each_concurrent`'s documentation.

**Comment by yoshuawuyts** [comment]
Though as a side note: I guess a neat change would be if the API would be `Option<NonZeroUsize>` to remove the corner case about "what limit does zero mean?".

**Comment by Nemo157** [comment]
One problem with taking `Option<NonZeroUsize>` (or `Into<Option<NonZeroUsize>>`) is that to call it with a constant you'd have to `for_each_concurrent(NonZeroUsize::new(5).unwrap())` (or eventually something like `for_each_concurrent(const { NonZeroUsize::new(5).unwrap() })` to force the checking to compile-time).

If you're not passing a constant then I think on the whole `NonZero` would be good to force you to think about what to do with `0` (e.g. if you are passing in a value from a config file, what happens if someone puts `0` there?).

**Comment by yoshuawuyts** [comment]
@Nemo157 oh wow, no yeah what you're saying makes sense. I didn't realize that writing non-zero literals would end up being clunky :/
