### ISSUE TITLE
Make Sender<T> struct comparable

### ISSUE THREAD

**Issue by LinkTed** [rust-lang-nursery/futures-rs#1588]
I would be great to add the `PartialEq` trait to the `Sender<T>` struct, because I want to remove all `Sender<T>` from a `Vec<Sender<T>>` which point to a specific channel, like:
```rust
fn remove_from_list(list: &mut Vec<Sender<u32>>, other: &Sender<u32>) {
    list.retain(|s| s != other);
}
```
I do not know if the following is correct:
```rust
impl<T> PartialEq for Sender<T> {
    fn eq(&self, other: &Sender<T>) -> bool {
        Arc::eq_ptr(&self.inner, &other.inner)
    }
}
```
Can you please verify the code and add it to the repository. If you want i can make PR.

**Comment by taiki-e** [comment]
Related: https://github.com/crossbeam-rs/crossbeam/issues/319

**Comment by azastrael** [comment]
@LinkTed The `same_receiver` has been added in #1617 to do that.

**Comment by LinkTed** [comment]
Thanks
