### ISSUE TITLE
Possible errornous condition in Mutex

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang-nursery/futures-rs#1594]
This line doesn't look good:

https://github.com/rust-lang-nursery/futures-rs/blob/99e25aae2de546213417598c2b820d2c7f7b3666/futures-util/src/lock/mutex.rs#L42

The match shadows function parameter `waker` with decomposed `waker` from `self`. As far as I know this means that the shadowed `waker` is selected in both references, making it an useless condition (implementation is `a.will_wake(a) == true`).

**Comment by taiki-e** [comment]
Oh, that is a bug, originally they were different variable names...

```diff
-             Waiter::Waiting(waker) if lw.will_wake_nonlocal(waker) => {},
+             Waiter::Waiting(waker) if waker.will_wake(waker) => {},
```
