### ISSUE TITLE
May a future both wake a Waker and return Pool::Ready?

### ISSUE THREAD

**Issue by jimblandy** [rust-lang-nursery/futures-rs#1623]
I can't tell from the documentation whether it is permitted for a polled future to *both*:
- wake the `Waker` from the `Context` passed to `poll`, and
- return `Poll::Ready`.
I think the `Future::poll` documentation ought to be clearer on this question.

I'll be happy to write a pull request once I understand the answer.

**Comment by Matthias247** [comment]
It is **always** possible and allowed to call `Waker::wake()` - even in situations where the task has already finished.

However you *should* not do it the relevant `Future` already gets completed in the same turn. Calling `wake()` in the same moment will cause the executor to call `poll()` on the task again in the case the task didn't already complete. That would be an unnecessary wakeup. Also if no higher level Future already remembers that this particular Future already finished and refrains from polling it again then this will cause an infinite loop of the Future waking up the executor and the executor polling the Future again.

**Comment by Nemo157** [comment]
A future that does so sounds like a good thing to have in `futures-test` as a way to stress-test executors (along with one that spawns a thread to call `wake` after the executor has been dropped, hmm, this is making me wonder how much Juliex has been stressed with logically buggy futures).

**Comment by cramertj** [comment]
Closing-- @Nemo157 if you want to follow up with a futures-test addition, SGTM.

**Comment by jimblandy** [comment]
Yes, closing is fine, sorry. I'll put together a PR for the doc change.
