### ISSUE TITLE
Misleading documentation of `SelectAll`?

### ISSUE THREAD

**Issue by svartalf** [rust-lang-nursery/futures-rs#1626]
Documentation for the [futures::stream::SelectAll](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.16/futures/stream/struct.SelectAll.html) of the `futures = "0.3.0-alpha.16"` says that `SelectAll` "maintain a set of streams and drive them all to completion".

With the following example

```rust
#![feature(async_await)]

use futures::*;

#[runtime::main]
async fn main() {
    let a = stream::iter((0..5));
    let b = stream::iter((10..20));

    let mut s = stream::select_all(vec![a, b]);

    while let Some(res) = s.next().await {
        dbg!(res);
    }
}
```
and used dependencies
```toml
runtime = "0.3.0-alpha.3"
futures-preview = "0.3.0-alpha.16"
```

`SelectAll` stops when the first inner stream exhausts:

```
[src/main.rs:13] res = 0
[src/main.rs:13] res = 10
[src/main.rs:13] res = 1
[src/main.rs:13] res = 11
[src/main.rs:13] res = 2
[src/main.rs:13] res = 12
[src/main.rs:13] res = 3
[src/main.rs:13] res = 13
[src/main.rs:13] res = 4
[src/main.rs:13] res = 14
```

Based on the documentation I was expecting it to continue driving stream `b` to completion, but it does not.
It seems that either documentation is wrong or `SelectAll` implementation is broken, I'm not sure which case is it.

UPD: `futures::stream::select` fn exhausts both streams and from my point of view the same behavior can be expected from the `select_all` fn.

**Comment by taiki-e** [comment]
I feel this is a bug. I'll fix this (if this is the intended behavior, I will propose to change it).

**Comment by cramertj** [comment]
yup, I'd definitely consider this a bug.
