### ISSUE TITLE
use of unstable library feature 'futures_api': futures in libcore are unstable

### ISSUE THREAD

**Issue by Iokdo** [rust-lang-nursery/futures-rs#1635]
use of unstable library feature 'futures_api': futures in libcore are unstable

**Comment by Nemo157** [comment]
@Iokdo what is the output of `rustc --version`? The minimum required versions for the current `futures-preview` crates are `rustc 1.36.0-beta.1 (3a5d62bd5 2019-05-22)` or `rustc 1.36.0-nightly (3f5152e20 2019-05-08)`, there are no stable releases that support it currently.
