### ISSUE TITLE
Keep Sink::Item an associated type

### ISSUE THREAD

**Issue by hewenyang** [rust-lang-nursery/futures-rs#1638]
I've just started learning Rust and futures recently, and one of the things that confuses me is why `Sink`'s `item` is a generic parameter while `Stream`'s `Output` is an associated type.

This means that `Sink` is able to accept multiple different types of items while Stream can only output one type of item. I have read the arguments in #623, and a use case is to "multiplex" multiple types of items into one stream. However, given the current sink API, I feel the current design is not quite ergonomic.

The `Sink` trait consists of four methods, three of which control things like back-pressure and when the stream closes. Conceptually, a sink should represent the sending side of a single stream, rather than a stream for each type that the sink accepts, so all the three methods should not depend on the exact type parameter. But since the Item is included in the type parameter, a different `poll_ready`, `poll_flush` and `poll_close` is implemented for each type that the sink accepts.

Such a design also prevents sending in a single type for different purposes. For example, a logging sink might accept `String`, but it's not possible for the sink to distinguish two different types of Strings, such as `Info` and `Error`.

For multiplexing purposes it should be a better idea to use enums, since they express the idea of multiplexing better. It is a bit ugly to map all types into their corresponding enum values at the sender side, so a mechanism for implicit conversion is still preferred, but it might be better to leave it outside the `Sink` trait. For example, an object might implement `IntoSink<T>` so it can be implicitly converted into a `Sink<Item = T>`, and the conversion from T to the enum type can happen automatically. Or it can implement `Into` trait for the sink item type. Maybe a separate trait `SinkOf<T>` that allows a sink to define "secondary" types, etc.

**Comment by cramertj** [comment]
`Sink::Item` cannot be an associated type while allowing `Sink`s to accept slices or other values with lifetime parameters, as they would not be able to accept references with multiple different lifetimes.
