### ISSUE TITLE
Consider flatten_stream_sink method

### ISSUE THREAD

**Issue by DenisKolodin** [rust-lang-nursery/futures-rs#1650]
How about to add `flatten_stream_sink` method that allows to extract a `Stream + Sink` instance from `Future`?

Related: https://github.com/rust-lang-nursery/futures-rs/pull/965

**Comment by cramertj** [comment]
I actually think this is just a matter of adding a `Stream` impl to the existing `FlattenSink` combinator, and I would be happy to accept a PR!
