### ISSUE TITLE
Some doc tests fail with ICE

### ISSUE THREAD

**Issue by taiki-e** [rust-lang-nursery/futures-rs#1657]
https://github.com/rust-lang-nursery/futures-rs/pull/1656#issuecomment-499387762

**Comment by taiki-e** [comment]
I think it is good to temporarily ignore these tests and restore them after rust-lang/rust#61442 lands.

**Comment by Nemo157** [comment]
Tests [passed on `rustc 1.37.0-nightly (5d8f59f4b 2019-06-04)`](https://travis-ci.com/rust-lang-nursery/futures-rs/jobs/205557740) and [failed on `rustc 1.37.0-nightly (7cdaffd79 2019-06-05)`](https://travis-ci.com/rust-lang-nursery/futures-rs/jobs/205893897), that's means they worked after the version where https://github.com/rust-lang/rust/issues/61442 failed so likely a different issue (also, 61442 seems to be related to the `Assign*` operators and blocks, whereas at a guess from looking at the error message + failing tests this is somehow related to changes in implicit-drop/StorageDead handling in generators).

**Comment by Nemo157** [comment]
[Minimal repro](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=970fe3fd61ac93849703b5ab3efa8c59). I'll open a new rust-lang/rust ticket about it.
