### ISSUE TITLE
Futures aware mutex doesn't switch while awaiting

### ISSUE THREAD

**Issue by StevenDoesStuffs** [rust-lang-nursery/futures-rs#1663]
Not sure if this is even possible to fix, but currently, the mutex in the futures crate doesn't let other tasks access data while one future has it locked and is awaiting some other task.

Take a look at this code:
```rust
lazy_static!{
    pub static ref MUTEX: Mutex<u32> = Mutex::new(0);
}
fn main() -> Result<()> {
    let mut pool = ThreadPool::new()?;
    let a = test1();
    let b = test2();
    pool.run(join(a, b).map(|_|()));

    Ok(())
}

async fn test2() {
    println!("{}", 3);
    let a = MUTEX.lock().await;
    println!("{}", *a);
}

async fn test1() {
    let mut a = MUTEX.lock().await;
    Delay::new(time::Duration::from_secs(2)).compat().await.unwrap();
    println!("{}", *a);
    *a += 1;
}
```
Here, test1 locks the mutex, does something for 2 seconds, and then prints then increments the mutex, and test2 simply prints 3, locks the mutex, and then prints whatevers in the mutex.
We run test1 and test2 simultaneously.

The output is 
```
3
0
1
```
with a 2 second gap between 3 and 0.
This implies that the mutex isn't allowing test2 to access the data while test1 is awaiting the delay.

Is this intended behavior? Is it even possible to implement the mutex to behave differently? In this case, it's definitely safe to give test2 access to the data in the mutex while test1 is awaiting the delay and only wake test1 again after both the mutex is unlocked and the delay is over, but there is a case where the delay task actually takes the data inside the mutex. In that case, would it still be safe?
This behavior makes the mutex a lot less useful (or at least more difficult to use correctly) as it's totally plausible that a developer might lock some program state, make an http request, and then modify the program state based on the response. While the HTTP request is happening, nothing else can access the program state.

**Comment by seanmonstar** [comment]
To me, this is working as expected. In blocking code, if you take a lock and then do something blocking, like read a file, the lock is held as well.

If you were to borrow something protected by the lock, and the lock were released while you were awaiting, the borrow could be invalidated by another task.

**Comment by StevenDoesStuffs** [comment]
Wdym the borrow could be invalidated by another task? Do you mean something like this: 
```rust
async fn test2() {
    let mut a = MUTEX.lock().await;
    println!("{:?}", a);
    *a = None;
}

async fn test1() {
    let mut a = MUTEX.lock().await;
    if let Some(ref n) = *a {
        Delay::new(time::Duration::from_secs(2)).compat().await.unwrap();
        println!("{:?}", n);
    }
}
```
Here, if the mutex allows test2 to access the data while test1 is awaiting the delay, n will be invalid, and the code will error.
It does seem like this isn't a solvable issue. At the very least I would hope that when this is stabilized, this is very very well documented (as in screaming in your face type documented) to prevent less experienced rust devs (like me) from making mistakes like in the HTTP request example. 
Thanks for your time.
