### ISSUE TITLE
Wrong git tag for v0.1.27

### ISSUE THREAD

**Issue by win-t** [rust-lang-nursery/futures-rs#1670]
Hi, I just want to mention that tag `0.1.27` is the same as `0.3.0-alpha.16` (they are both 99e25aae)
I think it should be 5654784d

**Comment by dekellum** [comment]
I can confirm, contents of the crate tarball match 5654784, which is nominally reassuring.

**Comment by cramertj** [comment]
Should be fixed now, thanks for the report!
