### ISSUE TITLE
future::empty and stream::empty behave differently

### ISSUE THREAD

**Issue by Marwes** [rust-lang-nursery/futures-rs#1684]
[future::empty](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.16/futures/future/fn.empty.html) creates a future that never resolves (returns `Pending`) while [stream::empty](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.16/futures/stream/fn.empty.html) creates a stream which resolves to `None`. While `empty` makes sense in isolation for these, given that `future::empty` never resolves I would expect `stream::empty` to do the same.

I propose that `future::empty` is renamed to `future::never` (or `future::pending` maybe if `never` is to close to the never-type `!`?) and that `stream::never` is added to be a stream that always returns `Pending`. `stream::empty` can remain with the current behaviour since it makes sense to return `None` as it does currently.

**Comment by cramertj** [comment]
sounds good to me! thanks for pointing this out!

**Comment by Nemo157** [comment]
Fixed by #1689
