### ISSUE TITLE
Consider adding `size_hint` to `Stream`

### ISSUE THREAD

**Issue by carllerche** [rust-lang-nursery/futures-rs#170]
This would be helpful for `Stream::collect`

Also, I often create empty streams to represent no body when working w/ HTTP, it would be nice to just skip all the work if the body is empty.

**Comment by alexcrichton** [comment]
I can see how `Stream::collect` could use this to prevent excessive allocations, but I'm not quite sure how that connects to the bodies you mentioned next?

I feel like this is a great optimization opportunity for iterators, but not necessarily streams. Would be good to have some examples in practice that this helps to evaluate as well!

**Comment by carllerche** [comment]
For example, if I know that the HTTP body is empty (size hint would be 0), then I could terminate the HTTP/2 stream right after the head and not need to write an empty body stream frame.

**Comment by khuey** [comment]
I also think this would be useful. I've written a bunch of code of the form

1. Start with a data structure
2. For each element in that data structure, do something asynchronously. The actual asynchronous operation here is usually performing an HTTP request and get the response. Generally the iterator is fed to `futures_ordered` or `futures_unordered` depending on whether the initial data structure was a vector or a hash table.
3. Collect all the results back into a data structure

**Comment by taiki-e** [comment]
We cannot optimize current `StreamExt::collect` with this, but it would be probably useful for some use cases.
