### ISSUE TITLE
Release 0.3.0-alpha.17?

### ISSUE THREAD

**Issue by taiki-e** [rust-lang-nursery/futures-rs#1703]
It has been almost two months since the previous version was released. We have many unreleased new features and changes (see: #1702).

cc @cramertj @Nemo157 @seanmonstar

**Comment by cramertj** [comment]
Sounds good! I'll publish one tomorrow.

**Comment by taiki-e** [comment]
@cramertj Thanks for publishing 0.3.0-alpha.17.
