### ISSUE TITLE
compat into_inner methods

### ISSUE THREAD

**Issue by VictorKoenders** [rust-lang-nursery/futures-rs#1704]
I'm running into an issue where I'm wrapping a tokio `TcpStream`'s `WriteHalf` in a `Compat01As03Sink` and a `ReadHalf` in a `Compat01As03`. Later in the function I want to upgrade this `TcpStream` to a `TlsStream`. For this, I want to use tokio's `SplitStream::reunite`. However, because the sink and stream are wrapped in the compat layer, I cannot get an instance back of the original sink and stream. Is there a reason against implementing an `into_inner()` method for the `Compat01As03[Sink]` structs?

**Comment by Nemo157** [comment]
No reason not to, they should all have the `into_inner`, `get_ref` and`get_mut` trio.
