### ISSUE TITLE
Provide a read_to_string method on AsyncReadExt for Read parity

### ISSUE THREAD

**Issue by sagebind** [rust-lang-nursery/futures-rs#1715]
It would be really handy to provide a `read_to_string()` method on `AsyncReadExt` similar to the one provided by `Read` instead of implementing this myself in my own crates.

**Comment by yoshuawuyts** [comment]
Reference: [`std::io::Read::read_to_string`](https://doc.rust-lang.org/std/io/trait.Read.html#method.read_to_string)

**Comment by taiki-e** [comment]
(By the way, the current `AsyncReadExt::read_to_end`, unlike `std::io::Read::{read_to_end, read_to_string}`, does not return the total number of bytes read.)
