### ISSUE TITLE
futures-select-macro-preview failes to compile

### ISSUE THREAD

**Issue by Mossop** [rust-lang-nursery/futures-rs#1728]
I tried to use futures-preview in a new project so I added `futures-preview = { version = "=0.3.0-alpha.17", features = ["compat", "async-await", "nightly"] }` to the dependencies. Running `cargo check` with nightly now fails with:

```
error[E0433]: failed to resolve: maybe a missing `extern crate token;`?
  --> /Users/dave/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-select-macro-preview-0.3.0-alpha.17/src/lib.rs:67:34
   |
67 |             } else if input.peek(Token![default]) {
   |                                  ^^^^^^^^^^^^^^^ maybe a missing `extern crate token;`?
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

Looks like it is missing `extern crate syn` but maybe something is wrong with my setup?

**Comment by taiki-e** [comment]
See https://github.com/rust-lang/rust/issues/62562.
This has been fixed in the latest nightly.

**Comment by Mossop** [comment]
Oops, so it has!
