### ISSUE TITLE
Is TryChain::is_terminated correct?

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang-nursery/futures-rs#1740]
Looking at https://github.com/rust-lang-nursery/futures-rs/blob/af434e1d495264dfd7f8b5094b69fbba490d423e/futures-util/src/try_future/try_chain.rs#L28-L33

Shouldn't those flipped? The `FusedFuture` docs say "Returns `true` if the underlying future should no longer be polled." Isn't the `Empty` state the completed state?

**Comment by taiki-e** [comment]
Seems current implementation is incorrect.
