### ISSUE TITLE
`mpsc::Sender::send` no longer returns the value to the caller on a failed send

### ISSUE THREAD

**Issue by canndrew** [rust-lang-nursery/futures-rs#1745]
With the standard library's `mpsc::Sender` and with the futures-0.1 `mpsc::Sender` you can try to send a value then get the value back if the receiver has hung up. futures-0.3 `mpsc::Sender` instead gives you back a `SendError` from which you can't extract the value you tried to send. There is a `try_send` method, but this is non-futures-aware and so useless to me.

Can we get this functionality back? Ownership and linearity are important in Rust. Values shouldn't just disappear into the void unless I want them to.

**Comment by taiki-e** [comment]
This is because `SendError` is also used for return values such as `poll_ready`, but I think we can change `SendError` to contain an `Option<value>`.

**Comment by seanmonstar** [comment]
The purpose of `try_send` is exactly this, that's why it has the `try_` prefix. Neither `try_send` nor `start_send` take a task context, so they're both equally "unaware" of futures. The task stuff is used in the poll methods.
