### ISSUE TITLE
Should BoxFuture/BoxStream require Sync?

### ISSUE THREAD

**Issue by Nemo157** [rust-lang-nursery/futures-rs#1752]
I was just looking at testing integrating some code with Hyper's master branch. The first problem I came across was that the existing code uses `BoxStream` to represent its body type, which cannot be converted into `hyper::Body` because it additionally wants `Sync` on the trait object:

```rust
pub fn wrap_stream<S>(stream: S) -> Body
where
    S: TryStream + Send + Sync + 'static,
    S::Error: Into<Box<dyn StdError + Send + Sync>>,
    Chunk: From<S::Ok>, 
```

I don't see why `Sync` would be necessary, since I see no usecases where the type is accessed concurrently from different threads, but it seems to be pretty common to require both markers for trait objects (e.g. there is `Into<Box<dyn Error + Send + Sync>>` but not `Into<Box<dyn Error + Send>>` which I have run into, and seen others run into, multiple times).

I can't think of any `Send + !Sync` type right now, and it seems like a niche usecase if they do exist.

cc @seanmonstar

**Comment by 12101111** [comment]
`hyper` require `Sync` on this method since https://github.com/hyperium/hyper/commit/4441372121e8b278ac773ddd4e408a642dadf2d8
Because https://github.com/rust-lang/rust/issues/57017
Maybe it’s a bug in rustc

**Comment by Nemo157** [comment]
More specifically the bug that Hyper is running into appears to be https://github.com/rust-lang/rust/issues/59245 (_via_ https://github.com/rust-lang/rust/issues/57017 causing the `match` patterns to create unnecessary references, but it would still be possible to hit \#59245 without \#57017).

It seems to me that it's definitely a bug in the generator transform, if the reference is internal then there's no need for the referenced value to be `Sync`.

Either way, is there a downside to adding `+ Sync` here? Skimming the docs I notice that `Cell`, `RefCell` and `mpsc::{Receiver, Sender}` appear to be the only types that are `Send + !Sync`.

**Comment by cramertj** [comment]
We now have `LocalBoxFuture` and `LocalBoxStream` which I believe resolve this issue. Let me know if there is more wanted here!
