### ISSUE TITLE
stream::unfold

### ISSUE THREAD

**Issue by jplatte** [rust-lang-nursery/futures-rs#1756]
futures 0.3 has the same [documentation for `unfold`](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.17/futures/stream/fn.unfold.html) that futures 0.1 had, however, it seems to me that the following *can't* be true anymore: 

> In case of error generated by the returned `Future`, the error will be returned by the `Stream`. The `Stream` will then yield `Poll::Ready(None)` in future calls to `poll()`.

because `Future`s no longer have errors built-in. For my use case, where the stream is endless unless an error occurs, this new version of `unfold` is not very helpful. I now need to do additional state tracking in my own code to be able to first yield `Some(Err(...))` and then `None` from the stream.

Is `unfold` intended to be kept as-is? Would you be open to a PR that adds a similar function (`try_unfold`?) for `TryStream`s?

**Comment by jplatte** [comment]
@cramertj so you fixed the docs, but what about my question regarding how to replicate the old behavior? Should I open a new issue for that?

**Comment by cramertj** [comment]
You can replicate it by returning and error and then returning `None` manually, but that's a decent bit of extra work. Feel free to open an issue for `try_unfold`!
