### ISSUE TITLE
Remove mentioning of default spawners from docs

### ISSUE THREAD

**Issue by SrTobi** [rust-lang-nursery/futures-rs#1757]
The docs mention `default spawners` multiple times in the `LocalPool`/`ThreadPool` docs (see below)  but from what I understand they do not exist anymore as no spawner is passed along the poll chain (see c5e5fd5f3f17b47057f619cdddd8f0cb7a84f70f) anymore.

It is very confusing to read something about default spawner when they don't exists.

https://github.com/rust-lang-nursery/futures-rs/blob/a705910a8d844f6d56527ab9d774be09eb3008d5/futures-executor/src/local_pool.rs#L106
https://github.com/rust-lang-nursery/futures-rs/blob/a705910a8d844f6d56527ab9d774be09eb3008d5/futures-executor/src/local_pool.rs#L129
https://github.com/rust-lang-nursery/futures-rs/blob/a705910a8d844f6d56527ab9d774be09eb3008d5/futures-executor/src/local_pool.rs#L140

https://github.com/rust-lang-nursery/futures-rs/blob/a705910a8d844f6d56527ab9d774be09eb3008d5/futures-executor/src/thread_pool.rs#L86

https://github.com/rust-lang-nursery/futures-rs/blob/a705910a8d844f6d56527ab9d774be09eb3008d5/futures-executor/src/thread_pool.rs#L91

**Comment by SrTobi** [comment]
I would have made a PR but I think it's wiser to decide on #1758 first.

**Comment by cramertj** [comment]
I think both this and #1758 are correct and I would like to include them in the 0.3 release.

**Comment by SrTobi** [comment]
Does that mean you want me to do the pr or will you do it yourself?

**Comment by cramertj** [comment]
I'll land one today.
