### ISSUE TITLE
Remove ThreadPool::run

### ISSUE THREAD

**Issue by SrTobi** [rust-lang-nursery/futures-rs#1758]
The method `ThreadPool::run` is a synonym for `LocalPool::new().run_until(f)`. Even though the docs state that the thread pool is used as default spawner, the concept of a default spawner does not exist anymore (see #1757) and so this method does not interact with the thread pool in any meaningful way.

It should be removed because it does not bring any additional value, but, even worse, adds confusion by suggesting that it interacts with the thread pool, which it does not.

https://github.com/rust-lang-nursery/futures-rs/blob/a705910a8d844f6d56527ab9d774be09eb3008d5/futures-executor/src/thread_pool.rs#L95

**Comment by realcr** [comment]
Hey, during porting of my futures code to stable Rust I stumbled upon this change.
First, please let me congratulate you for getting all the async stuff on stable!

Most of the tests in my codebase look like this:

```rust
     #[test]
     fn test_dummy_timer_multi_sender() {
         let mut thread_pool = ThreadPool::new().unwrap();
         thread_pool.run(task_dummy_timer_multi_sender(thread_pool.clone()));
     }
```

By the above, I understand that I should port the test to be:

```rust
     #[test]
     fn test_dummy_timer_multi_sender() {
         let thread_pool = ThreadPool::new().unwrap();
         LocalPool::new().run_until(task_dummy_timer_multi_sender(thread_pool.clone()));
     }
```

Is this the right way to go? The tests seem to pass so far, but the new code looks somewhat strange. The reader sees two pools. What is the relation between those two pools? 
My opinion is that this new form is a bit more confusing than the previous one.

I thought to try using only `LocalPool`, but I can't do it, as in the example above the function `task_dummy_timer_multi_sender` requires that the spawner implements `Send`, which is not true in the case of `local_pool.spawner()`.

**Comment by SrTobi** [comment]
You can use [block_on](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.19/futures/executor/fn.block_on.html). That would have the same effect but is a little shorter.

> The reader sees two pools. What is the relation between those two pools?
Yes there are two pools in your case. Both are basically a list of task that haven't been completed yet.

The threadpool also creates a number of worker threads that immediately and simultaneously start to work on these task to complete them.

The local pool does not start immediately, but only when you call `run_until` or one of the other similar functions and works on that list of tasks but only one at a time, because it uses only the thread that called `run_until`.

In your tests, you create a local pool, and put one task into the pool and then work on that task until it is finished (the one returned by `task_dummy_timer_multi_sender`). The local pool could also work on other tasks but for that you would have to submit more tasks :wink:

I assume however, that the `task_dummy_timer_multi_sender` task will submit more tasks to the threadpool!? These tasks will then be executed by the threadpool parallel to each other and also parallel to the original task in the local pool.

`ThreadPool::run` was removed because it appeared to interact with the threadpool in some way but it just didn't. It just created a new local pool, submitted the task and waited until the task was done. Nothing regarding the ThreadPool was happening there. For this, however, there is [block_on](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.19/futures/executor/fn.block_on.html), which not only explains better what it does, but also it does not have the overhead of creating an additional pool.

**Comment by realcr** [comment]
Thanks for the detailed explanation! 
I think that I will further simplify my test code with `block_on`.
