### ISSUE TITLE
Remove AsyncRead::initializer

### ISSUE THREAD

**Issue by Nemo157** [rust-lang-nursery/futures-rs#1761]
The [tracking issue](https://github.com/rust-lang/rust/issues/42788) for `std::io::Read::initializer` makes it sound like that API is definitely going to be changed a lot, it would be good to remove the similar API here until the `std` API is closer to its final form.

**Comment by cramertj** [comment]
Yeah, it seems like there's some push towards having `freeze()` instead. cc @seanmonstar @ralfjung

**Comment by RalfJung** [comment]
There was a push at https://github.com/rust-lang/rust/pull/58363, but there are two issues with this:
* Having `freeze` with the desired semantics basically means that a program can observe uninitialized memory without causing UB. See https://www.reddit.com/r/rust/comments/apreqi/ucgmiri_allhands_2019_recap/egarzl8/ for some links.
* `freeze` cannot actually be a NOP; [uninitialized memory can actually be unstable](https://github.com/rust-lang/rust/pull/58363#issuecomment-512119241).

Note however that the current `initializer` API is incompatible with https://github.com/rust-lang/unsafe-code-guidelines/issues/77, at least if https://github.com/rust-lang/unsafe-code-guidelines/issues/71 ends up deciding that integers must be initialized to be valid.

**Comment by seanmonstar** [comment]
It seems to me like we're at an awkward point with regards to the desired functionality here.

- *If it's decided that `&mut [u8]` to uninitialized memory is UB*, then we need to add methods like `unsafe fn read_uninit(&mut self, buf: &mut MaybeUninit<[u8]>)`.
- *However, if it is decided to NOT be UB*, then we don't need those methods, and don't need to suffer the churn.

**Comment by Nemo157** [comment]
Whether or not an `&mut [u8]` pointing to uninitialized memory is UB, there was [earlier discussion in the tracking issue](https://github.com/rust-lang/rust/issues/42788#issuecomment-325837435) about how the ceremony in the current API doesn't provide much utility and it could be replaced with a simpler API. It would be disappointing if `AsyncRead` ended up with a different, more complicated API than `Read`.

**Comment by taiki-e** [comment]
I think we should choose one of the following:
* Replace with a simpler API like https://github.com/rust-lang/rust/issues/42788#issuecomment-325837435
* Make `AsyncRead::initializer` unstable API - this will be near to what std is doing.
* Do both of the above.

**Comment by cramertj** [comment]
+1 for making it unstable. The "simpler API" is unsound, though, so I don't want to do that.

**Comment by carllerche** [comment]
@cramertj what is unsound about it?

**Comment by cramertj** [comment]
`unsafe fn may_read_buffer(&self) -> bool { true }` is incorrect because it is `unsafe` to implement, not unsafe to call. The only way today to make something unsafe to implement is via a separate `unsafe` trait, or something which is forced to call an `unsafe` function, at which point you wind up back at the current initializer API.

**Comment by carllerche** [comment]
@cramertj makes sense, thanks for the explanation. Is the intent to document the unsafe requirements you describe as part of https://github.com/rust-lang/unsafe-code-guidelines or some other location?

**Comment by cramertj** [comment]
The requirement that `unsafe fn` in traits is only unsafe to call, not unsafe to implement? I'm not aware of an existing UCG proposal for that, but I'd certainly be interested in one, yes.

**Comment by RalfJung** [comment]
That seems more like Reference material than UCG. There's no open questions, just things are a bit surprising (https://github.com/rust-lang/rfcs/pull/2585 would improve things IMO by making the role of `unsafe fn` clearer).
