### ISSUE TITLE
Will AsyncRead and AsyncWrite be standardized before async trait methods?

### ISSUE THREAD

**Issue by lachlansneff** [rust-lang-nursery/futures-rs#1762]
Async trait methods depend on generic associated types (GATs), which seem quite far away given their little visible progress. If traits like `Stream`, `Sink`, `AsyncRead`, and `AsyncWrite` were able to use GATs or async trait methods, then they could use Futures as their async primitive.

We could have:

```rust
pub trait AsyncRead {
    async fn read(&mut self, buf: &mut [u8]) -> io::Result<usize>;
}
```

which mirrors the blocking trait `Read` quite well,

instead of the current definition:

```rust
pub trait AsyncRead {
    fn poll_read(
        self: Pin<&mut Self>, 
        cx: &mut Context, 
        buf: &mut [u8]
    ) -> Poll<Result<usize, Error>>;
}
```

**Comment by Nemo157** [comment]
@lachlansneff see https://github.com/rust-lang-nursery/futures-rs/issues/1365 for previous discussion on this, TL;DR there are more issues than just getting async fn in traits (and even that is likely still a _long_ way away, need finished chalk integration before the GATs implementation can be started, then an RFC for impl-trait-in-traits, _then_ an RFC for async-fn-in-traits).

**Comment by seanmonstar** [comment]
> an RFC for impl-trait-in-traits

It looks like that's been approved! 🎉 

----

As noted, there's a lot more discussion in #1365, so I'm going to close this one as a duplicate.
