### ISSUE TITLE
Change future::select_all contract to block instead of panicking

### ISSUE THREAD

**Issue by udoprog** [rust-lang-nursery/futures-rs#1765]
The current contract of `future::select_all` states:

> This function will panic if the iterator specified contains no items.

I've had to work around this a handful of times, typically by doing something that makes sure that the list of futures is populated, like:

```rust
let mut futures = Vec::new();

loop {
    while futures.is_empty() {
        futures.push(rx.select_next_some().await);
    }

    while !futures.is_empty() {
        let either = future::select(rx.select_next_some(), future::select_all(&mut futures)).await;

        match either {
            future::Either::Left((future, _)) => {
                futures.push(future);
            }
            future::Either::Right(((_, index, _), _)) => {
                let _ = futures.swap_remove(index);
            }
        }
    }
}
```

We could arbitrarily decide to change this contract so that `future::select_all` blocks indefinitely in case there are no futures to select over. This would match all the uses I've had for`future::select_all` so far.

**Comment by matklad** [comment]
I argue that the same should be done for [`FuturesUnordered`](https://github.com/rust-lang-nursery/futures-rs/blob/5c2f3d90232c665c95ccce1d1d2622332e89f1c7/futures-util/src/stream/futures_unordered/mod.rs) as well. It currently returns immediately, which is not what you want if you want to put `FuturesUnorderd` itself into select.

Also cc https://bugs.python.org/issue25680: Python is also confused about what to do when selecting on an empty set of events :D

**Comment by matklad** [comment]
Also, *why* do both `SelectAll` and `FuturesUnordered` exist? `SeectAll` is inherently linear (just like `select` syscall), seems like one should always prefer `FuturesUnordered` instead?

**Comment by udoprog** [comment]
> Also, why do both SelectAll and FuturesUnordered exist?

I've since switched to using `FuturesUnordered`. And I agree, I'm not sure what niche `SelectAll` fills to warrant its inclusion.

**Comment by taiki-e** [comment]
> I argue that the same should be done for [`FuturesUnordered`](https://github.com/rust-lang-nursery/futures-rs/blob/5c2f3d90232c665c95ccce1d1d2622332e89f1c7/futures-util/src/stream/futures_unordered/mod.rs) as well. It currently returns immediately, which is not what you want if you want to put `FuturesUnorderd` itself into select.

#1009?

**Comment by udoprog** [comment]
There hasn't been any points raised against making this change so far. Would you be OK with a PR?

**Comment by udoprog** [comment]
Looking close at `FuturesUnordered` there's a bit of a problem.

Since `FuturesUnordered` implements `Stream`, users assume that it returns the sentinel value `None` when it is empty. It obviously can't return both `Poll::Pending` _and_ `Poll::Ready(None)`.

This causes issues with things like `block_on_stream`. The created iterator will never end.

Conceptually it would make more sense to me if there was a concept of "infinite streams", which doesn't yield `Option<T>` values. And who's termination status through `FusedStream` depends on if it beforehand knows it will block or not. Something like:

```rust
trait Stream {
    type Item;

    fn poll_next(
        self: Pin<&mut Self>,
        cx: &mut Context<'_>,
    ) -> Poll<Self::Item>;
}
```
Maybe even consider making the existing `Stream` not resolve with an `Option` value, and terminating streams are specializations on this. Similarly to how `Result<T, E>` was removed from `Future`. I've certainly had needs for this in the past with things like `Interval`. It's never correct to treat these as things that will end.

**Comment by cramertj** [comment]
I believe that it should be considered a bug to call `future::select_all` with a nonzero number of items, so panicking in this case (rather than silently blocking the event loop) is the behavior I think is right.

**Comment by udoprog** [comment]
@cramertj It seems like you stated the status quo without addressing prior comments. Would you mind motivating a bit?

**Comment by cramertj** [comment]
I'm not sure what further motivation I can provide, sorry. I find bugs blocking the event loop silently much more difficult to debug than bugs which cause panics, so I prefer to panic in this case.

**Comment by udoprog** [comment]
All right. I'll try to summarize:

So roughly, the position is that too make use of this API _without_ panicking, you tend to have to introduce the blocking behavior anyways (see example in bug report). `FuturesUnordered` and `select_all` are frequently used to drive a dynamic collection of work (see e.g. #1009) which needs to be populated. The current contract can be considered extra work to accomplish this*.

*: since we need to feed the collection of futures anyways, we tend to introduce block-on-empty behavior anyways, but with extra steps. If we don't, we instead have a bug where our application panics (which is how I found this).

I probably disagree on the hazard of blocking over panicking, but I appreciate that troubleshooting something that blocks indefinitely can also be a pain. tokio-tracing has been especially helpful for this in the past for me.

**Comment by kangalio** [comment]
> I'm not sure what further motivation I can provide, sorry. I find bugs blocking the event loop silently much more difficult to debug than bugs which cause panics, so I prefer to panic in this case.

Am I missing something? Async cancellation exists. The event loop isn't blocked when a future doesn't yield. Non-yielding futures are totally normal, e.g. for usage in `tokio::select`.

`futures::select_all()` makes itself more annoying to deal with by forbidding the empty case. In my code, I worked around its assert:

```rust
async fn select_all<T>(
    futures: impl IntoIterator<Item = impl std::future::Future<Output = T>>,
) -> T {
    let futures = futures.into_iter().collect::<Vec<_>>();
    // Workaround against select_all's arbitrary assert
    if futures.is_empty() {
        return std::future::pending().await;
    }
    futures::future::select_all(futures.into_iter().map(Box::pin)).await.0
}
```

But it feels ridiculous. `Iterator::all` or `Iterator::any` don't panic either if it's empty, it behaves in a way that's consistent with all its other possible behaviors, making `Iterator::all` and `Iterator::any` pleasant functions to use.
