### ISSUE TITLE
CopyBufInto should attempt to write whenever the buffer is !empty

### ISSUE THREAD

**Issue by talchas** [rust-lang-nursery/futures-rs#1771]
`CopyBufInto::poll` will exit immediately if `poll_fill_buf` returns Pending, when it should instead also attempt to write the buffer if it exists and only return Pending if the buffer is empty or both return Pending.

**Comment by Nemo157** [comment]
I can take a look at fixing this tomorrow.

**Comment by Nemo157** [comment]
The current implementation appears correct to me. `AsyncBufRead::poll_fill_buf` must only return `Pending` if the buffer is empty, it should attempt to pull more data into the buffer if it is available, but even if it doesn't it should return `Ready` with the same data as was available the last time.

**Comment by talchas** [comment]
Good point, I misread the docs of poll_fill_buf, and checking on the source says you're correct.
