### ISSUE TITLE
Release `0.3.0-alpha.18`

### ISSUE THREAD

**Issue by LucioFranco** [rust-lang-nursery/futures-rs#1786]
The last release was about a month ago and we've gotten a bunch of improvements to this crate like `join!` and `try_join!` being implemented as proc macros etc. I think its about time we think about releasing alpha 18. 

cc @cramertj @Nemo157 @taiki-e

**Comment by cramertj** [comment]
Sure, I can do a release tomorrow.

**Comment by cramertj** [comment]
This is done.
