### ISSUE TITLE
Design: Replace IntoAsyncRead with blanket impls of AsyncRead/AsyncWrite

### ISSUE THREAD

**Issue by najamelan** [rust-lang-nursery/futures-rs#1793]
I find myself wanting in now 3 distinct crates to provide AsyncRead/AsyncWrite for a type that is basically a Stream/Sink over `Vec<u8>` or `&[u8]`. I know about `IntoAsyncRead` and think oh, that would be handy, to eventually not use it. 

The reason is that it will require to user of my crate to call `into_async_read` and if they want to store the type, they need to store `IntoAsyncRead<MyStreamType>`. That's a little unconvenient and doesn't feel as nice as having my type just provides the traits, so I find myself copying the algorithm from `IntoAsyncRead` into my crates. It doesn't feel right that we can't reuse this algorithm without multiplicating it...

A bigger problem is that the `IntoAsyncRead` type does not implement other traits that the original stream implemented and takes it's inner stream by value, reducing the functionality strictly to `AsyncRead`. I filed a PR to at least preserve `AsyncWrite` impl from the inner stream, but it's no solution for other traits or type specific methods. 

So I'm thinking, if we would just provide blanket impls for AsyncRead/AsyncWrite, the design would be a lot more elegant. 

One problem of blanket impls is that downstream can no longer roll their own impl because it will be conflicting with the blanket one. I think we can solve this by making the blanket impl opt in. Eg. if we make `IntoAsyncRead` a dummy trait with no required methods, we can make our blanket impl conditional on types that implement `IntoAsyncRead`.

A further improvement: right now the `into_async_read` combinator only exists on `TryStream`, but I see no reason there can not be an `AsyncRead` impl for an infallible stream. It just never returns an error. We can also do the same thing for other traits, I'm mainly thinking of `AsyncWrite`, but there might be other candidates.

I know we are nearing stabilization of async_await, and this is a breaking change, so if there is consensus here I could try to PR this.

What do you all think?

**Comment by cramertj** [comment]
>  I see no reason there can not be an AsyncRead impl for an infallible stream. 

This isn't possible-- there's nowhere to store a previously yielded item that has not been entirely read yet. The same issue exists for `Vec<u8>`-- there's nowhere in that type to store the read progress. `io::Cursor<Vec<u8>>` would address this, but that is covered under the existing `io::AllowStdio` combinator since it implements `std::io::Read`.

**Comment by najamelan** [comment]
oops, you are right, it must be a type to be able to store that item. Sorry for the confusion.

**Comment by cramertj** [comment]
No worries!
