### ISSUE TITLE
Does `try_send` for `mpsc::Sender` need to require `&mut self`?

### ISSUE THREAD

**Issue by jhpratt** [rust-lang-nursery/futures-rs#1796]
Looking at [the details of how it's implemented](https://github.com/rust-lang-nursery/futures-rs/blob/66c879e3f73dcff91b62771d92e7ccc8e31a53e1/futures-channel/src/mpsc/mod.rs#L601-L612), shouldn't interior mutability suffice?

**Comment by cramertj** [comment]
No, this isn't possible-- it calls `SenderInner::try_send` which calls functions that mutate the `maybe_parked` field.
