### ISSUE TITLE
doc.rs shows build failure

### ISSUE THREAD

**Issue by 95th** [rust-lang-nursery/futures-rs#1800]
docs.rs show error for the latest release

![Capture](https://user-images.githubusercontent.com/22871609/62998170-4856f980-be88-11e9-9ef1-4fdaa0025c16.PNG)

**Comment by Nemo157** [comment]
The current nightly in use is too old, once docs.rs updates we can probably get them to rebuild the docs.

**Comment by taiki-e** [comment]
Seems to have been fixed: https://docs.rs/futures-preview/0.3.0-alpha.18/futures/
