### ISSUE TITLE
cannot find macro `proc_macro_call_0!` in this scope

### ISSUE THREAD

**Issue by fenhl** [rust-lang-nursery/futures-rs#1808]
I'm hitting this error when trying to use `futures::select` on the latest nightly.

# Minimal example

Cargo.toml:

```toml
[package]
name = "select-min"
version = "0.1.0"
edition = "2018"

[dependencies.futures-preview]
version = "=0.3.0-alpha.18"
features = ["async-await", "nightly"]
```

main.rs:

```rust
fn main() {
    futures::select! {}
}
```

Output of `cargo +nightly check`:

```
    Checking select-min v0.1.0 (C:\Users\Fenhl\Desktop\select-min)
error: cannot find macro `proc_macro_call_0!` in this scope
 --> src\main.rs:2:5
  |
2 |     futures::select! {}
  |     ^^^^^^^^^^^^^^^^^^^
  |
  = help: have you added the `#[macro_use]` on the module/import?
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error

error: Could not compile `select-min`.

To learn more, run the command again with --verbose.
```

Adding `#[macro_use] extern crate futures;` does not fix this.

**Comment by Nemo157** [comment]
Probably related to https://github.com/dtolnay/proc-macro-hack/issues/40 and https://github.com/rust-lang/rust/issues/63651, seems `proc-macro-hack` doesn't work on the latest nightlies. Easiest workaround for now is to go back a nightly or two.

**Comment by fenhl** [comment]
Can confirm, the macro works fine on `nightly-2019-08-15`.

**Comment by lneicelis** [comment]
how to set nightly to specific version?

**Comment by fenhl** [comment]
First, install the nightly with `rustup toolchain install nightly-2019-08-15`. Then in your crate directory, run `rustup override set nightly-2019-08-15`. Alternatively, run all `cargo` commands like e.g. `cargo +nightly-2019-08-15 build`.

**Comment by taiki-e** [comment]
Fixed in `nightly-2019-08-19`.
