### ISSUE TITLE
Rename `select!` to `race!`

### ISSUE THREAD

**Issue by jhpratt** [rust-lang-nursery/futures-rs#1809]
Stealing from JavaScript's [`Promise.race`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race) here, which I believe is a more descriptive name.

**Comment by archseer** [comment]
There's already a previous discussion at https://github.com/rust-lang-nursery/futures-rs/issues/760

**Comment by jhpratt** [comment]
Thanks, closing as dupe.
