### ISSUE TITLE
`SinkExt::send_all` should work with `TryStream`?

### ISSUE THREAD

**Issue by tedsta** [rust-lang-nursery/futures-rs#1817]
I have a `Sink<MyMsg, Error=MyError>` and I'd like to `send_all` it a stream, `Stream<Item=Result<MyMsg, MyError>>`.

`StreamExt::forward` almost works for me, but I need to keep using the `Sink` after.

Perhaps a `SinkExt::try_send_all` with `where St: TryStream<Ok = Item, Error = Error>`? I can send a PR if you guys are open to it.

**Comment by cramertj** [comment]
Agreed-- `TryStream` seems sensible to support here.
