### ISSUE TITLE
Syntax sugar for select! when using futures that return () or !

### ISSUE THREAD

**Issue by canndrew** [rust-lang-nursery/futures-rs#1825]
I'm not sure whether this is actually a good idea, but I want to put it out there and hear other opinions. I quite often `select!` over futures that return `()` or `!`. Currently, the way I write this is:

```rust
futures::select! {
    () = unit_future() => { ... },
    never = never_future() => match never {},
}
```

There's a couple of problems with this. First, having to match on a unit with `()` is slightly cumbersome. Rust statements which return unit don't usually force us to do this (eg. we can write `do_a_thing();`, rather than `let () = do_a_thing();`).

Secondly, having to match on a never by binding it to a variable then explicitly matching it away is more cumbersome and also raises unreachable code warnings.

Would it be worth adding syntax for these two cases which allow omitting the `()` pattern when matching on unit and omitting the branch (and possibly the pattern) when matching on never? I'm imagining this looking like:

```rust
futures::select! {
    unit_future() => { ... },
    
    never_future(),

    // or possibly
    ! = never_future(),
}
```

The downside is, of course, that it makes the syntax more ad-hoc, but these do seem like common special cases.

**Comment by Matthias247** [comment]
I see the motivation for this pretty weak. You can currently already write `_ = unit_future()`, so we remove the need for 2 characters and 2 whitespaces.

However it shouldn't be hard to support. If the expression doesn't parse as `ident = expr`, just try again with only `expr` and use `_` as ident.

**Comment by canndrew** [comment]
> You can currently already write` _ = unit_future()`

I don't think that's a good idea since it's not clear that you're throwing away a `()`. Also `unit_future` might get changed in the future to return something else in which case this code will start silently throwing away something other than `()` when it would be preferable to make this line of code fail type-checking instead.

Really though I'm more interested in syntax sugar for `!`-futures. Having to write `() = ` is not a big deal.

**Comment by cramertj** [comment]
I don't think these are changes I'm interested in at the moment, so I'm going to close this issue. Perhaps once `!` stabilizes (soon for real this time!) and has seen some use in the wild it will become more clear that a shorthand is necessary here, though I sort of doubt it will justify builtin syntax in `select!`.
