### ISSUE TITLE
CopyBufInto::poll does not flush until the input stream is completely drained

### ISSUE THREAD

**Issue by najamelan** [rust-lang-nursery/futures-rs#1828]
@Nemo157 @talchas I saw #1771, but this issue is slightly different, specifically about flushing behavior.

It doesn't seem correct to me. I'm using it for an echo server over `AsyncRead`/`AsyncWrite`, because those have a small buffer of 8k, which hurts performance. Maybe that's not a correct use case, but then what should I use? `AsyncReadExt::copy_into` shows exactly the same behavior. Documentation for neither methods say anything about flushing. They just say that the future will only resolve once the reader has hit EOF.

```rust
BufReader::with_capacity( 512_000, reader ).copy_buf_into( &mut writer ).await
```

When `poll_fill_buf` pulls in some data, it calls `poll_write` on the writer. Since this is in a loop, we try `poll_fill_buf` again. Ok, there is no more data to read, so it returns pending and `CopyBufInto::poll` just returns, not flushing the writer. This means that the data will just sit in the writer's buffer and never gets send out over the network until the connection from the reader gets closed, or the buffer of the writer is full.

I recon that after writing, if there is no more data to read, we should flush the writer, since for networking code there is no telling when the next incoming message will be.

**Comment by Nemo157** [comment]
Part of the `AsyncWrite::poll_write` contract is it must attempt to flush data out to accept the incoming write.

**Comment by Nemo157** [comment]
Oh, actually I misunderstood, so what you're describing is a situation in which the reader will send some data, then wait a bit, then send more, and in the meantime you expect that initial chunk of data to make it to the writer?

This behaviour would depend on the writer you're using, I would expect any `UdpSocket` or `TcpStream` to already satisfy this since the underlying kernel IO will buffer the data and set a timeout to send it. If you are wrapping that in a `BufWriter` then it won't as it just buffers until an explicit flush is required.

Sounds like what you need is something like [`LineWriter`](https://doc.rust-lang.org/nightly/std/io/struct.LineWriter.html) that will inject flushes in based on the data being sent, or something which buffers and injects flushes based on timeout from last write. As far as I know neither of these abstractions exist yet.

**Comment by najamelan** [comment]
What happens is since `AsyncRead`/`AsyncWrite` have 8k buffers, you will get reads and writes in small chunks. So to avoid that, it makes sense to keep reading and passing data onto a sender until you hit pending. However it seems to me that at that moment it makes sense to do a flush, because the next batch of data might not come in for a long time. That way the `AsyncWrite` can accumulate data while it's coming in, and flush it out further once there is nothing more "for now". 

This is to get around sending stuff in 8k batches. I thought that BufReader and BufWriter where meant for such scenarios, but maybe I'm missing something.

The thing is you cannot solve this from the writer side. If you would buffer for a while and then flush even though you only have `poll_write` called, and not `poll_flush`, when would you do it, after 1 call to `poll_write`, after two calls? There is no telling if more data is going to come in. Something needs to tell you, hey we've exhausted the available data, now flush.

**Comment by Nemo157** [comment]
This is identical behaviour to the equivalent `std::io` types:

```rust
fn main() {
    let listener = std::net::TcpListener::bind("0.0.0.0:9052").unwrap();
    println!("listening on {}", listener.local_addr().unwrap());
    let stream = listener.incoming().next().unwrap().unwrap();
    let mut writer = std::io::BufWriter::new(&stream);
    let mut reader = std::io::BufReader::new(&stream);
    std::io::copy(&mut reader, &mut writer).unwrap();
}
```

It can be solved from the writer side by injecting flushing as I mentioned, either via known data patterns (e.g. flush on newlines) or flush on idle via a short timeout after the last `poll_write` call.

This also doesn't seem like a situation where you need buffering on the writer side at all. You are already buffering the reader so you will be writing big chunks of data (and when you don't have a big chunk of data you want to be flushing it out straight away anyway), the main point of write-side buffering is to coalesce small writes into one big write.

**Comment by najamelan** [comment]
> You are already buffering the reader so you will be writing big chunks of data

You are right. I now checked and just calling `copy_into` on `AsyncRead` creates a `BufReader` with an 8k buffer. Manually creating the BufReader with a bigger buffer and calling `copy_buf_into` solves this. BufReader calls it's inner reader with it's buffer, so that will read a big chunk, and `copy_buf_into` will call the writer with that big buffer. Great.

So I could solve this by flushing out my `AsyncWrite` after each `poll_write`. But then why does `AsyncWrite` have a `poll_flush` at all? It feels like I break the semantics of the trait.

I pass on the data to a Sink of websocket messages. If I flush that sink on `poll_write`, I basically say to my users, there is buffering here, but you can't use it. You will have to buffer data before calling `poll_write`, because `poll_write` will immediately flush everything out on the network. 

I'm not sure if I like that design overall, but it would make `CopyBufInto` work.

That's why I feel `CopyBufInto` should call flush on the writer when no more data is available. As for timeout mechanisms, I really wouldn't go there. I would rather roll a `CopyBufInto` myself that flushes when no  more data can be read than using timeouts.

----

Another problem with the current algorithm is that if the writer ever returns `Poll::Pending`, the `CopyBufInto` will be pending and if it hasn't emptied the reader, it will never flush the writer, so it will just deadlock. 

It isn't really documented what the desired behavior of `copy_buf_into` is, but I would have expected it do to the following:
1. Try to read as much as you can
2. Try to write out as much as you can
3. If we stopped because the writer emptied our buffer, go to 1
    If we stopped because the writer returns pending, flush it. If `poll_flush` returns pending, return pending to be woken up when the writer is ready to take more data.
4. When the reader returns pending, 
    a. if we didn't get any data, return pending
    b. if we have written data to the writer and we have nothing left, flush the writer to let it know we are out of data for now and return pending, to be waken up when the reader has more data.

**Comment by najamelan** [comment]
I would like to make one comment on the API design. It looks like if methods like `AsyncRead::copy_into` just allowed you to specify a buffer size (and `std::io::copy` as well for that matter), maybe we don't even need a `BufReader` API.

**Comment by Nemo157** [comment]
> Another problem with the current algorithm is that if the writer ever returns `Poll::Pending`, the `CopyBufInto` will be pending and if it hasn't emptied the reader, it will never flush the writer, so it will just deadlock.

If the writer returns pending it is now its responsibility to wake the task when more data can be written, a deadlock here would indicate a buggy `AsyncWrite` implementation.

> I pass on the data to a Sink of websocket messages.

What are you using to treat the sink as a writer? There might be some extra buffering here that is causing the issue, I'll try and throw together an example to see whether there is an unavoidable mismatch between the APIs.

> If we stopped because the writer returns pending, flush it. If poll_flush returns pending, return pending to be woken up when the writer is ready to take more data.

This is unnecessary since `poll_write` must flush before returning pending. Other than that, I think adding in flushing of the writer while the reader is pending might actually be ok. I thought at first that it would block writing the next block of data in when the reader is ready again, but of course it won't because we don't need to wait for the flush to complete, we can stop flushing and go back to writing as soon as the reader is ready.

**Comment by najamelan** [comment]
Ok, it took some time, but I think I figured it out.

> What are you using to treat the sink as a writer?

Im implementing that myself in ws_stream, which isn't published yet. It uses a `CompatSink01As03` under the hood  because tokio-tungstenite still is on 0.1. This always buffers one item to deal with the difference of 0.1 and 0.3 Sink API's, so it needs to be flushed explicitly to make sure data doesn't hang in transit. I thought it made sense I do that in `poll_flush` of my AsyncWrite, rather than in `poll_write`. 

However since I don't buffer internally, I always make an entire websocket message of the buffer in `poll_write`, I could flush it there, ignoring the pending that might return.

Thus the question really is, is the burden on the client code to call AsyncWrite with a sufficiently large buffer to avoid performance problems, or should an AsyncWrite buffer to allow the client to call `poll_write` repeatedly until it is flushed explicitly?

I had a look at primary users of AsyncRead/AsyncWrite, framed streams. It turns out both futures-codec and tokio-codec will buffer internally and call `poll_write` on the underlying stream only when they get flushed. So they turn a semantic flush into a write which seems to confirm that it makes sense for AsyncWrite to flush in `poll_write`.

Eg. my little echo server takes this responsability by using a BufReader with a bigger buffer than just calling `AsyncRead::copy_into`. And BufWriter would allow users to compensate if third party libraries like futures-codec would not do this. 

So all in all, I think I should just flush in `poll_write`, and if what I'm saying here is correct, I would like to make a PR for the documentation of AsyncWrite to be much clearer as to avoid new users going through the same debugging I had to.

In that case, It's actually ok not to change `CopyBufInto`. I suppose it would change it's semantics from something like `SinkExt::send_all` to a repeated `SinkExt::send`. 

If implementors of AsyncWrite can assume the burden is on the client to call with a sufficiently large buffer, and we advise them to always flush the wrapped object in `poll_write`, then I think we shouldn't change `CopyBufInto`, since a write will trigger a flush anyway.

> This is unnecessary since poll_write must flush before returning pending.

If this is the reasoning, I think it should be added to the documentation of `AsyncWrite::poll_write`, which says no such thing right now, so I didn't take that into account when thinking about the algorithm.

**Comment by ChrisGreenaway** [comment]
I'm doing something remarkably similar to @najamelan - I'm implementing an AsyncWrite wrapper over a Sink from https://crates.io/crates/websocket . I'm also using a 0.1 - 0.3 compat layer, but the start_send method on Sink explicitly doesn't necessarily do a flush anyway, so it doesn't matter that much if the compat layer does buffering.

I'm not convinced about just ignoring the Pending response from the flush. If it did return a Pending then would that stall the pipeline? In other words, what would be responsible for calling poll_flush or poll_write on the AsyncWrite to complete the flush? I'm not even sure which context to use for the sink poll_flush call because if I reuse the one arriving in the AsyncWrite poll_write call then the Waker might be called for the flush Pending rather than the write Pending, but poll_write shouldn't be called again.

Just to come up a level to make my use case more explicit, I'm using copy_into to proxy a local socket to a websocket - i.e. I have a TcpStream (with ReadHalf and WriteHalf) and a websocket equivalent and I'm using copy_into to just connect the readers to the writers.

The problem comes for me when copy_into does a read from the local socket and then writes into the websocket AsyncWrite. Because there's no flush, the message never gets sent and the higher level protocol stalls. The server on the other end of the websocket nevers gets the message and so never sends anything back to be written back to the local socket.

I liked @najamelan 's original suggestion, that if copy_into is pending on a read, then it should explicitly flush on the write side.

**Comment by najamelan** [comment]
Yeah, if you pass the context from `poll_write` to the flush, there might be a spurious wakeup. It's probably fine, but I have yet to do proper testing to trigger this and see what happens. 

In my case, since I always construct an entire websocket message in poll_write, I have to return how many bytes we took, so the client code never tries to send these bytes again. That's why I think it's not an option to return pending if the flush from the sink returns pending, so I ignore it for now. 

The wakeup would just trigger the task to run again, like trying to read again from the reader, which might still not have data, but it would just return pending in that case. Also since poll_write depends on `poll_ready` giving a green light before calling `start_send`, it should be safe.

If the wakeup would give a problem, it's possible to call it with a dummy context. I know that [futures-test-preview](https://crates.io/crates/futures-test-preview) has those.

**Comment by cramertj** [comment]
There's some good discussion happening in this issue, but I think there aren't any action items for futures-rs here. Please correct me if I'm wrong (either if a change is wanted, or more documentation is needed to clarify things) and I'll happily reopen!

**Comment by ChrisGreenaway** [comment]
I don't think this should be closed. Ideally there should some earlier flushing, but at a minimum the lack of flushing should be documented.

In the end, I wrote my own version of copy_into that had the flushing behaviour I wanted, so I don't need this fixed, but I think would be the right thing to do.

**Comment by najamelan** [comment]
@cramertj  I originally felt that for my specific use case, since I built an entire binary websocket message for every call to `poll_write` (eg. I don't do any buffering) it was fine for me to just flush every time. 

So I felt that mainly AsyncWrite is missing some hints in documentation for implementers and users alike. I wanted to file a documentation PR once someone confirmed that my conclusions in https://github.com/rust-lang-nursery/futures-rs/issues/1828#issuecomment-525386574 where correct, but that hadn't happened yet. 

To make progress I'll go on and make a docs PR with some propositions, and it will probably be easier to discuss whether the assumptions I make are correct when looking at a concrete proposal.

It seems that for @ChrisGreenaway however the original proposition of changing the behavior `copy_buf_into` does make sense. The question remains are there any uses for which flushing when the read pends is a problem? Either way, I would propose we document the chosen behavior, eg. either warning that it won't call flush if the reader pends, or explaining that it does.

**Comment by Nemo157** [comment]
I have a usecase now where inserting extra flushing is bad: in `async-compression` flushing an `async-compression::write::DeflateEncoder` will cause the current block to be finished and flushed out, even if more data could be written to it, so adding extraneous flushing will result in reduced compression efficiency.

**Comment by najamelan** [comment]
Actually, I had another look over users of AsyncRead/AsyncWrite like tokio-codec. It seems I was mistaken above and they will also call `poll_write` and `poll_flush` from `poll_ready` if there internal buffer is full. So it seems they never call `poll_write` without following it up with a flush, in contrast to `copy_buf_into`.

I do feel that there are just 2 different use cases here, a bit like `Sink::send` vs `Sink::send_all`. Either we want to wait to have all data, or we want data to flow through when there are breaks on the producer end.

Would it make sense to either take a `flush` parameter in a method like `copy_buf_into`, or provide 2 different methods, like `copy_buf_into_all`. 

One thing that makes me wonder about flushing only on the end is that it's already possible to detect the end of the stream in `poll_close`. @Nemo would your usecase not work by buffering until `poll_close` get's called?

**Comment by Nemo157** [comment]
Buffering until `poll_close` would not satisfy the semantics of `poll_flush`. If a user requests flushing of the stream then the other end of the IO channel should be able to receive all data up until that point (e.g. if the IO channel is used as something like a websocket message transport and you flush after each message the remote should be able to fully receive the message).
