### ISSUE TITLE
Separate Spawn/LocalSpawn from futures-core?

### ISSUE THREAD

**Issue by taiki-e** [rust-lang-nursery/futures-rs#1830]
I think this trait is not as stable as other `futures-core`'s items like `Stream`.

Related:
  * https://github.com/rust-lang-nursery/futures-rs/issues/1669
  * https://github.com/rust-lang-nursery/futures-rs/issues/1634#issuecomment-495513571

**Comment by seanmonstar** [comment]
I agree with this, especially with the odd-feeling `spawn_obj(FutureObj)` method (and the issues you linked). I think it could be moved to `futures-executor` (and the executor implementations could be made optional, so depending on the crate doesn't require depending on executors you don't use).

**Comment by taiki-e** [comment]
> I think it could be moved to `futures-executor` (and the executor implementations could be made optional, so depending on the crate doesn't require depending on executors you don't use).

The executor implementations (`LocalPool`, `ThreadPool`) depend on `futures-util`, `futures-util` (`SpawnExt`, `Executor01CompatExt`, `Executor01Future`, `Executor01As03`) depends on `Spawn` trait, so we need to resolve these circular dependencies.

**Comment by cramertj** [comment]
#1925 has landed.
