### ISSUE TITLE
Impl Sink for With should buffer the items

### ISSUE THREAD

**Issue by hosyvietanh** [rust-lang-nursery/futures-rs#1834]
I recently faced an issue when using `Sink` to send websocket messages.
I used `sink.with` in order to modify the msg before actually sending it. The items are not buffered which caused some messages being lost.
https://github.com/rust-lang-nursery/futures-rs/blob/e9cd539cc977fda701f6f4679ee435fa66986ed8/futures-util/src/sink/with.rs#L171

I'm not sure if I understand the purpose of `with` correctly, but I think it should buffer the items when calling `start_send` instead of replacing the old ones.

**Comment by Nemo157** [comment]
There is definitely a bug because is `With::poll` not calling `self.sink.poll_ready` before it attempts to send the buffered item, but if the underlying sink isn’t ready to accept it then that should result in an error rather than missing items, so there may be something else I’m missing.

**Comment by Nemo157** [comment]
Actually, I guess `With` itself doesn’t guarantee an error if you start sending before it’s ready, so maybe the underlying sink could be similar. Unfortunately I don’t see any way for `With` to create an error if `start_send` is called while it has a buffered item...

**Comment by cramertj** [comment]
I think #1880 is all we're planning to do on this-- let me know if more is wanted here.
