### ISSUE TITLE
Should the `Fut` closure passed to TryStreamExt::try_filter_map really return a TryFuture?

### ISSUE THREAD

**Issue by Follpvosten** [rust-lang-nursery/futures-rs#1852]
So I don't know about the backgrounds or internals, but from a pure user perspective, returning a TryFuture doesn't make a lot of sense; the purpose is filtering and simultaneously mapping the `Ok` value to a different type, so why do I need to consider another `Err` possibility?

To me, it looks like the closure should return a `Future<Output = Option<T>>`, that way, it stays consistent with what the futures 0.1 Stream does and doesn't overcomplicate things like returning a `Result<Option<T>>` does.

**Comment by cramertj** [comment]
It's possible that the closure you're providing could fail in some way-- we want to make that possible without requiring multiple layerings of `Result`. If this isn't needed, it's easy to wrap the result in `Ok`, but if it's not needed, it's much more difficult to go the other way around.
