### ISSUE TITLE
`first_or_else` combinator

### ISSUE THREAD

**Issue by thomaseizinger** [rust-lang-nursery/futures-rs#1883]
We have our own `first_or_else` combinator in our codebase that is based on futures-0.1.

Would this be something worth contributing back and porting to futures-0.3?

```rust
pub trait StreamExt: Stream {
    /// Returns a future that resolves with the first element of the stream
    fn first_or_else<F: FnOnce() -> Self::Error>(self, or_else: F) -> FirstOrElse<Self, F>
    where
        Self: Sized,
    {
        FirstOrElse {
            stream: self,
            or_else: Some(or_else),
        }
    }
}

impl<S> StreamExt for S where S: Stream {}

pub struct FirstOrElse<S, F> {
    stream: S,
    or_else: Option<F>,
}

impl<S, I, E, F> Future for FirstOrElse<S, F>
where
    S: Stream<Item = I, Error = E>,
    F: FnOnce() -> E,
{
    type Item = I;
    type Error = E;

    fn poll(&mut self) -> Poll<Self::Item, Self::Error> {
        match self.stream.poll() {
            Ok(Async::Ready(Some(item))) => Ok(Async::Ready(item)),
            Ok(Async::Ready(None)) => {
                let or_else = self
                    .or_else
                    .take()
                    .expect("must not be polled after completion");

                Err(or_else())
            }
            Ok(Async::NotReady) => Ok(Async::NotReady),
            Err(e) => Err(e),
        }
    }
}
```

**Comment by cramertj** [comment]
To clarify, the behavior of this combinator is that it runs a stream until it produces `None`, at which point it runs the provided function to produce an error? That seems rather niche to me and could also be accomplished using the `chain` combinator, unless I've misunderstood.

**Comment by thomaseizinger** [comment]
Not quite! :)
`FirstOrElse` only implements `Future` but not `Stream`.
This combinator is useful if you are only interested in the first (Ok) item of a (Result) Stream or emit an error if the stream ends before emitting anything :)
Hence the name: `FirstOrElse`!

**Comment by cramertj** [comment]
`stream.next().map(|first| first.unwrap_or_else(|| or_else()))` <- does this do what you want?

**Comment by thomaseizinger** [comment]
Maybe!
`next` didn't exist in futures 0.1 right? That is the reason we added `first_or_else` to our codebase :)
If my understanding of `next` is correct, I doesn't consume and thereby not terminate the stream.
I would like a terminating behaviour that either gives me a future of the first item or returns the error. In addition, the ergonomics of being able to directly chain `Future` combinators onto `first_or_else` is quite nice. Don't you run into lifetime problems if `first` only mutably borrows the stream?

Maybe it is also helpful to describe the iteration process of how we got to this design. Initially, we only had a `first` combinator but that brought up the question, how to handle the case of a stream that terminates without yielding any items. Returning an option from `first` resulted in bad ergonomics for downstream code that wanted to only handle the succesful case in an `and_then`. Hence we thought that yielding an error would actually be the most appropriate.
`first_or_default` could also be a possible combinator inspired by this one!

**Comment by cramertj** [comment]
`.next` is roughly `Stream::into_future` from 0.1, which you can use to do the same thing.

**Comment by thomaseizinger** [comment]
Ah yeah, I am aware of `into_future` but the ergonomics are bad and it results in quite a bit of code duplication and noise if you need to do `into_future` and `map` with `unwrap_or_else` in several places.

To me, having a `first_or_else` combinator seems to be clearly advantagous over that, however, overall I get the impression that you don't like it?

What are the requirements for getting new combinators accepted?

**Comment by cramertj** [comment]
I don't dislike it, but I'd prefer to avoid introducing operators that can be written fairly easily in terms of other operators for all but the most common cases.

**Comment by thomaseizinger** [comment]
Understood :)
Is there another place of where combinators like these could go?
An unstable feature flag for example or a separate crate that has a lower entry barrier and people can try out and give feedback on those?
It would be cool to contribute it to somewhere instead of having it sit in our project.

**Comment by thomaseizinger** [comment]
I just saw that `futures` actually _has_ an `unstable` feature. Would consider pulling such a combinator in as _unstable_?

**Comment by cramertj** [comment]
`unstable` isn't intended for things we're not sure whether we want to include, it's there for things we want to include but aren't yet stable.
