### ISSUE TITLE
Release `0.3.0-alpha.19`

### ISSUE THREAD

**Issue by bmwill** [rust-lang-nursery/futures-rs#1884]
The last release of the futures-preview crate happened back in the beginning of August. Since then the `async_await` feature has been stabilized on nightly as well as in the 1.39.0 beta and it would be nice to be able to build this crate using the recently released beta compiler. So it would be great to do another release that includes #1816.

cc @cramertj @taiki-e

**Comment by cramertj** [comment]
Sounds good! I'll put one together now.
