### ISSUE TITLE
How to loop future infinitely, what happened to loop_fn?

### ISSUE THREAD

**Issue by peku33** [rust-lang-nursery/futures-rs#1892]
I want to build rust program that supervises child process, logs its stdin/out and restarts it with delay if program dies.

I'm using nightly version + futures-core-{preview, util} 0.3.0-alpha.18

I had no problems writing spawning and waiting function:
```
async fn start_process(
    &self
) -> () {
    let mut command = self.command_build(); // returns tokio_net::process::Command (also pipes std{out,err} and nulls stdin)
    let mut child = command.spawn().unwrap(); // tokio_net::process::Child
    
    let stdout = tokio::codec::FramedRead::new(
        child.stdout().take().unwrap(),
        tokio::codec::LinesCodec::default(),
    ).for_each(|message| {
        // log message
        return futures_util::future::ready(());
    });

    let stderr = tokio::codec::FramedRead::new(
        child.stderr().take().unwrap(),
        tokio::codec::LinesCodec::default(),
    ).for_each(|message| {
        // log message
        return futures_util::future::ready(());
    });

    // wait for process to finish
    child.await.unwrap();
    stdout.await;
    stderr.await;

    return ();
}
```

The next step is to build a loop that will restart the process if it ends (it should be long-running and dies only on fatal errors).

I'm pretty sure that setting up tokio delay timer (resolves future after certain amount of time) is fine, however I'm not sure how to build an inifinite loop for that.

While doing something like
```
pub async fn start_process_watch(
    &self
) -> () {
    loop {
        self.start_process().await;
        tokio_timer::delay_for(std::time::Duration::from_secs(15)).await;
    }
    return ();
}
```
may work, I'm not pretty sure if it's correct. What i'm worried about is the process of canceling this thing, for example when I'm not longer interested (or want to stop) in the process.

The IDE also warns me about unreachable code - the return statement.

What I want to achieve is to have function that:
- runs the process and waits 15s if it dies, then restarts it.
- stops the process / kills the timer if caller (future owner?) is not longer interested in it (future is dropeed)
- never resolves, returns nothing

In the past I saw loop_fn / tail_fn, but I'm not sure what happened to this.

What is the correct way to do this on 29.09.19?

Best regards.

**Comment by Matthias247** [comment]
I think this question is more appropriate for stackoverflow than here, since it's not in particular about futures-rs.

What you want is:
- A signal whether the process exists - likely in the form of a Future - That might be provided by Tokio.
- A mechanism to wait at max 15s - that is provided e.g. by tokio timers
- A mechanism to wait on either condition to happen first. You can use the `select!` macro from this library to do that.

**Comment by peku33** [comment]
Indeed, will move this to stackoverflow
