### ISSUE TITLE
Documentation not available for alpha.19

### ISSUE THREAD

**Issue by elpiel** [rust-lang-nursery/futures-rs#1898]
Currently in [crates.io](https://crates.io/crates/futures-preview/0.3.0-alpha.19) the link to the documentation: https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.19/futures is non existent.

**Comment by Nemo157** [comment]
Looks like the auth token used to publish them is expired/revoked/doesn't have access: https://travis-ci.com/rust-lang-nursery/futures-rs/jobs/239482255#L1679

**Comment by Nemo157** [comment]
Since #1895 stops using these published docs I think it's best to delete this automation and just manually publish the `alpha.19` docs so that the current link works, I can do that shortly.

**Comment by Nemo157** [comment]
Should be fixed now.
