### ISSUE TITLE
Add async-await to default-features?

### ISSUE THREAD

**Issue by Nemo157** [rust-lang-nursery/futures-rs#1904]
Since it works on 1.39 it might make sense to have this as a default-active feature. It's a significant bump in build-time, but the `join!` and `select!` macros seem useful/common enough to warrant it to me.

**Comment by cramertj** [comment]
Makes sense to me, thought the build time cost is a bit unfortunate, especially since we can't undo this in a backwards-compatible way. I'll make this change unless anyone objects.
