### ISSUE TITLE
select! block doesn't work as expected.

### ISSUE THREAD

**Issue by xudesheng** [rust-lang-nursery/futures-rs#1905]
I try to follow the guide on [Asynchronous Programming in Rust](https://rust-lang.github.io/async-book/06_multiple_futures/03_select.html).

But I found select! always let first option finish first. In current code, t1 always finishes earlier than t2.

if I switch sequence in select! like:
```
select! {
        () = t2 => println!("task two completed first"),
        () = t1 => println!("task one completed first"),
    }
```
, then t2 will finish first.

Cargo.toml:
```
rand = "0.7.2"
futures-preview = { version = "=0.3.0-alpha.19", features = ["async-await"] }

```
origin code:

```
use futures::{
    future::FutureExt, // for `.fuse()`
    pin_mut,
    select,
};
use rand::prelude::*;
use std::{thread, time};
use futures::executor::block_on;

async fn task_one() { 
    let mut rng = rand::thread_rng();
    let y: u64 = rng.gen_range(500,600);
    eprintln!("task one got value:{}", y);
    
    let millis = time::Duration::from_millis(y);

    thread::sleep(millis);
}

async fn task_two() {
    let mut rng = rand::thread_rng();
    let y: u64 = rng.gen_range(2,5);
    eprintln!("task two got value:{}", y);

    let millis = time::Duration::from_millis(y);

    thread::sleep(millis);
}

async fn race_tasks() {
    let t1 = task_one().fuse();
    let t2 = task_two().fuse();
    
    pin_mut!(t1, t2);

    select! {
        () = t1 => println!("task one completed first"),
        () = t2 => println!("task two completed first"),
    }
}

fn main(){
    block_on(race_tasks())
}

```

**Comment by Matthias247** [comment]
Two issues:

1. If multiple branches of a `select!` expression are ready at the same time, it provides no guarantee which branch will be taken. It is intentionally randomized.

2. In the posted code there are blocking `thread::sleep()` calls in both async functions, which cause the executor for async functions (`block_on()`) to block until the function was completely executed. Therefore whichever async fn is tried first will block the whole scheduler, run to completion, and prevent the other branch from even being tried. You can use an async timer to fix the example. Don't utilize any thread-blocking code in async methods.

**Comment by xudesheng** [comment]
thank you. I'm convinced. :)
