### ISSUE TITLE
Confused about select! and tokio::timer::Delay

### ISSUE THREAD

**Issue by importcjj** [rust-lang-nursery/futures-rs#1906]
futures-preview 0.3
tokio 0.2

Code A

```rust
    let mut heartbeat = timer::delay_for(Duration::from_secs(3)).fuse(); // here
    let mut heartbeat2 = timer::delay_for(Duration::from_secs(15)).fuse(); // here

    loop {
        select! {
            _ = heartbeat => println!("send heartbeat"),
            _ = heartbeat2 => println!("send heartbeat2"),
            complete => break,
        }
    }
```

Code B
```rust

    let mut heartbeat = timer::delay_for(Duration::from_secs(3));
    let mut heartbeat2 = timer::delay_for(Duration::from_secs(15));

    loop {
        select! {
            _ = heartbeat => println!("send heartbeat"),
            _ = heartbeat2 => println!("send heartbeat2"),
            complete => break,
        }
    }
```

They are almost the same, but code A works good, and code B can print nothing. 
According to my understanding, The `Delay` has already implemented the `FusedFuture` trait, but why I still need to use the `fuse` to convert it. Can anybody explain it?

**Comment by Nemo157** [comment]
This is a Tokio bug, the FusedFuture impl for Delay is incorrect

**Comment by cramertj** [comment]
Yeah, [`is_elapsed` here](https://github.com/tokio-rs/tokio/blame/master/tokio-timer/src/delay.rs#L97) isn't the correct check. Even though the timer has elapsed, the future may not yet have yielded an output.
