### ISSUE TITLE
Provide implementation of futures::io::AsyncRead and futures::io::AsyncBufRead for Vec<u8>?

### ISSUE THREAD

**Issue by jmjoy** [rust-lang-nursery/futures-rs#1913]
I found that only `&[u8]` is implemented of `futures::io::AsyncRead` and `futures::io::AsyncBufRead`, and `Vec<u8>` is implemented of `futures::io::AsyncWrite`. 
But sometimes I need to push a param to a third-part function which accept a type need to implement both `AsyncRead` and `AsyncWrite`, but `Vec<u8>` can't, so can you provide it?

**Comment by Nemo157** [comment]
Directly implementing read for vec is probably not what you want, it has nowhere to store the currently read offset.

The question would be what sort of `AsyncRead + AsyncWrite` is expected? A network connection like one where the two halves are independent would be possible by combining a `&[u8]` backed reader with a `Vec` backed writer. A file like one where reading and writing affect each other would be possible to emulate using something like `Cursor<Vec<u8>>`

**Comment by jmjoy** [comment]
@Nemo157 Thanks, I think `Cursor` is a good choice.
