### ISSUE TITLE
problem with iteration over stream of results

### ISSUE THREAD

**Issue by debris** [rust-lang-nursery/futures-rs#1920]
**rustc 1.39.0-beta.6 (224f0bc90 2019-10-15)**
**futures-preview = "0.3.0-alpha.19"**

I just stumbled upon weird compiler output when  using `?` operator while iterating over stream of results.

```
error[E0277]: `?` couldn't convert the error to `Error`
  --> src/lib.rs:25:32
   |
25 |     for value in s.next().await? {
   |                                ^ the trait `std::convert::From<std::option::NoneError>` is not implemented for `Error`
   |
   = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
   = note: required by `std::convert::From::from`

```

I expected both of the functions attached below to compile correctly

```rust
use futures::stream::{self, Stream, StreamExt};

pub struct Error;

fn my_stream() -> impl Stream<Item = Result<u8, Error>> {
    stream::repeat(1).map(Ok)
}

pub async fn foo_working() -> Result<u8, Error> {
    let mut s = my_stream();
    let mut acc = 0;
    for value in s.next().await {
        let value = value?;
        acc += value;
    }

    Ok(acc)
}

pub async fn foo_not_working() -> Result<u8, Error> {
    let mut s = my_stream();
    let mut acc = 0;
    // fails with  
    // the trait `std::convert::From<std::option::NoneError>` is not implemented for `Error`
    for value in s.next().await? {
        acc += value;
    }

    Ok(acc)
}
```

[link to source](https://github.com/debris/for_stream_next/blob/master/src/lib.rs)

**Comment by Nemo157** [comment]
This error message is correct, you're running into the issue that both `Option` and `Result` implement `IntoIterator` so can be used in a `for` loop, but that's definitely not what you want (so while `foo_working` compiles it will only see the first element of the stream). If there wasn't `IntoIterator` for `Result` you would get an additional error:

```

error[E0277]: `NotResult<u8, Error>` is not an iterator
  --> src/lib.rs:43:18
   |
43 |     for value in s.next().await? {
   |                  ^^^^^^^^^^^^^^^ `NotResult<u8, Error>` is not an iterator
   |
   = help: the trait `std::iter::Iterator` is not implemented for `NotResult<u8, Error>`
   = note: required by `std::iter::IntoIterator::into_iter`
```

To loop over a stream now you should use `while let Some(value) = s.next().await`, to do something like you intend to short-circuit when the stream produces any errors you can do `while let Some(value) = s.next().await.transpose()?`.
