### ISSUE TITLE
Mutex try_lock returns an Option instead of a Result

### ISSUE THREAD

**Issue by rasviitanen** [rust-lang-nursery/futures-rs#1942]
As `std::sync::Mutex`'s `try_lock` returns a Result,  I think `futures::lock::Mutex` should do the same (which currently returns an `Option`).

[std's Mutex's try_lock documentation](https://doc.rust-lang.org/std/sync/struct.Mutex.html#method.try_lock)
[future's Mutex's try_lock documentation](https://docs.rs/futures-preview/0.3.0-alpha.19/futures/lock/struct.Mutex.html#method.try_lock)

The current `try_lock`:
```
pub fn try_lock(&self) -> Option<MutexGuard<'_, T>> {
    let old_state = self.state.fetch_or(IS_LOCKED, Ordering::Acquire);
    if (old_state & IS_LOCKED) == 0 {
        Some(MutexGuard { mutex: self })
    } else {
        None
    }
}
```

**Comment by taiki-e** [comment]
[Unlike std mutex](https://doc.rust-lang.org/std/sync/enum.TryLockError.html#variants), there is only one reason why try_lock fails in futures' mutex (only `WouldBlock`), so I don't think Result is necessary.

std mutex:
```rust
    pub fn try_lock(&self) -> TryLockResult<MutexGuard<'_, T>> {
        unsafe {
            if self.inner.try_lock() { // if false, returns TryLockError::WouldBlock
                Ok(MutexGuard::new(self)?) // if fails, returns TryLockError::Poisoned
            } else {
                Err(TryLockError::WouldBlock)
            }
        }
    }
```

**Comment by seanmonstar** [comment]
Exactly, the difference is `futures::lock` doesn't use poisoning.
