### ISSUE TITLE
Mention std::sync in readme

### ISSUE THREAD

**Issue by casey** [rust-lang-nursery/futures-rs#283]
It might be worth mentioning in the readme the role of std::sync, how it relates to futures, and when to use one vs the other.

I'm not sure how common it might be, but I thought I needed futures for a task, when actually I just needed std::sync. I had a simple parallel computation I wanted to run, and std::sync::mpsc::channel was the right tool.

I started trying to figure out how to use futures, and was pretty confused when I ran into the concept of a task, and the fact that I couldn't do anything but a blocking `.wait()` on a future.

**Comment by cramertj** [comment]
I'd be happy to accept a PR here where it's unclear, but there's quite a bit of existing literature, such as the async book, which describe when asynchronous code is appropriate.
