### ISSUE TITLE
Inconsistency between `Stream::filter` and `Stream::skip_while`

### ISSUE THREAD

**Issue by troplin** [rust-lang-nursery/futures-rs#311]
The predicate of `Stream::filter` returns a plain `bool`, while the predicate of `skip_while` returns an `IntoFuture<Item=bool, Error=Self::Error>`.
I think this should be made consistent.

**Comment by alexcrichton** [comment]
Makes sense to me! I'll tag this for 0.2 so we can be sure to touch it up in the next major release.

**Comment by alexcrichton** [comment]
This landed in https://github.com/rust-lang-nursery/futures-rs/pull/728 for 0.2, so closing.
