### ISSUE TITLE
Consider renaming Stream::into_future -> Stream::next

### ISSUE THREAD

**Issue by carllerche** [rust-lang-nursery/futures-rs#315]
Whenever I use `Stream::into_future` I'm really trying to get the next value. It seems like next may be a better name?

**Comment by 46bit** [comment]
I'll chime in as liking this as well.

**Comment by cramertj** [comment]
I generally wouldn't expect `next` to move `self`. That is to say, I'm used to the convention established in the `Iterator` trait of having `next` take `&mut self`.

**Comment by Xion** [comment]
Agree with @cramertj . `next` is a mutator method, and having `Stream::next` consume it is unexpected. I wouldn't be opposed to _introducing_ `next(&mut self) -> Future<T>` but I'm not sure how much utility such a method would have.

If you want to rename `into_future`, I think `slice::split_first` is its closest analogue in the standard library, so calling it `split_first` seems natural.

**Comment by flosse** [comment]
It's a bit off-topic but I couldn't find an answer how to take one item out of a stream without consuming the stream. So I'm looking exactly for a method like `next(&mut self) -> Future<T>`!
How can I achieve that at the moment?

Here is my original question:
https://www.reddit.com/r/rust/comments/6v11os/hey_rustaceans_got_an_easy_question_ask_here/dm4c85h/

**Comment by alexcrichton** [comment]
@flosse that's unfortunately not easily done right now, but you can always [write your own combinator](https://github.com/mozilla-services/autopush/blob/07f5939bcd546074c52609ad9cc2800544fdb7e7/autopush_rs/src/client.rs#L295-L345) to achieve what you're thinking of

**Comment by aturon** [comment]
We should consider this now that we have `poll_next` -- it's a common thing to have `poll_foo` and `foo` variants, where the latter yields a future.

@cramertj thoughts?

**Comment by cramertj** [comment]
@aturon Yup, I think `next` makes sense.
