### ISSUE TITLE
Stream::filter_map should use IntoFuture on its closure

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/futures-rs#338]
Tagging for an 0.2 release to ensure we don't forget it. We're doing this everywhere else with `Stream`, so may as well be consistent.

**Comment by alkis** [comment]
Can we get a filter_map2 as a stop gap until 0.2 lands?

**Comment by alexcrichton** [comment]
For now I'd recommend vendoring a local extension trait/combinator, but if there's enough desire we could consider a new method!

**Comment by alexcrichton** [comment]
This landed in https://github.com/rust-lang-nursery/futures-rs/pull/726 for 0.2, so closing.
