### ISSUE TITLE
Yield combinator for futures

### ISSUE THREAD

**Issue by Stebalien** [rust-lang-nursery/futures-rs#353]
To avoid blocking for too long, it could be useful to have a yield combinator for futures. Specifically, one that returns `NotReady` once after the wrapped future completes and then returns the result on the next poll. For example, in:

```rust
let my_future = some_call()
    .yield()
    .and_then(do_second);
```

Even if `some_call` and `do_second` are actually synchronous, the `yield` call will force `my_future` to return `NotReady` after completing `some_call` and before running `do_second`.

**Comment by Stebalien** [comment]
Design question: Should this method yield after errors?

**Comment by drewhk** [comment]
`yield` is not a good name as it seems to be a reserved word?

bq. Design question: Should this method yield after errors?

I think usually it does not need to. It can be a flag though (my experiences from Akka Stream say that if there is a possibility to add a flag to control behavior then there *will* be people that need that flag :) ).

**Comment by Stebalien** [comment]
@drewhk we could solve both by providing `then_yield`, `and_yield`, and `or_yield` but adding three methods seems like a waste. I'm always wary of adding seldom used boolean flags because they're hard to remember (what does true mean? why is rust complaining about a missing parameter?). However, yielding on both errors and success cases (always) should be mostly harmless. I asked mostly because everything else seems to special case errors.

**Comment by drewhk** [comment]
> I'm always wary of adding seldom used boolean flags because they're hard to remember 

In my defense, I come from Scala where there are named and default arguments, and if I pass a boolean to a method like `method(false)` then my IDE shouts at me that I should write `method(theFlag = false)` :) I don't mind any version. 

> However, yielding on both errors and success cases (always) should be mostly harmless. 

I agree, let's reduce the confusion and simply treat them the same here.

**Comment by Stebalien** [comment]
>  my IDE shouts at me

Nice!

**Comment by alexcrichton** [comment]
Before we go too far down this road, is there a concrete use case for this in mind so far? I'm wary to try to solve scheduling issues too soon which end up just needing another overhaul down the line.

**Comment by drewhk** [comment]
I don't mind any particular implementation, but I have debugged fairness issues before, and they are not fun. I consider them the second worst kind of concurrency issues, right after memory visibility issues.

**Comment by Stebalien** [comment]
If by "concrete" you mean, will I use this now  then no. I mostly proposed this as a compliment to #352 (and in response to your comment there https://github.com/alexcrichton/futures-rs/pull/352#issuecomment-272551011). However, I agree that we might want to come up with a complete solution before proceeding.

**Comment by alexcrichton** [comment]
@Stebalien ok thanks for clarifying! I'd be inclined in that case to continue discussion on #352 before merging

**Comment by drewhk** [comment]
Well, and I need some help with that PR, mainly about what Sinks do in this picture, and I need to make it pass the PR validation.
