### ISSUE TITLE
Handle long-running, always-ready futures fairly

### ISSUE THREAD

**Issue by Stebalien** [rust-lang-nursery/futures-rs#354]
In #352, @drewhk introduced a yield combinator for streams as a way to to ensure fairness. As I understand it, the problem is that `my_stream().for_each(...)` will block until `my_stream()` returns `NotReady`. If `my_stream()` is always ready, it will block forever and never let anything else run.

**Ideas:**

1. @drewhk's proposal was to introduce a `yield_after(items)` combinator for streams. One would write `my_stream().yield_after(n_items).for_each(...)` and the `yield_after` combinator would force the stream to return `NotReady` after returning `n_items`. This way, the future returned by `my_stream().yield_after(n_items).for_each(...)` would return a `NotReady` after processing `n_items` and the scheduler would have the opportunity to schedule something else.

2. An alternative solution is to have `for_each` (and friends) return `NotReady` after every item.  Basically, as a rule, futures would always do as little work as possible and then let the scheduler decide whether or not you should do more work. This could be a performance issue due to extra bookkeeping (I'm mostly worried about potentially slow reads/writes of atomic flags) and might make it harder for the compiler to optimize loops.

3. Provide some sort of `task::should_yield()` function and check it before yielding as in solution (2). This could reduce some of the overhead.

4. Extend `Async` to include an `Async::Yield` state (in addition to either 2 or 3). This could be used to avoid the overhead of park/unpark but is a big breaking change and adds significant complexity.

5. Instead of 4,  implement `task::yield()` (#177) as a replacement for `park().unpark()`. Given that this guarantees that `unpark()` will be called from the task's thread, we could probably avoid the overhead of atomics described in (2).

6. Introduce a yield combinator for futures as described in #353. One would then write `my_stream().for_each(|item| { ...; futures::finished(()).then_yield() })` to force a yield after every item. IMO, for this particular use case, 1 is a better option (less cumbersome).

---

Thoughts? Other ideas?

**Comment by drewhk** [comment]
> @drewhk's proposal was to introduce a yield_after(items) combinator for streams.

I am not seriously proposing, I was just thinking about the problem, realized that I cannot solve it at the executor level, then on a sleepness night I realized that a combinator can do that, so I just sketched it up and submitted here :)

>  This could be a performance issue due to extra bookkeeping (I'm mostly worried about potentially slow reads/writes of atomic flags) 

Are atomics really needed? If you think about it, yielding only provides information to the current worker thread, which is exactly the same one that calls the poll in question. In other words the writer and reader thread are the same. You can even have a per-Task counter, you only need to make sure if the Task passes threads then the dequeuing/enqueueing has a proper barrier that safely publishes the previously written value to the next thread. I might be wrong, I am a newbie to this library and Rust, but I think this is doable without atomics being involved.

> Extend Async to include an Async::Yield state (in addition to either 2 or 3). This could be used to avoid the overhead of park/unpark but is a big breaking change and adds significant complexity.

It is important to keep it simple to write custom combinators. I think one of the things we got right in Akka Streams is its high flexibility and simplicity when it comes to extending it. If things are more complex than necessary than you miss out on potential contributors.

>  Given that this guarantees that unpark() will be called from the task's thread, we could probably avoid the overhead of atomics described in (2).

Ah, yes that is one I meant by not needing atomics above. Agreed.

**Comment by Stebalien** [comment]
> I am not seriously proposing, I was just thinking about the problem, realized that I cannot solve it at the executor level, then on a sleepness night I realized that a combinator can do that, so I just sketched it up and submitted here :)

Actually, now that I understand your use case, I think it's a good idea, just not a complete solution (which is why I submitted this issue).

**Comment by alexcrichton** [comment]
To me futures are just green threads in the sense that they're cooperatively scheduled. There's not really anything we can do about that and prevent you from throwing in a `loop` or some such.

We can always instrument I/O primitives and general standard primitives with context switch points, as well as offering a suite of yield-like abstractions, but I fear that this issue as-is basically cannot be solved without radically changing the design.

**Comment by drewhk** [comment]
> To me futures are just green threads in the sense that they're cooperatively scheduled. There's not really anything we can do about that and prevent you from throwing in a loop or some such.

While that is true, there is a whole spectrum here, not just black and white. Just because you cannot prevent one edge case that is not an argument for to not preventing other edge cases. In this case just because you cannot implement fully fair scheduling in userland it is not an argument for not improving the fairness in most of the cases. 

Of course one can argue that the current approach favors simplicity, which is a fair argument. The current yield operator approach favors simplicity and backwards compatibility for this exact reason.

**Comment by alexcrichton** [comment]
@drewhk yeah don't get me wrong I think we'll definitely grow methods of yielding. As stated, though, this issue seems to be like a request to solve this problem *without* requiring explicit code annotations. I would see something like that as "very unlikely to happen" at this point.

**Comment by Stebalien** [comment]
I filed this issue as a place to discuss potential solutions to the fairness problem as we now have (at least) 3 separate issues proposing solutions to different parts of the problem (#352, #353, #177). The ideas I posted in my first post were just ideas (I probably should have put them in a separate comment to make that clear).

Also, I'm not suggesting we (entirely<sup>&dagger;</sup>) fix this without explicit annotations. I was exploring ways to balance throughput with fairness (faster ways to yield and yielding only when necessary) and best practices (yield often).

<sup>&dagger;</sup> I am suggesting that we apply these best practices to some built-in combinators like `for_each`, `filter`, `fold`, etc.. Basically, futures that can potentially do unbounded (or lots of) work should consider yielding after each chunk of work, even if they're "built-in" futures. While this won't entirely fix the problem, it should make the programmer's life much easier.

**Comment by alexcrichton** [comment]
@Stebalien makes sense to me! That's definitely how I've been approaching this as well. We've considered in the past modifying the core combinators to have this sort of behavior by default as well, yeah. (particularly on streams)

**Comment by drewhk** [comment]
We are in full agreement then :)

**Comment by dylanede** [comment]
Has there been any progress on how to deal with this? I keep running into fairness problems.

**Comment by alexcrichton** [comment]
@dylanede nah not much has changed here, but can you detail a bit the problems that you're seeing? It'd be great for informing solutions here!

**Comment by dylanede** [comment]
Sure, the main case where this pops up for me is with mpsc queues that receive items at a high rate that are `for_each`ed over on a tokio event loop. Since the queue has almost always had a new item put into it by the time the `for_each` gets to re-polling, other work on the event loop gets starved, sometimes indefinitely. In my particular use case, allowing that other work to complete would indirectly reduce the rate of items going into the queue, so this isn't just a case of the queue filling up faster than it can ever be processed.

**Comment by drewhk** [comment]
You can still try the yield_after operator in my PR: https://github.com/alexcrichton/futures-rs/pull/352/files
It does not require any changes to futures-rs.

**Comment by alexcrichton** [comment]
Ah ok makes sense to me!

@dylanede does the stream that @drewhk mentioned work for you?

**Comment by dylanede** [comment]
Yes it probably would, but I've been using https://github.com/alexcrichton/futures-rs/pull/359 for the time being, which works well enough.

**Comment by alexcrichton** [comment]
Ok cool, just want to make sure that the "planned" recourse for this does indeed work for you.

**Comment by cramertj** [comment]
i'm not opposed to a combinator similar to the one proposed in #352. Otherwise, I don't think there's any more to be done here.
