### ISSUE TITLE
"reached the recursion limit during monomorphization (selection ambiguity)" with join_all()

### ISSUE THREAD

**Issue by dwrensha** [rust-lang-nursery/futures-rs#367]
I expect the following program to compile without error.

```rust
extern crate futures; // version 0.1.9
use futures::{Future, future};

fn main() {
    let _ = future::join_all(vec![
        future::lazy(|| {
            future::ok::<(),()>(()).join(
                future::ok(()).and_then(|()| {
                    future::ok(()).map(|_| ())
                })
            )
        })
    ]);
}
```

Instead, `rustc` (stable, beta, and nightly) gives me
```
error: reached the recursion limit during monomorphization (selection ambiguity)
```

This problem seems to be related to https://github.com/rust-lang/rust/issues/38033.

I am not sure whether this should be considered a rustc bug or a futures-rs bug. I think the problem could be sidestepped on the futures-rs side by making `join_all()`'s `I::Item` be an actual `Future` rather than an `IntoFuture`.

**Comment by alexcrichton** [comment]
What in the wrong is wrong with `join_all`?!

**Comment by alexcrichton** [comment]
I applied both https://github.com/alexcrichton/futures-rs/pull/286 locally and removed `IntoFuture` in the implementation of `JoinAll`, but it still hit the recursion limit :\

**Comment by dwrensha** [comment]
Closing, as this error no longer happens.
