### ISSUE TITLE
Bikeshedding: methods with names in common with `Result`

### ISSUE THREAD

**Issue by P-E-Meunier** [rust-lang-nursery/futures-rs#377]
I just chased a bug for quite some time, which could have been signaled by warnings, but wasn't, possibly because of the naming of methods in futures (or maybe because `join` accepts `IntoFuture` instead of just `Future`).

I have the following function:

```rust
struct Server(tokio_core::net::Incoming);
fn startup(…) -> Result<Server> {
   // setup my sockets.
   let s = …;
   Ok(Server(s.incoming()))
}
```

That function initializes a socket and returns a future accepting connections. Then I'd like to write a server with multiple such servers, listening on different ports, all with slightly different interfaces (because they come from different crates).

```rust
let first_server = startup().unwrap().map_err(Error::FirstServer);
let other_server = other_startup_function().map_err(Error::OtherServer);
event_loop.run(
   first_server
   .join(other_server)
)
```

The correct code uses `other_startup_function().unwrap().map_err(Error::OtherServer)`, but it wasn't easy to spot, and I specifically designed my types so that I could see a non-use of `Result`, which means I was definitely not expecting the problem to come from there.

**Comment by alexcrichton** [comment]
Oh man that is indeed tricky! On one hand I think we benefit from similar names to draw from previous experience in Rust, but on the other you're right in that they can be a footgun. 

I'm not really sure there's a great way to solve this :(

**Comment by P-E-Meunier** [comment]
I agree, and I actually liked the choice of similar names when that project was small enough and I was still learning tokio/futures.

Another solution is that `join` takes `Future` instead of `IntoFuture`, or remove the implementation of `IntoFuture` for `Result`. I wouldn't mind writing:

```rust
event_loop.run(
   first_server
   .join(other_server.into())
)
```

And the other way would have yielded an error, forcing me to deal with the `Result`.

Feel free to close if you think it's not appropriate.

**Comment by alexcrichton** [comment]
Removing `Result<T, E>: IntoFuture` I fear would lose *far* too much ergonomics to fly, but removing `IntoFuture` on `join` may be plausible. In general I like consistency with taking `IntoFuture` everywhere instead of just `F: Future` (as opposed to half somewhere half elsewhere). I think it's worth leaving open to discuss more though!

**Comment by aturon** [comment]
@cramertj did you end up looking at this in your 0.2 work?

**Comment by cramertj** [comment]
@aturon Nope. As discussed elsewhere, I think there are other changes we should make to join, and combining this one in with them makes sense to me.

**Comment by aturon** [comment]
I'm going to punt this to 0.3, where we're revising the relationship between `Future` and `Result`.

**Comment by bstrie** [comment]
Noting that this is one of the few listed blockers for a 0.3 release, what is the status here since the last update?

**Comment by cramertj** [comment]
I certainly hadn't planned any changes here. The revisions we did as part of the move to 0.3 split out all the `Result`-y methods onto `TryFutureExt`, where they live as `.map_ok` and `.map_err`. I think those are still wanted, and I don't think we should change them, but I'd love to hear about difficulties people are encountering when using them and confusion they may be causing!
