### ISSUE TITLE
Rename `poll_complete` to `poll_flush`

### ISSUE THREAD

**Issue by aturon** [rust-lang-nursery/futures-rs#379]
Clarify the semantics of `poll_complete` by renaming to `poll_flush`.

**Comment by alexcrichton** [comment]
With [`Sink::close`](https://github.com/alexcrichton/futures-rs/pull/404) we may also wish to consider `Sink::flush` instead of `Sink::poll_flush`

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang-nursery/futures-rs/pull/747
