### ISSUE TITLE
select_all for streams

### ISSUE THREAD

**Issue by rushmorem** [rust-lang-nursery/futures-rs#461]
It will be awesome to have `join_all` for streams as well.

**Comment by alexcrichton** [comment]
Just to make sure I understand, you mean something that basically takes a `Vec<Stream<T>>` and gives you back a `Stream<Vec<T>>`?

**Comment by rushmorem** [comment]
No. Something that takes a `Vec<Stream<T>>` and gives back a `Stream<T>`. Instead of waiting for one stream to finish before moving on to the next, the steams should all run concurrently so that the receiver can just pull values one at a time from whichever stream is ready.

**Comment by Stebalien** [comment]
Ah, you mean `select_all` (a streaming version of [`future::select_all`][https://docs.rs/futures/0.1.13/futures/future/fn.select_all.html]).

**Comment by rushmorem** [comment]
@Stebalien Ah, yes that one! Can we have it for streams?

**Comment by alexcrichton** [comment]
Thanks for the clarification @rushmorem!

I think this is definitely a plausible combinator to have for streams. We'll likely want an implementation similar to `futures_unordered` using unpark events to know precisely which stream needs to be polled.

**Comment by swizard0** [comment]
I've recently implemented such combinator on top of `Stream::select`: https://crates.io/crates/futures-stream-select-all 
You could use it as a temporary solution.

**Comment by 0xcaff** [comment]
This seems to be in 0.2.x versions but disabled in later versions. What's up with `select_all` for streams?

https://github.com/rust-lang-nursery/futures-rs/blob/d040a57521ca09d7eb162840bfb084d90d72db03/futures-util/src/stream/disabled/select_all.rs

**Comment by Nemo157** [comment]
At a guess it was just never fully updated for 0.3, I don't see any reason to not have the same basic API so a PR to re-add it would probably be accepted.

**Comment by taiki-e** [comment]
In 0.3, this seems to be currently implemented. https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.13/futures/stream/fn.select_all.html
