### ISSUE TITLE
Can sink be reused after `send_all`?

### ISSUE THREAD

**Issue by BusyJay** [rust-lang-nursery/futures-rs#462]
Hi, I notice that `SendAll` struct will call `close` method when polling, doesn't it mean that though `SendAll` will be resolved back to Sink eventually, but it can't be reused anymore? And I don't find any combinator except `SendAll` will call close under the hook. So if I want to close a sink asynchronously, do I have to either reimplement a Future or just use `SendAll`?

**Comment by rasendubi** [comment]
Actually, I was about to post the same issue.

I consider this to be a bug, as the documentation doesn't mention closing the Sink.
```
/// Future for the `Sink::send_all` combinator, which sends a stream of values
/// to a sink and then waits until the sink has fully flushed those values.
```
`Sink::send_all` docs as well:
```
A future that completes after the given stream has been fully processed into the sink, including flushing.

This future will drive the stream to keep producing items until it is exhausted, sending each item to the sink. It will complete once both the stream is exhausted, and the sink has fully processed and flushed all of the items sent to it.

Doing sink.send_all(stream) is roughly equivalent to stream.forward(sink).
```

Furthermore, `Stream::forward` closes Sink as well, so there is no a method to send all items without closing a Sink.

**Comment by alexcrichton** [comment]
Yes currently the `send_all` and `forward` functions are intended to send values and then close a sink. The sink is returned to reclaim resources from it (if possible).

Thanks for pointing out the docs bug @rasendubi! I'll go update those to make sure they're in sync.

**Comment by carllerche** [comment]
I was personally surprised that send_all and forward closed the Sink, however @alexcrichton explained to me that this was for backwards compatibility reasons. 

There should be a way to send a stream to a Sink without closing the Sink. What we need to figure out is how to expose the various permutations (to close and to not close) as well as deal with backwards compatibility in 0.1 and the transition to 0.2.

**Comment by rasendubi** [comment]
It would be also good to have a combinator that enqueues all the data but does not flush the sink. That's nice when the next future enqueues data as well, so it can start without waiting while the data is flushing.

**Comment by alexcrichton** [comment]
Out of curiosity, @BusyJay and @rasendubi mind commenting with your use cases for continual use of the sink after `send_all`?

**Comment by rasendubi** [comment]
My `Sink` is an USART interface, which practically never ends/stops (think of it as of stdout). I use `send_all` (modified to not flush and to not close the Sink) to send a welcome message, application logs, terminal prompt, command responses, etc.

**Comment by BusyJay** [comment]
Actually I don't need to reuse the sink at all. Just the interface confuses me, because from the name "send_all", the sink is expected to drain the stream but not close itself. I do need a method that drain the stream and close itself too, but not expected it's `send_all` until I look into its implementation.

**Comment by sfackler** [comment]
I would also like a method that doesn't shut down the sink - in my case I'm sending a sequence of messages to a backend, after which I'm waiting for a response.

**Comment by sfackler** [comment]
(The fact that close is called is *really* nonobvious in the docs, especially since `send` recommends `send_all` be used if you have more than one message)

**Comment by dbrgn** [comment]
Another use case here: I'm implementing a [SaltyRTC](https://saltyrtc.org/) client. The handshake protocol sometimes requires the client to send multiple messages in succession, and then to wait for a response again.

My current approach was to pass incoming messages to a handling function and to return a list of messages to be sent back from it. That list of messages should then be sent to the server, but without closing the sink.

Since `send_all` appears to close the sink, I'll have to find a workaround.

(PS: For some reason, [this example](https://github.com/saltyrtc/saltyrtc-client-rs/blob/develop/examples/wstest.rs) does not seem to close the sink when using `send_all`, it still blocks and waits for new messages. Why?)

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang-nursery/futures-rs/pull/745

**Comment by BusyJay** [comment]
So is there a method that works just like the old one?

**Comment by alexcrichton** [comment]
Not currently, no
