### ISSUE TITLE
CpuPool::spawn_stream

### ISSUE THREAD

**Issue by stepancheg** [rust-lang-nursery/futures-rs#470]
Implement `CpuPool::spawn_stream(Stream) -> Stream`.

**Comment by carllerche** [comment]
This issue is related to https://github.com/alexcrichton/futures-rs/pull/455.

On one hand, there could be a `background` variant on `Stream`. On the other, how does that impact buffering?

**Comment by alexcrichton** [comment]
Yeah I was thinking the same with the relation to #455, specifically adding a `spawn` method to the `mpsc` modules (sync and unsync). Another option is to add `mpsc::Sender::spawn` as a function, which allows control over buffering b/c you'd create the channel first.

**Comment by aturon** [comment]
Closing, this is no longer relevant with 0.2.
