### ISSUE TITLE
docs that steve wrote

### ISSUE THREAD

**Issue by carols10cents** [rust-lang-nursery/futures-rs#503]
@steveklabnik wrote [stuff about futures, mio, and tokio on reddit](https://www.reddit.com/r/rust/comments/6fjk0d/hey_rustaceans_got_an_easy_question_ask_here/dijanrb/?st=j3lqqx0r&sh=89d83948) and i think this could be used for useful docs so here you go! Let me know if I should move this to tokio or mio's repo....

---

To understand tokio, you need to understand its two major components:

## Futures

A future is a way of representing a computation as a value. What does that mean? Well, let's look at the Future trait:

```
pub trait Future {
    type Item;
    type Error;
    fn poll(&mut self) -> Poll<Self::Item, Self::Error>;
}
```

A Future has a single required function, poll, that returns either an Item or an Error. This is very similar to Result in the standard library. There's a difference, though: see how it returns a Poll, not a Result? Poll looks like this:

```
type Poll<T, E> = Result<Async<T>, E>;
```

And Async looks like this:

```
pub enum Async<T> {
    Ready(T),
    NotReady,
}
```

Putting it together, this means that Poll can be one of three things:

1.    Ok(Async::Ready(Item)): this state means "hey, the computation has completed, here's the result."
2.    Ok(Async::NotReady) is "hey, I'm still working on it, come back later"
3.    Err(Error) means "this computation has failed, here's the error"

The Asyc bit is really the big difference; with Result, you'd write a function with this kind of signature:

```
fn do_something() -> Result<Item, Error>
```

In this case, do_something must perform the entire computation before it returns. The only two possible states are "succeed" and "fail".

But with poll...

```
fn poll(&mut self) -> Poll<Item, Error>
```

the signature looks very similar, except that the Ok state is split into two: done, and not yet done.

What does that buy us? Asynchronicity! We can call poll and it will not block. It always returns very quickly, either with a "hey not done" or "here's your answer." A particular future can do work in the background, and it won't be blocking.

Futhermore, now that we have a value to represent our computation, we can combine computations. So for example, imagine we had a future that fetches something from the network. Afterwards, we want to use a future that does some processing on the result. We can use combinator methods to combine these futures

```
fetch_from_network.and_then(do_processing)
```

The result of and_then is to return another Future, so now we've combined two individual futures into a larger future. We can call poll on that future to drive the entire computation, and if the first future fails, the whole computation will fail. And it's all asynchronous.

Note that nothing here has anything to do with IO, specifically. It's a way of modeling computations as values.

This is the core of the Futures library, but there's a lot of other useful stuff in there.

## mio

Mio is a wrapper around epoll, kqueue, and IOCP. The tricky bit is that IOCP has a fundamentally different model than epoll and kqueue, so there's some code to adapt it so that it presents one model. Mio lets you interface with your operating system to do IO in a non-blocking way. But operating systems are very low-level, and so are their interfaces. So mio is also low-level, as it's trying to be a no-overhead wrapper.

Being low level means that it's a bit hard to use. Which brings us to...

## Tokio

Tokio is best summed up as "using futures to make Mio easier to use." It takes the general futures mechanism and uses it to do non-blocking IO with mio, but in a way that (hopefully) is easier to understand than mio itself. It also provides interfaces for higher-level networking concepts, such as "this is a frame", stuff like that, that matters when you're implementing a protocol.

Random developers will learn Futures, mostly, and have to worry less about Tokio and mio. They're more relevant for people who are actually implementing said network protocols than for the users of them. But since the interface to those protocols is a future, a good understanding of working with futures is useful for working with libraries on top of tokio.

**Comment by steveklabnik** [comment]
yup; i know the tokio team was interested in re-doing their docs, so I didn't want to try to integrate into something that's changing a ton

**Comment by alexcrichton** [comment]
💖

**Comment by alexcrichton** [comment]
I'm going to close this for now in favor of https://github.com/aturon/apr/blob/master/src/SUMMARY.md which I think should hopefully help quite a bit in this space!
