### ISSUE TITLE
Deprecate old Stream::concat

### ISSUE THREAD

**Issue by srijs** [rust-lang-nursery/futures-rs#532]
Just creating this so we can track it for the 0.2 clean-up.

Deprecate the current `Stream::concat` method and rename `Stream::concat2` to `Stream::concat`.

**Comment by srijs** [comment]
@alexcrichton could you add the 0.2-cleanup label here?

**Comment by alexcrichton** [comment]
Certainly!

**Comment by alexcrichton** [comment]
This was done in https://github.com/rust-lang-nursery/futures-rs/pull/731 for 0.2, so closing
