### ISSUE TITLE
.poll() crashes on CpuFuture in most basic use ... 

### ISSUE THREAD

**Issue by przygienda** [rust-lang-nursery/futures-rs#534]
adding a simple test setup 

```
use futures_cpupool::CpuPool;

lazy_static! {
static ref CPU_POOL : CpuPool = Builder::new()
			.pool_size(20)
			.create();
}

#[test]
	fn simple_cpu_feature_poll() {
		let mut f = CPU_POOL.spawn(
			ok::<_,()>( 5 )
			.map(|v| v)
			.fuse()
		);

		f.poll();
	}
```

leads to 

```
thread 'bounded_futures_queue::tests::simple_cpu_feature_poll' panicked at 'no Task is currently running', src/libcore/option.rs:823:4
stack backtrace:
   0:        0x10722ac53 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::hb2e4589b48ff3268
   1:        0x10722caa1 - std::panicking::default_hook::{{closure}}::h5febd04eb069ba4a
   2:        0x10722c70d - std::panicking::default_hook::hbdc079c4ecdaaf61
   3:        0x10722ec82 - std::panicking::rust_panic_with_hook::he5c8309538974404
   4:        0x10722eb64 - std::panicking::begin_panic_new::h6ebc5b5819365d9e
   5:        0x10722ea92 - std::panicking::begin_panic_fmt::h58b23d554103b953
   6:        0x10722e9fa - rust_begin_unwind
   7:        0x1072564f3 - core::panicking::panic_fmt::hb2cc2ea3b36a7d6b
   8:        0x10725655d - core::option::expect_failed::hf92abd6cd8a21f8c
   9:        0x1071a95b5 - <core::option::Option<T>>::expect::h8e46674857d4f935
  10:        0x1071b2efa - futures::task_impl::with::h807d77a7ad871ffc
  11:        0x1071b2fd3 - futures::task_impl::current::h13bb5641c8405b29
  12:        0x10711abfd - <futures::sync::oneshot::Inner<T>>::recv::h83a9314f13de8a8e
  13:        0x10715600b - <futures::sync::oneshot::Receiver<T> as futures::future::Future>::poll::hf23e56e79b888350
  14:        0x10715806f - <futures_cpupool::CpuFuture<T, E> as futures::future::Future>::poll::hb6de413e4109c69a
  15:        0x10715c8b3 - thrift_service::bounded_futures_queue::tests::simple_cpu_feature_poll::hd8ffb71dfd77c416
  16:        0x1071f5271 - <F as test::FnBox<T>>::call_box::h322568d773dbcd38
  17:        0x10722fddc - __rust_maybe_catch_panic
  18:        0x1071e45ba - std::sys_common::backtrace::__rust_begin_short_backtrace::hb3c75d488c8d37b3
  19:        0x1071e5337 - std::panicking::try::do_call::hdf54b51caff001ad
  20:        0x10722fddc - __rust_maybe_catch_panic
  21:        0x1071edfb3 - <F as alloc::boxed::FnBox<A>>::call_box::hf25926b8139a1dcf
  22:        0x10722bf5b - std::sys::imp::thread::Thread::new::thread_start::h3a95850d89644972
  23:     0x7fff9b54199c - _pthread_body
  24:     0x7fff9b541919 - _pthread_start
test bounded_futures_queue::tests::simple_cpu_feature_poll ... FAILED
```

**Comment by jimmycuadra** [comment]
You're not intended to call `poll` directly. That's called by the task executor. Try calling `wait` instead.

**Comment by alexcrichton** [comment]
Ah yes here the panic message is correct in that you need to set up a `Task` or otherwise `spawn` the future if you intend to call `poll`, the [`poll` documentation](https://docs.rs/futures/0.1.14/futures/future/trait.Future.html#tymethod.poll) should have some more information as well.

**Comment by przygienda** [comment]
Alex, I have no issue with poll() not "being supposed to call" but then I suggest to either remove it as 

```
pub fn 
```

or _at_ minimum document what is the `magic` call necessary for it to work such as in case of CpuFuture. 

I intended to do `.forget()` basically but all the documentation indicated that .poll() is just fine to call and get an Async::NotReady and so on ... 

.forget() is asymmetric for CpuFuture and with that hard to "understand" or find. 

I suggest to not just close this defect but give it a thought what the strategy is here so the API doesn't fall apart in non-orthogonality over time. 

Overall, great package and vastly superior to normal threadpools since I can build async closures without fighting lifetimes of stuff excessively given the nice Source/Sink semantics, I'm using it now with `.forget` and that works well albeit I wished for more stats obtainable from the futures core rather than having my own atomic counters and fiddle with those. E.g. tasks completed, tasks executing, tasks waiting and such. 

Thanks for the great work ...

**Comment by alexcrichton** [comment]
Oh it's sort of subtle here in that `poll` is the building block for the entire crate. It's definitely intended to be called in *some* situations, but not others. Spawning a future (e.g. on a thread pool) is an example of where `poll` shouldn't be called, but if you're implementing a future (e.g. `impl Future for MyType`) then calling `poll` is totally normal.

If you're looking for a crate to spawn futures though I might also recommend taking a look at rayon, which is likely going to be more efficient (and powerful!) than futures-cpupool

**Comment by przygienda** [comment]
I use rayon very heavily but it doesn't have an asynchronous threadpool (well, only on unstable and it has some many exclamation marks I stay away from it ;-) and even then it looks like it will struggle with lifetimes. Your  ok::<_,_>::(  myvalues ).map( ... ) gives me the possiblity to run closures with my own parametrization whereas all the other threadpools and so on make a hash of a  'static Fn() -> () assumption that forces me to fiddle with egregious static mut or whatever not ... I don't need tons performance, I'm running a couple tens requiests/sec tcp-services server and for that your stuff works great. Plus, I can do thinks like takin in a Future and just piggy-back something in the server code on it and so on ... Very neat ...

**Comment by przygienda** [comment]
And yeah, I definitely recommend to put some heavy 'caution' signs on the poll doc and roughly outline when it's leggit to call and when not. Your 'panics' catch things nicely but without reading tons source they're cryptic and don't help to understand WHAT needs to be done for poll to be legal.

**Comment by alexcrichton** [comment]
Ok, seems good to reopen as a docs issue!

**Comment by alexcrichton** [comment]
I believe once https://github.com/rust-lang-nursery/futures-rfcs/blob/master/task-context.md is fully implemented this will effectively become self-documenting so I'm going to close
