### ISSUE TITLE
Peekable is missing inner Stream accessors

### ISSUE THREAD

**Issue by farnz** [rust-lang-nursery/futures-rs#573]
Most concrete stream types (Fuse for example) provide get_ref, get_mut, and into_inner functions to let you access the inner Stream. Peekable does not, which means that there's no good way to use something that's Peekable<Fuse<_>>, as you cannot access the Fuse<...> methods from the Peekable outer layer.

The implementation will be slightly different to other concrete stream types, as Peekable adds its own Fuse layer in the middle, which you'll probably want to skip as an implementation detail.

**Comment by alexcrichton** [comment]
I think when these were originally added I just wasn't 100% sure what to do wrt the buffered item, but I think it's fine to add the standard accessors to the stream regardless.
