### ISSUE TITLE
Notify tasks rather than futures

### ISSUE THREAD

**Issue by Diggsey** [rust-lang-nursery/futures-rs#594]
Apologies if this has been discussed before, but I couldn't find a related issue.

In order to support an efficient implementation of `FuturesUnordered`, `task.notify()` notifies a future rather than a task (ie. a leaf node or sub-tree in the tree of futures comprising a single task). This avoids the implementation having to poll *all* of the child futures when a `FuturesUnordered` is polled, and is necessary for good performance.

I think it would be worth considering a simpler implementation:
- Notify would be changed to just notify a task, no extra information would be tracked
- `FuturesUnordered` would be changed to spawn its child futures as new tasks
- When a `FuturesUnordered` is dropped, it would cancel its child futures

The disadvantages:
- This requires the ability to spawn new tasks onto the current executor.

The advantages:
- Reduce updates to the "current task" thread local
- Simplify notification machinery - the complications around `FuturesUnordered` are often glossed over, which I think is the source of many complaints about "magic" in the library.
- Reduce number of `poll()` calls - if a `FuturesUnordered` is used at the bottom of a nested chain of futures, *all* of the parent futures must be polled every time any one of the child futures needs re-polling. By flattening the child futures into their own tasks, the parents only need to be re-polled when a child future actually completes (ie. it's optimal).
- Notifications are more efficient: the executor is notified about a task, and that's it, no need to perform work for each `FuturesUnordered` in the chain.

A possible objection is the allocation overhead of spawning new tasks. I believe this can be avoided by an improvement to the executor design. By using an `AnyMap` storing `Vec<TaskT>` for each task type, the executor can eliminate allocations for task types which have previously been spawned onto the reactor. This is a common case anyway, but is *always* the case for `FuturesUnordered`.

**Comment by carllerche** [comment]
Thanks for the issue. I think there are some points that require some clarification.

> Notify would be changed to just notify a task, no extra information would be tracked

Notify already only notifies a task.

> When a `FuturesUnordered` is dropped, it would cancel its child futures

This is already true.

Re: disadvantages

> This requires the ability to spawn new tasks onto the current executor.

This is not simple. What type of future does the current executor support spawning? Is it `Sync`? is it `Send`? is it `'static'? Is it a fixed type? Is dynamic dispatch required? Do you use trait objects? etc... The current executor might only support `Foo` typed futures, but the `FuturesUnordered` contains `Bar` typed futures. How do you spawn a bar onto a foo? Does that mean you box all futures? Ok, trait objects... but what type? Are the futures `Send`? Are they `'static`? I'm not sure how this can all fit together. Could you elaborate a bit.

To clarify, I read your comment on `AnyMap`, however that just handles reducing allocations (though, at what cost? I wonder if allocations would be more efficient here. We would need benchmarks). I'm specifically wondering how to handle executor limitations.

Re: advantages

> Reduce updates to the "current task" thread local

What is an update to the current task?

> Simplify notification machinery

I don't understand how this simplifies any notification machinery. You are proposing that you can only notify tasks, but `FuturesUnordered` contains tasks? Or do you have an alternate definition of task? It might be helpful if you could formally define what you mean by task.

> Reduce number of poll() calls 

Do you have specific examples of this?

> Notifications are more efficient

If we are going to be talking about efficiency, we should have some specific benchmarks that we can use as an anchor. Maybe you could recommend recommend something that provides good coverage of real world scenarios?

**Comment by Diggsey** [comment]
> Notify already only notifies a task.

Ah I suppose I may have a slightly different understanding of the terminology: I understood a task to be the entire tree of futures, ie. the root thing that is polled directly by the executor, and everything below it.

Would "task" and "sub-task" be a better description?

> What is an update to the current task?

When a `FuturesUnordered` is polled, it replaces the current task with a sub-task before polling each child future:
https://github.com/alexcrichton/futures-rs/blob/master/src/stream/futures_unordered.rs#L373

> Notify already only notifies a task.

OK, but the implementation for the sub-tasks that `FuturesUnordered` creates must recursively notify the parent task, correct?
https://github.com/alexcrichton/futures-rs/blob/master/src/stream/futures_unordered.rs#L592

> Do you have specific examples of this?

If sub-tasks were instead spawned to the executor, then the parent task need not be re-polled until a child task actually completes, so really *any* usage of `FuturesUnordered` is an example where the number of polls would be reduced.

The most valuable cases would be when a `FuturesUnordered` is used deeply nested inside a tree of futures, since the number of polls would correspond to the depth of the tree multiplied by the number of polls an average child takes to complete, multiplied by the total number of children.

> If we are going to be talking about efficiency, we should have some specific benchmarks that we can use as an anchor.

Doing less work is usually a good indication of improved efficiency. At the moment when a subtask is notified, it most also notify its parent tasks, whereas if the set of tasks is flattened, this would not be the case. The most realistic benchmark would be to take a decent sized program using futures and measure the amount of time spent in `task::notify()` before and after the change.

> I don't understand how this simplifies any notification machinery. You are proposing that you can only notify tasks, but FuturesUnordered contains tasks?

Conceptually, it would contain futures of the result of spawned tasks, not tasks themselves. Implementation-wise it would probably be better to create an mpsc queue, and spawn child tasks which push their result onto the queue when they complete. The `FuturesUnordered` would be a simple wrapper around a `Receiver`, plus some extra logic to cancel the child tasks when dropped.

> This is not simple. What type of future does the current executor support spawning?

By virtue of the fact that the concrete child futures are part of the type of `FuturesUnordered`, I believe most of these constraints are already guaranteed. ie. if the child future was not `Send`, then the `FuturesUnordered` would not be `Send`.

There's still a question around how you encode that in the type system while minimising the amount of any unsafe code required. Personally I feel this is yet another case where taking the current task as a parameter rather than via a thread-local has merits, since in that case the spawn functionality can be exposed via the current task, and constraints can be placed on it, eg. `where ChildFuture: Spawnable<TaskT>`.

**Comment by Diggsey** [comment]
Also, I should add that I consider any performance improvements to be a bonus - the primary motivating factor for is that I think it provides a conceptually simpler and more familiar model for futures.

Secondary factors are simplifying the *implementation* of futures, reducing unsafe code, and centralising the actual "task scheduling" into the executor: for example, if a `FuturesUnordered` were spawned to a thread pool, its children could be driven to completion in parallel.

**Comment by cramertj** [comment]
> I think it provides a conceptually simpler and more familiar model for futures.

This change shouldn't actually affect the external API of `FuturesUnordered` at all, should it? I think it makes sense for `FuturesUnordered` to be opaque the the end-user.

**Comment by Diggsey** [comment]
@aturon Based on your recent blog post, it looks like futures 0.2 is actually moving in a direction that is particularly compatible with this feature request!

Notably, task contexts are gaining the ability to spawn new child tasks, which is the only "difficult" part to implementing this feature.

**Comment by carllerche** [comment]
AFAIK, nothing has actually changed except the task context is threaded through instead of accessed via thread-local?

**Comment by Diggsey** [comment]
@carllerche http://rust-lang-nursery.github.io/futures-rs/futures/task/struct.Context.html#method.spawn

**Comment by cramertj** [comment]
This is all quite different now.
