### ISSUE TITLE
Sink::send_all on error should provide stream or sink back

### ISSUE THREAD

**Issue by jpastuszek** [rust-lang-nursery/futures-rs#602]
Currently if `send_all` fails we loose stream and sink regardless winch one failed.
What would be nice is instead of mushing all errors to `Sink::SinkError` it would return and enum with `(Stream::Error, Sink)` or `(Sink::SinkError, Stream)` so we can recover the one that did not fail.

My current use case is sending data from a pipe (stream) to channel (`Sender` sink) and I want to keep reading the pipe if other end of the channel (`Receiver`) gets closed but I get `SendError<pipe item>` only and my pipe stream gets dropped along with the sink.

Is there any workaround currently for that so I don't have to reopen the pipe after receiver end got closed?

**Comment by alexcrichton** [comment]
Thanks for the report! One possible workaround for now at least is you can vendor an implementation of the combinator and customize its behavior. I'm somewhat hesitant to change the return type here though as it'd make it much less ergonomic to use in the common case... Maybe we could provide both?

**Comment by jpastuszek** [comment]
Yeah I think you could have one with enum and implement the current one on top of it by mapping it to `SinkError` with `From`.

For now I found a work around using `fold()` and `Option<Sender<_>>` like this:
```rust
    handle.spawn(
        pipe
            .and_then(|pipe| FramedRead::new(pipe, tokio_file_unix::DelimCodec(tokio_file_unix::Newline))
            .and_then(|line| String::from_utf8(line)
                .map_err(|_utf8_error| io::Error::new(io::ErrorKind::InvalidInput, "non-UTF8 data in pipe")))
            .fold(Some(sender), move |sender, line| {
                sender
                    .map(|sender| sender.send(line))
                    // somehow I need this to get Option<Send<Sender<String>>> treated as Future for or_else()
                    .map_err(|o| o)
                    // eat the SendError and type it to io::Error
                    .or_else(|_send_error| future::ok::<_, io::Error>(None))
            })
            .map(|_| ()) // reached EOF - drop sender
        )
        .map_err(|error| panic!("error while reading lines from pipe: {}", error))
    );
```

**Comment by alexcrichton** [comment]
It's true yeah that we can use from conversions, but it tends to be somewhat unergonomic to actually leverage unfortunately :(

**Comment by carllerche** [comment]
@sfackler did something like this for streams: https://github.com/sfackler/futures-state-stream

**Comment by cramertj** [comment]
`send_all` now takes `&mut self`, so this is done.
