### ISSUE TITLE
RFC - Rename types to avoid confusion

### ISSUE THREAD

**Issue by yazaddaruvala** [rust-lang-nursery/futures-rs#612]
Edit: After some discussion, I've better formulated my point. It may be better to start reading at [this comment](https://github.com/rust-lang-nursery/futures-rs/issues/612#issuecomment-363212079).

Original:
Not understanding you need to execute a Future is such a common confusion. This might stem from the fact that `Future`s in other languages are promises that a value will show up later. i.e. as soon as the Future type is created, you expect a value to show up later. Maybe there should be a bit of renaming, to avoid this confusion?

Current -> Proposed
`Future` -> `TaskBuilder`
`Reactor` -> `TaskRunner`
`Task` -> `Task`
`Future` -> `TaskHandle`

A TaskBuilder is a collection of closures/structs which create the state machine for a Task. A TaskRunner creates a Task to execute a TaskBuilder (and its entire state machine inside the TaskRunner's thread). However, Tasks are an internal construct of the runner, so the TaskRunner should output a TaskHandle. TaskHandles are poll-able, and can chain closures, exactly like today's Futures.

Compared to today, only the names would be different (I'm open to other names as well), but it seems to me there should be a lot less confusion around the whole async task system.

Future could then be written anew as an ergonomic sibling for TaskHandle, i.e. a Condvar around the result of the Task so that Futures are similar to every other language which has them.

This would mean that the async task system is identical to today, for people who need the performance and flexibility but Futures would be more ergonomic for most common usecases.

It is likely too late in the story to change these names, but thoughts?

**Comment by alexcrichton** [comment]
Thanks for the report! Have you seen tokio-rs/tokio-rfcs#3? Would that solve the problems you're worried about here?

**Comment by yazaddaruvala** [comment]
Sorry, for the slow response. While that RFC definitely helps the story as a whole, I don't think it relates to my point.

Very succinctly, the implementation of "Futures" in this crate and as such Rust, is very unique. Should we make the vocabulary unique as well? (examples in my original post)

To elaborate a bit more, people from other languages are familiar with the way a "Future" works. While it is not an ideal implementation, a "Future" takes a callback and runs it once a value exists. This crate challenging that familiarity is causing unneeded friction. Additionally, in no other language does the Futures concept also have this "task api" concept, and especially given the "task api" is hidden (for good reason), it ends up being very jarring to realize that it exists and is arguably  understanding it is crucial to the use of Futures, which should have been a familiar concept.

Now, as you are very well aware, for performance reasons, using the familiar implementation of Futures is not an option. As a result, other than extensive documentation and tutoring, the only other thing we might be able to do to improve this situation is change the vocabulary. Thoughts?

P.S. I also have other points but unless we are on the same page about this those would just be noise.

**Comment by alexcrichton** [comment]
It's a good point that this library can be a bit jarring with preconceived notions! I disagree though that renaming the types would fix much, though. I think we might achieve some success in that people won't automatically think of callback-based-futures but I think we'd lose a lot from having odd naming and no connection to prior art. Fundamentally we're doing the same thing as callback-based futures, the runtime is just a bit different with this crate.

In that sense I think this is an excellent opportunity to bolster the documentation and of course clarify futures especially from a callback-based perspective (explicitly compare and contrast them). I don't really see a future where the `Future` trait is called something else though.

**Comment by yazaddaruvala** [comment]
I agree, it would be kinda awkward to not have `Future`s in Rust. However, that still leaves a few other concerns with the name.

In prior art, its not just that futures have callbacks but also that futures are eagerly evaluated. That means without polling for it, i.e. "running it", the IO has begun and the future will eventually have a value show up (unless canceled). Rust's futures diverge from the norm here as well, *sometimes*. Sometimes, Rust's Futures are lazily evaluated, which is different than most commonly used Futures. But most importantly it seems Rust hasn't made any distinction between eager and lazy Futures, or read-only or mutable futures. The only way to know is to read the implementation.

Futures can still use the poll interface but be eagerly evaluated. i.e. It would be really nice to have Future be the output of the Task system, rather than be the input. We would call the input something different, eg. `FutureBuilder`, `Promise[Builder]`, `Task[Builder]`. It provides a good distinction for when you should run a future, and when that future just represents an incoming value.

In other common uses of Futures, you should never need to spawn a Future i.e. `thread::spawn_task(future)`[1].
Something like `let future = thread::spawn_task(task_builder)`[2] is a lot more familiar.

It might also be worth re-reading [this wiki](https://en.wikipedia.org/wiki/Futures_and_promises). Even if colloquially we don't explicitly differentiate, there seems to be this implicit distinction, a growing consensus (in the documentation like that wiki, but also different language implementations), between a Future, and the way it gets set. More and more the most common definition for a Future is an eagerly evaluated, read-only view. Maybe use a different word from the wiki to satisfy the prior art constraint for lazily evaluated "futures"? What are your thoughts around a distinction in this regard?

[1] Example taken from the [the tokio rfc](https://github.com/tokio-rs/tokio-rfcs/pull/3) but `copy(...).then(...)` has been replaced with a variable.
[2] `task_builder` could be replaced with other structs or vocabulary: `task`, `future_builder`, etc.

**Comment by alexcrichton** [comment]
Hm ok well in any case this is a *huge* change to completely rename everything and move away from the term "future" entirely. We can't really decided on a topic like this based purely on discussion in this issue, it will need much broader consensus such as an RFC in the tokio-rfcs repo or at least an internal/users thread.

**Comment by yazaddaruvala** [comment]
I just figured since this is about Futures, but if Tokio RFC is more appropriate I'm happy to do that (FYI, I don't know how to write a real RFC but I'd try).

Meanwhile, I agree that changing all of the names at this point is way too big a change. In some perfect world with infinite time, this better vocabulary might also help inform better struct and trait names, but you're right this part should be de-emphasized.

I'm wondering if only to to better write the documentation, there be a brainstorming thread to better understand where and why the current vocabulary is lacking intuition, and what a more intuitive vocabulary might look like. Would such a thing still be considered an RFC?

**Comment by stuhood** [comment]
> It might also be worth re-reading this wiki.

> In prior art, its not just that futures have callbacks but also that futures are eagerly evaluated. 

With regard to reading https://en.wikipedia.org/wiki/Futures_and_promises ... the section on "Evaluation Strategy" explicitly indicates that lazy vs eager is an implementation choice. Being lazy does not mean that something is not a future.

**Comment by yazaddaruvala** [comment]
@stuhood you're right. Two thoughts:

1. Even though technically, lazy evaluated Futures can exist. Most uses of Futures are eager and it is what users of Futures have come to expect.

2. Its awkward that there is no way to tell if a Future in Rust is eager or lazy (unless I read through the implementation). I'm not settled on any particular solution, we could change all the names, or just use `Future` and `LazyFuture`, or some third or fourth approach, I really don't know. But not distinguishing between them is confusing.

Maybe I started off this thread poorly. I usually don't like pointing out a problem unless I have a suggestion. There is clearly a problem and people are genuinely confused by Rust's async story. If it would help I'm happy to take back my suggested solution and just focus on identifying and clarifying the problem.

@alexcrichton do you think it might be better for me to create a thread in the Tokio repo in the vein of: "What about Rust's async story confuses you, or you felt took you by surprise?"

**Comment by alexcrichton** [comment]
@yazaddaruvala it may be best to hold off on that for now, I know @aturon is working on a "async book" for Rust which goes in great detail about many of the Tokio/futures concepts and is squarely aimed at solving most of the confusion. I think it'd be best to take a look at the book (when it's ready) and have a discussion around that for what's missing.

**Comment by yazaddaruvala** [comment]
Just a summary of what I put into the "Futures 0.2" issue, but is also relevant here.

If you're creating a library, this is less applicable, but when writing web services:

```rust
// Its not clear if we need to spawn these futures.
let from_table_one: Future<...> = self.database.call(...);
let from_table_two: Future<...> = self.database.call(...);

// Has the database client has already abstracted away the need to drive these futures?
// or is it the users responsibility? Each client might make a different decision for style/ergonomics.
pool.spawn(from_table_one);
pool.spawn(from_table_two);

await!(from_table_one);
await!(from_table_two);
```


```rust
// Very clear that we need to spawn these futures.
let from_table_one: LazyFuture<...> = self.database.call(...);
let from_table_two: LazyFuture<...> = self.database.call(...);

pool.spawn(from_table_one);
pool.spawn(from_table_two);

 // Ideally, we would get a compile time error if we await an un-spawned future
await!(from_table_one);
await!(from_table_two);
```

```rust
// Very clear that we need to spawn these futures.
let from_table_one: LazyFuture<...> = self.database.call(...);
let from_table_two: LazyFuture<...> = self.database.call(...);

let from_table_one: EagerFuture<...> = pool.spawn(from_table_one);
let from_table_two: EagerFuture<...> = pool.spawn(from_table_two);

// Compile time checks to ensure this will not cause the thread to wait indefinitely
await!(from_table_one); // i.e. await can only take an `EagerFuture`
await!(from_table_two);
```

**Comment by aturon** [comment]
I'm going to close this out; at this point, the naming in the library is pretty well settled.

**Comment by yazaddaruvala** [comment]
@aturon I'm just curious about this mindset.

Even in [the book you're writing](https://aturon.github.io/apr/task-model/real/tasks.html), the first concept that is introduced is a `Task`. Tasks make up the first whole chapter. Even in the chapter about `Future`s the word 'task' occurs as frequently as the word 'future'.

Why resign to stick with names which require the need for documentation, when we could brainstorm names which might be intuitive?

If/When needed, we can always re-introduce the concept of Futures into Rust in a way which conforms to other languages rather than diverges. For example, look at C++'s [future](http://en.cppreference.com/w/cpp/thread/future), and how it is different from [async](http://en.cppreference.com/w/cpp/thread/async). The simplest way to describe how Future's are used in other languages (at-least C++ and Java) are, that they are the result of `executor.execute(task)`.

While inconvenient for the current ecosystem, shouldn't we at least explore making this library more intuitive?
