### ISSUE TITLE
impl Stream for future::Either

### ISSUE THREAD

**Issue by Arnavion** [rust-lang-nursery/futures-rs#614]
For code that returns one of multiple `Stream`s it'd be nice to have `future::Either` also impl `Stream`.

```rust
fn foo() -> impl Stream {
    let v = match some_result {
        Ok(v) => v,
        Err(err) => return Either::A(stream::once(Err(err))),
    };

    return Either::B(some_stream(v));
}
```

**Comment by alexcrichton** [comment]
Sounds like a good idea to me!

**Comment by alexcrichton** [comment]
Added in https://github.com/rust-lang-nursery/futures-rs/pull/756

**Comment by tekjar** [comment]
Hi. Can this be backported to 0.1 to as well? benefits tokio users

**Comment by Kixunil** [comment]
@tekjar I've cherry picked it and made #1682

**Comment by tekjar** [comment]
Thanks @Kixunil
