### ISSUE TITLE
`enter` shouldn't return an `Option`

### ISSUE THREAD

**Issue by aturon** [rust-lang-nursery/futures-rs#651]
Currently the `enter` function returns an option, rather than panicking as per the RFC. It's unclear why this change was made, but in addition, `Option` does not provide the `must_use` lint, making it easy to accidentally drop the RAII guard.

What's the rationale?

**Comment by aturon** [comment]
cc @carllerche

**Comment by carllerche** [comment]
The reason is two fold:

* There is no way to check if currently in an executor context.
* The `enter` panic error message is generic and opaque. By returning `Option`, each executor can customize the error message.

I'm open to other proposals that address these two points.

**Comment by aturon** [comment]
I don't have a strong preference between a panicking API or not, but the `must_use` issue is significant; we should at least change to `Result`.

I'm curious if you have use cases in mind for checking if already in a context?

**Comment by carllerche** [comment]
Up until now, it has mostly been to provide improved panic messages. I would be fine having `enter` not return `Option` if there was also a way to check if currently in an executor context.

Again, up until now it has only been to provide improved error message. i.e., something better than "trying to enter an execution context while already in an executor context". That said, it seems obviously good to have some way to check if a function will panic before calling it.

**Comment by alexcrichton** [comment]
An API that returns an option or a result seems very easy to misuse. For example you could do something like:

```rust
let _guard = executor::enter();
```

Here the unused result lint won't trigger and you don't actually know if it succeeded or not. This seems like a case similar to `RefCell` where 90% of the time you want a panic, so we'd have two methods (if necessary), an `enter` and a `try_enter` where `enter` always panics.

**Comment by aturon** [comment]
Right, `enter` and `try_enter` are more idiomatic (from `std` anyway), but that wouldn't address the panic message issue. That said, I don't fully grok what the executors are going to say that's so much more clear than a generic "You tried to run an executor in a context where one was already running."

**Comment by carllerche** [comment]
I would say that `You cannot call future::Blocking::wait() while on a future executor` is more descriptive.

**Comment by aturon** [comment]
@carllerche Agreed.

Let's compromise and change to `Result`?

**Comment by carllerche** [comment]
To be clear, as I mentioned above, I am fine havin `enter` return `Enter` and panic if re-entering, but in that case, I would like a fn to check if currently entered as well (like `Enter::is_currently_entered()` or something... that clearly is a bad name though).

Either way, `Result` is better than `Option`.

**Comment by carllerche** [comment]
In those cases, `enter` would have a generic message, but sane implementations would check first and use a custom panic message (so the generic one is avoided).

**Comment by carllerche** [comment]
What actions need to be taken for this issue as of now?

**Comment by alexcrichton** [comment]
`enter()` needs to change from returning `Option` to returning `Result`?

**Comment by alexcrichton** [comment]
Implemented in the 0.2 branch
