### ISSUE TITLE
Generic Executor traits

### ISSUE THREAD

**Issue by stbuehler** [rust-lang-nursery/futures-rs#661]
Sometimes I'd like to provide a generic interface, and need to ask for an executor to spawn one or more `Future`s.  But now I need to name the `Future` types I want to spawn in the public interface (or box them), and I'd rather avoid that.

It would be nice if rust supported something like this (but it doesn't afaict...):

```rust
fn spawn_some_local_future(e: &E)
where
    for<F: Future<Item = (), Error = ()> + 'static>: Executor<F>
{
    // ...
}
```

As far as I can see there is usually no reason for an executor to run only very specific `Future`s; the main difference is whether a `Future` is `Send` or not.

So I'd like to see generic interfaces like this:

```rust
pub trait LocalExecutor: RemoteExecutor + RemoteClosureExecutor {
    fn execute_local<F>(&self, f: F) -> Result<(), ExecuteError<F>>
    where
        F: Future<Item = (), Error = ()> + 'static,
    ;
}

pub trait RemoteExecutor {
    fn execute_remote<F>(&self, f: F) -> Result<(), ExecuteError<F>>
    where
        F: Future<Item = (), Error = ()> + Send + 'static,
    ;
}

pub trait RemoteClosureExecutor {
    fn execute_remote_closure<C, F>(&self, c: C) -> Result<(), ExecuteError<C>>
    where
        C: FnOnce() -> F + Send + 'static,
        F: Future<Item = (), Error = ()> + 'static,
    ;
}
```

Implementations for tokio `Core`, `Handle` and `Remote` are trivial (`Remote` obviously can't implement `LocalExecutor`).

**Comment by carllerche** [comment]
> As far as I can see there is usually no reason for an executor to run only very specific Futures; the main difference is whether a Future is Send or not.

It is very useful to be able to be generic over the specific future. Being able to accept any future means that the executor will be forced to use allocations + dynamic dispatch. Being able to specify the exact future type allows for more optimized executors that are able to operate w/o allocations or dynamic dispatch.

**Comment by stbuehler** [comment]
I see. So what you're saying is that a good library should always wrap it's Futures in explicit types (this won't work though with closures and `#[async]` afaict).

And if I'm not willing to do this, an event loop handling generic Future types will probably box them anyway.  If we now could avoid the double-boxing somehow I'd be convinced there is no real need for those traits.

**Comment by carllerche** [comment]
There is no need to double box. You can see how existing event loops impl Executor today.

Libraries in general probably want to return explicit types in order to be able to extend the library without breaking changes but it is up to the library authors. Abstract type should help as well when that lands.

**Comment by stbuehler** [comment]
I agree there is no generic need, but I'm pretty sure tokio will double box in [`Handle::spawn`](https://docs.rs/tokio-core/0.1.10/src/tokio_core/reactor/mod.rs.html#720-728) if I pass an already boxed future.

How could tokio avoid it? Maybe trying to match some boxed Future types with `Any::is` and some crazy memory transforms? Probably easier to create a separate `spawn_box` function; but this won't be accessible through the existing `Executor` interface until [RFC 1210: impl specialization](https://github.com/rust-lang/rust/issues/31844) lands.

**Comment by alexcrichton** [comment]
This issue sounds like it may be a bit more general than double boxing (but I may be misinterpreting?) but yeah for now the most likely way we'll avoid double-boxing in the future is via specialization, but in the meantime we could also add a separate spawn function for boxed futures if necessary!

**Comment by aturon** [comment]
See the [executor RFC](https://github.com/rust-lang-nursery/futures-rfcs/pull/3).

**Comment by stbuehler** [comment]
The `Executor` trait looks fine to me - imho this issue can be closed.

**Comment by aturon** [comment]
Closing, this has been addressed.
