### ISSUE TITLE
Consider removing the `Self::Error: From<Fut::Error>` bound on `fold`

### ISSUE THREAD

**Issue by carllerche** [rust-lang-nursery/futures-rs#668]
This bound means that the error type of the inner closure cannot be inferred when it is always `Ok`.

My fold return value must now be:

```rust
Ok::<_, tower_grpc::Error>((summary, Some(point)))
```

All combinators should probably be inspected for such issues.

**Comment by cramertj** [comment]
@alexcrichton I think we should remove all of the error conversions for now, and we can add them back if default-type-params gets a solution? (there's a new RFC which looks exciting)

**Comment by alexcrichton** [comment]
@cramertj sgtm

**Comment by alexcrichton** [comment]
This'll get fixed in 0.2 in https://github.com/rust-lang-nursery/futures-rs/pull/733, so closing.
