### ISSUE TITLE
Interacting with parked sinks (and futures)

### ISSUE THREAD

**Issue by AljoschaMeyer** [rust-lang-nursery/futures-rs#687]
Suppose a call to `start_send` on a sink returns `Ok(NotReady)`. Am I allowed to call call other methods like `poll_complete` or `close` before the sending has been unparked? The docs don't explicitely disallow this, but correctly handling this scenario makes sink implementations more complex. And it somewhat makes sense to assume that these things can not be interleaved, e.g. to allow sending partial data between different poll attempts.

What about calling `start_send` itself multiple times, while previous calls are still blocked. Is that allowed? If this was allowed but flushing/closing was not, all helper methods would need to indicate their compatibility, which would again make a lot of things more complex.

Following the above reasoning, I always assumed that `poll` on a future may also only be called once while in-flight. This is not true, e.g. the join combinator may poll the same contained future multiple times, even though it already signaled non-readiness and will be unparked eventually. I can't judge whether allowing multiple polling simplifies lots of things, but it definitely complicates others. And it seems unintuitive to me to allow polling something which will already unpark itself. Isn't the whole point of the system that you don't need to poll multiple times?

Whether multiple polling and interleaved sink methods are allowed or not, the docs should clearly state that, instead of avoiding the topic.

**Comment by alexcrichton** [comment]
The contract of sinks/futures/streams are that the *last* task to call a method is the only one to get notified. In that sense it's perfectly legal to switch calling methods (note that a not ready `start_sent` implies a `poll_complete` though) it's just that you may lose task notifications.

The `close` function has a slight contract around it that when it starts sinks may start panicking if you then call `start_send`.

Sounds like we could have some better docs!

**Comment by aturon** [comment]
I believe this is now covered well by the docs.
