### ISSUE TITLE
Separate crate for combinator methods and functions

### ISSUE THREAD

**Issue by cramertj** [rust-lang-nursery/futures-rs#711]
Right now, combinators methods and functions are defined in the same place as the core interface of `futures`: `Future::poll`, `Stream::poll`, `Sink::xxx` etc. This offers some convenience, but it also means that any breaking changes to combinators require a breaking release of the `futures` crate and therefore break compatibility for the core traits.

I propose that we move the core traits into a separate crate, `futures-traits`, and that we re-export `futures-traits` from the `futures` crate for ease of use. With this approach, it would be possible to release breaking changes and improvements to combinators while still allowing libraries and applications to upgrade at their leisure.

This could potentially include moving methods like `and_then` etc. into a `FutureExt` trait which would be included in the prelude.

See previous discussion [here](https://github.com/alexcrichton/futures-rs/pull/696#issuecomment-358745452).

**Comment by carllerche** [comment]
I personally would be hesitant as the facade / re-export strategy will make it easy to accidentally use types that are prone to churn.

The proposed strategy of reducing futures-rs and moving items to futures-util would avoid this.

**Comment by cramertj** [comment]
@carllerche That seems like a reasonable concern to me. My hesitation is that it seems odd to require that users depend on two crates in order to get basic functionality.

**Comment by alexcrichton** [comment]
Er sorry yeah I was thinking we'd go the other direction, moving less-used more-susceptible-to-breakage stuff to an external crate rather than extract the traits themselves.

**Comment by cramertj** [comment]
@alexcrichton Can you give some examples of the sorts of things you'd like to move out of the current repo? "Less-used" seems like a challenging judgement call and it's hard to know where any specific combinator should belong (similarly, it's harder for users to find if they have to search across two crates).

**Comment by alexcrichton** [comment]
Certainly! Taking a look now... perhaps:

* `Future::shared`
* `Future::from_err`
* `Future::inspect*`
* `Future::catch_unwind`
* `Stream::catch_unwind`
* `Stream::peekable`
* `Stream::chunks`
* `Stream::inspect*`
* `Sink::with_flat_map`
* `Sink::sink_from_err`
* `Sink::fanout`

and maybe the `unsync` module? I could go either way on a lot of these though!

**Comment by carllerche** [comment]
Re the `unsync` module, I'd like to see either a) it moved to a -tools crate or b) the justification for having it is revisited.

As I recollect, it was added because "atomics are overkill when working in a single thread", however I don't remember seeing any numbers backing this statement.

Or I could have completely forgotten the original argument.

**Comment by aturon** [comment]
Closing, this is dealt with in the 0.2 branch.
