### ISSUE TITLE
Sink::send() on error should provide the sink back

### ISSUE THREAD

**Issue by manuels** [rust-lang-nursery/futures-rs#716]
I noticed that `Stream::into_future()` returns `(S::Error, S)` on error.
`Sink::send()` however returns `S::SinkError` on error, so the `Sink` is gone for good if `send()` fails.
I would suggest to make `Sink::send()` return `(S::SinkError, S)` on error, too.

This issue is similar to #602.

**Comment by manuels** [comment]
Now that 0.2.0-alpha is out, `Sink::send()` still does not return the sink back on error.

Did plans change and it's intentional, or was this bug not fixed, yet?

**Comment by manuels** [comment]
I mean, not returning the sink is very TCP-centric: If we cannot send data anymore, the connection must be closed. But for e.g. UDP sockets it can happen that we get an destination/network unreachable error which we just want to ignore and continue sending packets to other hosts via the same sink.

**Comment by aturon** [comment]
@manuels I think this was just missed. I've put it on the milestone for the final 0.2.

**Comment by carllerche** [comment]
Personally, I’d rather see Stream::into_future not include the stream on error (by default). 

A better option imo would be an inherent fn on the various futures that allow optionally getting the stream / Sink back by wrapping the future with WithInner<T> or something like that that provides the altered error type.

**Comment by manuels** [comment]
@aturon, if I can help out with a pull request please let me know.

**Comment by aturon** [comment]
@carllerche can you give a rationale for your preferences?

**Comment by carllerche** [comment]
@aturon the rational is that, in *most* cases, when you call `into_future` and there is an error, you don't care about the original stream. So, if the *default* is to include the error, now you basically always have to map the error on every single call to `into_future`.

```rust
my_stream.into_future()
    .map_err(|(e, _)| e)
    .and_then(|v| do_something(v))
```

I suggested this in a previous issue (but I can't find it anymore):

```rust
impl<T: Stream> IntoFuture<T> {
    pub fn return_self_on_err(self) -> ReturnSelfOnErr<IntoFuture<T>> {
        ReturnSelfOnErr(self)
    }
}

impl<T: Stream> Stream for ReturnSelfOnErr<IntoFuture<T>> {
    type Item = ....;
    type Err = (T::Error, T);

    fn poll ... {
        self.0.poll()
            .map_err(|e| (e, self.0.inner.take().unwrap()))
    }
}


my_stream.into_future()
    .return_self_on_err()
    // use into_future, now with the original stream on error
```

Obviously a very quick sketch w/ bad names.

**Comment by manuels** [comment]
Too bad, now that the stable v0.2.0 is out, chances that this breaking API change can be applied, looks rather bad, right?

**Comment by cramertj** [comment]
This is done in 0.3 since `send` takes `&mut self`.
