### ISSUE TITLE
The documentation of `futures::stream::Stream::for_each` confused me

### ISSUE THREAD

**Issue by friedrich** [rust-lang-nursery/futures-rs#725]
The documentation says that `for_each` "runs this stream to completion". I did not care about all the details of the function, so that is where I stopped reading. It took me quite some time to realize that `for_each` does also stop as soon as an error is generated.

I know I should have just read the whole paragraph, but the first statement sounded pretty strong to me and I did not consider the possibility that it could be contradicted later on.

Would you consider changing the documentation to something like: "Runs this stream to completion, or until an error occurs, executing the provided closure for each element on the stream."

**Comment by cramertj** [comment]
IMO this behavior should be changed-- streams run until `None`, not until an error.

**Comment by aturon** [comment]
@cramertj did you end up changing this?

**Comment by cramertj** [comment]
No, this has not been changed. I still think it should be changed, though, perhaps adding another method for opting-in to the current behavior (though it is just `stream.for_each(|res| res.into_future().and_then(|x| <old body here>))`, so it's not too bad).

**Comment by aturon** [comment]
I'm going to punt this to 0.3, where we're revising the error handling story throughout.

**Comment by taiki-e** [comment]
I think this was fixed in 0.3

[StreamExt::for_each](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.18/futures/stream/trait.StreamExt.html#method.for_each)
> **Runs this stream to completion**, executing the provided asynchronous closure for each element on the stream.
>
> The closure provided will be called for each item this stream produces, yielding a future. That future will then be executed to completion before moving on to the next item.
> 
> The returned value is a Future where the Output type is (); **it is executed entirely for its side effects.**

[TryStreamExt::try_for_each](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.18/futures/stream/trait.TryStreamExt.html#method.try_for_each)

> **Attempts to run this stream to completion**, executing the provided asynchronous closure for each element on the stream.
> 
> The provided closure will be called for each item this stream produces, yielding a future. That future will then be executed to completion before moving on to the next item.
> 
> The returned value is a Future where the Output type is Result<(), Self::Error>. **If any of the intermediate futures or the stream returns an error, this future will return immediately with an error.**
