### ISSUE TITLE
Manually implement `Debug` for combinators/wrappers containing closures

### ISSUE THREAD

**Issue by abonander** [rust-lang-nursery/futures-rs#737]
`#[derive(Debug)]` isn't particularly useful for combinators or wrappers that take closures as it requires all fields to be `Debug` even though closures don't implement it and the `Debug` impl on function pointers isn't particularly meaningful anyway, as it just prints the value of the pointer.

I recommend instead manually implementing `Debug` for these, debug-printing the other fields such as nested futures/streams while printing something like `[closure]` (bikeshedding welcome) for the closure fields of these combinators/wrappers.

This is confusing users in the wild, [like this person](https://www.reddit.com/r/rust/comments/7vd891/hey_rustaceans_got_an_easy_question_ask_here_62018/dtwdmd9/) trying to `.unwrap()` the result of a `Select2<Map<_, [closure]>, _>`.

I'm willing to implement this myself if it meets everyone's approval.

**Comment by alexcrichton** [comment]
This sounds like a great idea to me!
