### ISSUE TITLE
Potential issue with flushing a buffered Sink

### ISSUE THREAD

**Issue by benashford** [rust-lang-nursery/futures-rs#752]
I think this might be related to the recent Tokio reform, as I have only noticed on code that uses the new `tokio` rather than `tokio-core`, but tracing the code it appears to be a bug when flushing a buffered Sink.

The symptom was that the final few messages being written to a Sink were not being flushed, even when using `send_all` to feed the Sink, which should have flushed the sink before completing.  Instead, the `send_all` was never completing and the buffered messages never flushed.

After following the chain of function calls, the issue appears to be here: https://github.com/rust-lang-nursery/futures-rs/blob/master/src/sink/buffer.rs#L47-L61 (although I'm not familiar enough with the codebase to be sure).

```rust
    fn try_empty_buffer(&mut self) -> Poll<(), S::SinkError> {
        while let Some(item) = self.buf.pop_front() {
            if let AsyncSink::NotReady(item) = self.sink.start_send(item)? {
                self.buf.push_front(item);

                // ensure that we attempt to complete any pushes we've started
                self.sink.poll_complete()?;

                return Ok(Async::NotReady);
            }
        }

        Ok(Async::Ready(()))
    }
```

The result of the call to `self.sink.poll_complete()` was `Ok(Async::Ready(()))` because the underlying Sink had flushed successfully, but this function returns `Ok(Async::NotReady)` as this buffer was not fully flushed.

However, since the underlying Sink was flushed successfully, the future was not scheduled for further execution, hence why no more flushes were attempted and my system ground to a halt.

I verified this by creating a custom `send_all` within my client code, which explicitly rescheduled the future in the event of a `Async::NotReady` from the `poll_complete` function of the buffer.  Which did fix the problem, but this is obviously inefficient as it will re-poll the future at the earliest opportunity, rather than when the bottom-level indicates it is ready (in this case a `tokio` TcpStream).

The simplistic fix would be to check the result of `self.sink.poll_complete()?` and, if the result was `Async::Ready(())` to continue looping through the buffer until either the whole buffer is accounted for or we get a `Async::NotReady` from the underlying Sink.  But when I attempted this, the `buffer` test went into an infinite loop, so either the test needs to be updated, or (much more likely) I'm missing information and the simplistic fix isn't a fix after-all.

**Comment by alexcrichton** [comment]
Aha thanks for the report! I do indeed think this is a bug, currently there's a contract that a failed `start_send` "otherwise attempted and failed a `poll_complete`" so we should be able to omit it entirely. Does that work for the use case you ran into? If so, sounds like something we should definitely fix!

**Comment by benashford** [comment]
Thanks for this, that makes sense.

In my case the underlying sink was a Framed Sink from `tokio-io`, which, when I traced the call-stack was calling this: https://github.com/tokio-rs/tokio/blob/master/tokio-io/src/framed_write.rs#L159

The implementation of `start_send` for that sink will call `poll_complete` before returning `Async::NotReady`, so it seems to honour the contract.  But it could have been that that `poll_complete` completed successfully, but the data left in the buffer was still above the threshold, so a `Async::NotReady` was returned hence causing the problem I've been seeing.  (I'm not familiar with the Tokio codebase either 😀 so I'm probably missing something.)  Does this implementation meet the contract?

I'll try and put together an example that shows this problem happening, and if it looks like a Tokio issue I'll open an issue against that project.

**Comment by alexcrichton** [comment]
Hm nah I think that's impemented implemented ok and upholds the current contract of `Sink` because if poll_complete succeeds it'll have drained the internal buffer and the item may be encoded?

**Comment by benashford** [comment]
I see now, this makes sense.

To demonstrate the bug with real-code, I've pushed a `futures-bug` branch on one of my projects: https://github.com/benashford/redis-async-rs/tree/futures-bug the problem can be seen when running `cargo bench bench_complex_pipeline` (warning: it's a Redis client so needs a Redis instance running on localhost - if you already have one running, it'll write nonsense to it).

The only difference between the `futures-bug` and `master` branch is that `futures-bug` buffers the Sink used to send Redis commands and `master` doesn't.

Using that test case your original suggestion fixed the problem and the test completes reliably with the fix in place.

I'll open a PR with the (very small) fix.
