### ISSUE TITLE
sync::mpsc vs. unsync::mpsc

### ISSUE THREAD

**Issue by dominikwerder** [rust-lang-nursery/futures-rs#766]
I have two futures running on the same tokio core.
The first future processes a stream and forwards the items into a `mpsc`.
The second future reads from that `mpsc`.
Everything works fine with `sync::mpsc`.
But when I switch to `unsync::mpsc` then the second future will apparently not know when the `Sender` side is closed and continue running.
No `unsafe` code at all.

Before I dig deeper and try to extract a minimal not-working example, I wanted to ask: Is there anything special about the `unsync::mpsc`?

**Comment by alexcrichton** [comment]
Thanks for the report! The `unsync` module is currently intended to be the exact same as the `mpsc` module, so if it's not a drop-in replacement then that's probably indicative of a bug!

**Comment by dominikwerder** [comment]
OK, the PR #768 would be ready.
