### ISSUE TITLE
`&self` vs. `&mut self` for executors.

### ISSUE THREAD

**Issue by carllerche** [rust-lang-nursery/futures-rs#767]
A continuation of [this](https://github.com/rust-lang-nursery/futures-rs/pull/763#discussion_r168088727) thread.

The executor PR diverged from the [RFC](https://github.com/aturon/futures-rfcs/blob/5fa3bdc1971a75f48266236cad3392302c2657fb/executors.md#the-core-executor-abstraction-executor).

Generally, `&mut self` would provide more flexibility for implementations. Whether that flexibility is needed or not is TBD.

@aturon says:

> Then you can't implement `Executor` on an `Arc<E: Executor>`.

This is true, but how common is that? Also, a work around would be taking `T: Executor + Clone`.

@cramertj  says

> I don't think the `Executor` for `Arc<E: Executor>` is the critical piece: the important part is that this needs to work somehow:
>
> ```rust
> let local_pool = LocalPool::new();
> let local_exec = local_pool.executor();
> local_pool.run_until(|f| future
>     .and_then(|_| local_exec.spawn_local(some_other_task))
>     .and_then(...));
> ```

But this doesn't seem related to the mutability of self as `local_exec` is owned and can be moved into the closure.

Either way, I don't think there is a critical problem, but the reasoning should be clear.

**Comment by aturon** [comment]
I don't have a strong preference here; `&mut` seems fine.

**Comment by cramertj** [comment]
@carllerche 
> But this doesn't seem related to the mutability of self as local_exec is owned and can be moved into the closure.

Indeed-- my point was that, because `local_exec` has to be owned, it isn't possible to eliminate the `Rc<RefCell<_>>` underneath, so `&mut` doesn't give the implementation any more freedom.

**Comment by carllerche** [comment]
I mentioned this on IRC, but I'll post here for the record.

I tried adding an implementation of `Executor` or the current_thread executor included w/ Tokio. See [here](https://github.com/tokio-rs/tokio/blob/tokio-runtime/src/executor/current_thread/mod.rs#L392).

This implementation takes advantage of `&mut self` and does not need `RefCell`, which is nice. If `&self` is required, it probably could be switched to `RefCell` or `UnsafeCell`, but it is kind of nice to not have to :)

**Comment by aturon** [comment]
I think I'm convinced we should go with `&mut self`. Originally I had been thinking that with `&self` we could allow users of executors to decide on the memory management strategy (by applying an `Rc`/`Arc` themselves), but in practice I think these are usually baked into the executor anyway.

**Comment by aturon** [comment]
This is now addressed on the 0.2 branch.
