### ISSUE TITLE
Stream::for_each where Stream has no error type and closure does.

### ISSUE THREAD

**Issue by GoldenBadger** [rust-lang-nursery/futures-rs#774]
Hi, apologies if this isn't the best place to post this. I have a `mpsc::Receiver` on which I am calling `for_each`. `Receiver` has no error (i.e. type `()`), but the closure I am passing the `for_each` call does return errors. Here is an example of my code:

```rust
let conn_loop_future = rx.for_each(|task| {
    future::done(task.write_to_bytes())
        .map_err(|e| e.context(BrokerErrorKind::TaskSerialisationFailed))
        .and_then(|bytes| {
            channel
                .basic_publish(
                    "",
                    RABBIT_QUEUE_NAME,
                    &bytes,
                    &BasicPublishOptions::default(),
                    BasicProperties::default(),
                )
                .and_then(|_| {
                    debug!(
                        "Task of length {} bytes sent to queue `{}`.",
                        bytes.len(),
                        RABBIT_QUEUE_NAME
                    );
                   future::ok(())
                })
                .map_err(|e| e.context(BrokerErrorKind::ConnectionDropped))
        })
});
```

Naturally, this code fails to compile as the closure returns a `Future<Item = (), Error = failure::Context<BrokerErrorKind>` but the `rx` stream doesn't have an error associated with it so it expects the closure to return a future with no error also. What's the current best way to handle errors encountered while processing the stream? Thanks.

**Comment by vitalyd** [comment]
The simplest is probably to `map_err` to an `unreachable!()` and then let type inference handle the rest:
```
rx.map_err(|_| unreachable!("receiver does not error")).for_each(...)
```

**Comment by GoldenBadger** [comment]
Thanks very much, that sorted it. I'll keep `unreachable!()` in mind in the future. Many thanks @vitalyd.
