### ISSUE TITLE
Stream::take_until()/skip_until() a future is ready

### ISSUE THREAD

**Issue by manuels** [rust-lang-nursery/futures-rs#776]
I would like to propose two new functions to add to `Stream`: `take_until(self, future: F)` and `skip_until(self, future: F)` where `F: Future<(), Stream::Error>`.

`skip_until()` would just be the 'reverse' of `take_until()`, so let's concentrate on `take_until()` for now:
`take_until()` should yield items of the stream until a side condition is true, i.e. the future is ready.
Note that this sounds a bit like the `take_while(self, pred: FnMut(&Self::Item) -> R)` function, that already exists, but `take_while()` *waits for new items* and then runs a predicate function on them, but `take_until()` should wait for the future asynchronously and stop the stream *even if no new item is available*.

Note that I am not really sure about the naming of the functions. There are probably better names.

**Comment by troplin** [comment]
This would be nice especially for signals like ctrl-c (tokio-signal)

**Comment by jonhoo** [comment]
Another use-case for this is to enable graceful shutdown of long-running futures. For example, consider a `tokio::net::TcpListener`'s `Incoming` `Stream`. You could then have a oneshot channel that indicates shutdown (maybe wrapped in a `Shared`), and write:
```rust
listener.incoming().take_until(shutdown_rx).for_each(...)
```

**Comment by jonhoo** [comment]
For those in need of this, you can use my [`stream-cancel`](https://docs.rs/stream-cancel/) crate :)
