### ISSUE TITLE
Documentation for polling methods needs improvement

### ISSUE THREAD

**Issue by stjepang** [rust-lang-nursery/futures-rs#790]
Currently, the docs for `Future::poll` contain the following paragraph:

> Note that if `NotReady` is returned it only means that *this* task will receive a notification. Historical calls to `poll` with different tasks will not receive notifications. In other words, implementers of the `Future` trait need not store a queue of tasks to notify, but only the last task that called this method. Alternatively callers of this method can only rely on the most recent task which call `poll` being notified when a future is ready.

Put differently, if `NotReady` is returned, the current task is registered for future notification. However, it is **not** guaranteed that the current task will be notified when the future completes. However, **at least one** task that polled it will be notified.

I think the wording in this paragraph could be shorter and clearer. A recently accepted RFC will introduce explicit `&mut task::Context` argument to `poll`, which will hopefully clear up one of the long-standing 'gotchas' about futures. But another big surprise for me was the fact that **at least one** task gets notified, and **not necessarily all** of them. This should be more clearly indicated in the documentation. Currently, the paragraph is buried deep in the docs for `Future::poll`.

Another issue is that the same rule also applies to `Stream::poll` and `Sink::start_send`, yet the documentation for those methods does not mention how many tasks get notified at all.

**Comment by aturon** [comment]
Note -- the docs are being rewritten in 0.2.

**Comment by aturon** [comment]
Closing as per docs rewrite.
