### ISSUE TITLE
AsyncRead / AsyncWrite EINTR handling

### ISSUE THREAD

**Issue by carllerche** [rust-lang-nursery/futures-rs#803]
Continuation of https://github.com/tokio-rs/tokio-io/issues/37.

PR: https://github.com/tokio-rs/tokio/pull/136

This should be figured out before releasing.

**Comment by cramertj** [comment]
In https://github.com/tokio-rs/tokio-io/issues/37 it was decided that `AsyncRead/Write` implementations shouldn't bubble up `EINTR`, but should retry on their own. Does that still seem like a reasonable approach? I don't personally have a strong opinion here. If that is the decision, we should make sure to add documentation to that effect on the `AsyncRead/Write` traits.

cc @alexcrichton @aturon

**Comment by carllerche** [comment]
To elaborate a bit, I don't think an `EINTR` should ever happen in practice due to calls being async / non blocking (as such, there is nothing to interrupt).

Of course, there might be fringe reasons for `EINTR` to occur that cannot be anticipated, so maybe the answer is to update the documentation to say that `EINTR` should never be **returned**. Instead, the operation should be retried **or** the error converged to a different error.

**Comment by cramertj** [comment]
That makes sense-- then the only place we really have to worry about this is the `AllowStdIo` combinator, right?

**Comment by alexcrichton** [comment]
@cramertj yeah it seems fine by me to swallow EINTR in futures-io, notably in the context of async I/O I think that EINTR matters far less than in sync I/O where it's actually used to interrupt things from time to time.
