### ISSUE TITLE
Feature request: feature flag for integration with `Fail` crate

### ISSUE THREAD

**Issue by sdleffler** [rust-lang-nursery/futures-rs#810]
Here's a new issue as requested, previous comment can be found [here](https://github.com/rust-lang-nursery/futures-rs/issues/660#issuecomment-368164273).

I've been using `failure` with `futures` and I've got a couple of little obstacles which could, if fixed, make interop a lot nicer! It all boils down to two separate slight hiccups:

First off, it'd be nice if optionally `futures` could support something similar to the [`ResultExt`](https://docs.rs/failure/0.1.1/failure/trait.ResultExt.html) trait present in `failure`; I'd just like to be able to call `.context(...)`, `.with_context(...)`, and `.compat()` directly on futures without having to go through `.map_err`. The context functions especially are very useful with futures as they allow you to trace back through which exact futures failed very easily. That's a bit of a lesser issue though, and the main problem I have is with `SharedError`/the `Shared` future:

`SharedError<E>` does not implement `Fail` where `E: Fail`, even with the blanket impls coming from `failure`. This is because `Fail` types (and specifically the `failure::Error` type) do not necessarily implement `std::error::Error`, which means that their error implementations do not pass through, `SharedError<E: Fail>` does not implement `std::error::Error` and a rather confusing error message results. The message essentially says "`SharedError<E>` does not implement Fail because `SharedError<E>` does not implement `Error` because `E` does not implement `Error`", which is true, because `E` implements fail - but all this comes with a several-traits-long backtrace from trait resolution showing rustc's reasoning for the requirement which can be somewhat difficult to muck through when you're using `futures-await` or just plain sleep deprived.

So, minimally, in order to ergonomically use `futures` with `failure`, I think there should be some sort of enabling to make futures error types work with `Fail`, and then it would be a fantastic cherry on top to have `ResultExt`-like methods auto-implemented onto `Futures`.

**Comment by stbuehler** [comment]
I don't think "integration-with-other-crate-feature-flag" is a solved problem: if there is a crate (say tokio) using `futures` without the feature flag, and your application uses `futures` with the feature flag, you'll have a hard time combining types of those two.

With the new split into many crates you could get away with a feature flag in `futures-util` and combine the incompatible types of `futures-util` through the common and hopefully compatible base `futures-core`.

**Comment by cramertj** [comment]
closing-- I think it's easy enough to call `.context` now that we have async/await.
