### ISSUE TITLE
Rustdoc does not respect type alias Poll<Self::Item, Self::Error>

### ISSUE THREAD

**Issue by Centril** [rust-lang-nursery/futures-rs#816]
On http://rust-lang-nursery.github.io/futures-rs/futures/prelude/trait.Future.html, rustdoc renders this as:

![`-> Result<Async<Self::Item>, Self::Error>;`](https://cdn.pbrd.co/images/H9GJALL.png)

I.e:

```rust
-> Result<Async<Self::Item>, Self::Error>;
```

instead of:

```rust
-> Poll<Self::Item, Self::Error>;
```

This makes me feel a bit 😢

**Comment by withoutboats** [comment]
This is a rustdoc issue, not a futures issue
