### ISSUE TITLE
Idea: A nicer type alias for the Future trait

### ISSUE THREAD

**Issue by Centril** [rust-lang-nursery/futures-rs#817]
While reading @aturon's interesting blog post about futures 0.2, a thought crossed my mind..

The trait `Future` will be defined as:

```rust
trait Future {
    type Item;
    type Error;

    fn poll(&mut self, cx: task::Context) -> Poll<Self::Item, Self::Error>;
}
```

but I'd propose that you define a type alias:
```rust
type Polled<F> = Poll<<F as Future>::Item, <F as Future>::Error>;
```

and then define the trait as:

```rust
trait Future {
    type Item;
    type Error;

    fn poll(&mut self, cx: task::Context) -> Polled<Self>;
}
```

I believe this formulation to be more terse and readable.

This device is used in the crate `proptest` here: https://docs.rs/proptest/*/proptest/strategy/trait.Strategy.html#tymethod.new_value

**Comment by alexcrichton** [comment]
This has an unconditional warning:

```
warning[E0122]: trait bounds are not (yet) enforced in type definitions
 --> src/main.rs:5:1
  |
5 | type Polled<F: Future> = Poll<<F as Future>::Item, <F as Future>::Error>;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: type alias is never used: `Polled`
 --> src/main.rs:5:1
  |
5 | type Polled<F: Future> = Poll<<F as Future>::Item, <F as Future>::Error>;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(dead_code)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 1.5 secs
     Running `target/debug/playground`
```

so it may not work?

**Comment by Centril** [comment]
@alexcrichton

```rust
type Polled<F> = Poll<<F as Future>::Item, <F as Future>::Error>;
```
This type alias already requires that `F: Future` by using the projections from `<F as Future>::`, so there's no need to add that constraint - but you could do it for extra clarify and 🤐 the warning..

**Comment by alexcrichton** [comment]
Oh weird, I had no idea! Seems like a nifty idea to me if that's the case!

**Comment by stbuehler** [comment]
The warning is only shown with `F: Future`, but with `: Future` and without the warning means this compiles:

```rust
type Polled<F> = Poll<<F as Future>::Item, <F as Future>::Error>;
type Foo = Polled<i32>;
```

It will (for now) only break if you actually "use" `Foo`.

Given people could be using the type alias in a way that breaks in future rust versions I'd recommend against it.

**Comment by cramertj** [comment]
obsolete
