### ISSUE TITLE
Dead links in/to docs 

### ISSUE THREAD

**Issue by ousado** [rust-lang-nursery/futures-rs#821]
https://github.com/rust-lang-nursery/futures-rs/issues/702 already mentions it, but it's concerned with other issues, too. There are dead links to https://tokio.rs and also some to https://github.com/alexcrichton/futures-rs in the futures documentation and other places on the web that are supposed to provide the in-depth information on the respective crates/modules.

**Comment by aturon** [comment]
I believe this is addressed on master now.
