### ISSUE TITLE
Consider switchin stream::once to take T: IntoFuture

### ISSUE THREAD

**Issue by carllerche** [rust-lang-nursery/futures-rs#826]
AFAIK, there is no way to convert a future to a stream of one value right now. `stream::once` takes a Result. It probably wouldn't be hard to update that to take `T: IntoFuture`.

**Comment by cramertj** [comment]
Are you looking for [this method](https://rust-lang-nursery.github.io/futures-rs/futures/prelude/trait.FutureExt.html#method.into_stream)?

**Comment by carllerche** [comment]
I guess so, it wasn't clear where to look for it. My first thought was `stream::foo(...)`
