### ISSUE TITLE
AsyncWrite::poll_write doc error

### ISSUE THREAD

**Issue by carllerche** [rust-lang-nursery/futures-rs#839]
https://github.com/rust-lang-nursery/futures-rs/blob/a7d08e635ae1b24bc0442f4fb38629b49ee595e2/futures-io/src/lib.rs#L156

This should just be "writable".

**Comment by cramertj** [comment]
I don't consider this an error-- the documented behavior is intentional. If you're attempting to write to a socket and it is closed in the middle of the process, your task shouldn't silently stall out-- it should be woken up to discover that the socket has been closed and respond appropriately, just as in `AsyncRead::poll_read`.

**Comment by carllerche** [comment]
This is not how Tokio or epoll / kqueue (afaik) work. HUP signals the read half closed, which *usually* means the write half closed as well, but this is not a guarantee. Tokio will only notify the read half on HUP.

So, as of now, Tokio does not satisfy the contract as defined here.

**Comment by carllerche** [comment]
The details are [here](https://github.com/tokio-rs/tokio/blob/master/tokio-reactor/src/lib.rs#L354-L364).

I guess it would depend on if a full close implies a write error, however catching remote TCP sockets closing is simply unreliable.

**Comment by carllerche** [comment]
> If you're attempting to write to a socket and it is closed in the middle of the process, your task shouldn't silently stall out

The fact is that this is what happens when you expect to get notified on close given how unreliable getting this notification can be :)

**Comment by cramertj** [comment]
> HUP signals the read half closed, which usually means the write half closed as well, but this is not a guarantee.

But it *will* signal HUP when the write half is closed, right? It's fine to provide unnecessary wakeups, but it isn't fine to miss wakeups. I know what tokio does today, and I consider it to be a bug (see https://github.com/tokio-rs/tokio-core/issues/274).

Furthermore, the proposed contract (notify only on "writable") means that ever task which blocks on performing a write must also be attempting to read in order to receive notifications when the socket closes, which seems unworkable to me and would make all of the current combinators on `AsyncWrite` incorrect.

**Comment by cramertj** [comment]
> The fact is that this is what happens when you expect to get notified on close given how unreliable getting this notification can be

So what should you do instead? Set a timeout for every task which will be blocked by the inability to write (including elements of a `FuturesUnordered`, which will leak if they remain uncompleted)?

**Comment by carllerche** [comment]
> But it will signal HUP when the write half is closed, right?

I don't know if this is true. It is also very difficult to test given how sockets are almost always writable. The case in question is the socket transitions to not writable (internal buffer fills up) then the remote sends a half shutdown.

In this case, I just don't know what will happen. epoll doesn't really treat events on read / write halves as independent.

I think that it is plausible that you will get a write notification followed by a write failing at *some* point, but I can't really say what the guarantees are right now.

**Comment by carllerche** [comment]
> So what should you do instead? Set a timeout for every task which will be blocked by the inability to write (including elements of a FuturesUnordered, which will leak if they remain uncompleted)?

Pretty much one should always do this for reliability.

We're also talking about a very edge case given how sockets are almost always writable. I just cannot say with confidence what the *guarantee* is right now.

**Comment by carllerche** [comment]
I think kqueue might do the "right" thing given that read & write directions are separate. I skimmed the epoll docs and did not find any discussion of guarantees.

The next step would have to be reading the kernel source.

**Comment by cramertj** [comment]
I'm less concerned about the case where the write half is closed independently of the read half, and more concerned about the case where the entire thing is closed, and the read task is awoken while the write task is not. That seems like a bug to me.

**Comment by carllerche** [comment]
Reading through the linux kernel source, it **seems** that `HUP` is only returned when the socket has reached a full close.

The source also includes this comment, which does not inspire confidence:

> POLLHUP is certainly not done right. But poll() doesn't have a notion of HUP in just one direction, and for a socket the read side is more interesting.

So, Mio could translate `EPOLLHUP` to both readable / writable for linux and anything else would be a linux bug.

**Comment by seanmonstar** [comment]
There's also `EPOLLRDHUP`, just to make things more fun.

**Comment by aturon** [comment]
I'm going to punt this onto the 0.3 milestone; it'd be good to resolve the contract before then.

**Comment by taiki-e** [comment]
I think the document mentioned in the issue description has been fixed in #1633

**Comment by Nemo157** [comment]
#1633 fixed "readable" vs "writable", but I'm not sure whether the "is closed" notification is resolved. `tokio-io(0.2.0-alpha.4)::AsyncWrite::poll_write` also says:

> receive a notification when the object becomes readable or is closed.

@carllerche do you know if tokio guarantees notification on the write-half being closed now, or does this still need looking into?

**Comment by cramertj** [comment]
I believe the documentation here is still correct-- if there are changes needed, let me know!
