### ISSUE TITLE
Differences between channels in futures and std

### ISSUE THREAD

**Issue by stjepang** [rust-lang-nursery/futures-rs#840]
I'm wondering whether there are any high-level rules driving the design of channels in `futures`. At first sight, it might seem that `futures::sync::mpsc` and `std::sync::mpsc` are trying to mirror each other - the former channels work with asynchronous tasks and the latter channels work with threads. Other than that, they look very similar.

### Closing/disconnection

But then there are some peculiar differences. For example, channels in `futures` have [`Receiver::close`](https://docs.rs/futures/0.1.18/futures/sync/mpsc/struct.Receiver.html#method.close). If this method is useful, is there any reason why channels in `std` don't have it, too? Or, put differently, was this method added because it fits into a certain model of how `futures` should be used, or just seemed like a nice addition at a certain time?

### ~~Unbounded channels~~

~~Another difference is that `futures` doesn't have unbounded (sometimes called *asynchronous*) channels, while `std` does. Is there a reason for that? Golang considers unbounded channels dangerous because they don't provide backpressure. Still, they have their uses (e.g. in Servo), hence why we have them in `std`. Will we ever have them in `futures`, too?~~

### Capacities of bounded channels

Next, bounded channels in `futures` have unusual capacities. Each `Sender` has its own reserved slot in the channel, which means the actual capacity of a channel is the initial capacity + the number of active senders. There are technical reasons for this - I believe capacity behaves like that simply because it's hard to make it constant without sacrificing performance. These technical hurdles can be overcome, however. In any case, it can be surprising to discover this behavior.

### Learnability

There's also a case to be made for learnability. If the Rust book teaches inter-thread communication using `std::sync::mpsc`, are newcomers not going to expect channels in `futures` to behave the same way? But there sure seem to be a few important differences, or 'catches' one has to be aware of.

I'm personally a fan of thinking of channels in `futures` and `std` as virtually the same, except for what kind of threading/task mechanism they operate on. Or maybe making these channels as similar as possible is simply not a goal we should pursue?

**Comment by kamyuentse** [comment]
It's that the `Unbounded channels` you mentioned?

https://github.com/rust-lang-nursery/futures-rs/blob/master/futures-channel/src/mpsc/mod.rs#L376

**Comment by stjepang** [comment]
@kamyuentse Oh, I wasn't aware of the new unbounded channels because they don't show up on [docs.rs/futures](https://docs.rs/futures) yet. Never mind about the lack of unbounded channels then. :)

**Comment by kamyuentse** [comment]
@stjepang I just notice it when I check the code before. Thanks for your great conclusion about the difference.

**Comment by stsydow** [comment]
I use futures 0.1.25 and got an unexpected panic from the channel.
The scenario is sending from a stream (tokio runtime) to a GUI std::thread which calls poll on the Receiver. 
If all Senders (and their runtime?) is dropped, poll() panics on the receiver - I would expect an Error.

Am I doing it wrong? I found no way to have futures::*::Sender with std::*::Receiver.

**Comment by Nemo157** [comment]
@stsydow if you have a stack trace it would be good to open a new issue for it. Skimming the code I don't see any way that closing the channel should cause a panic to occur.

**Comment by bstrie** [comment]
I'm reviewing issues that are blocking the 0.3 milestone and I'd like a contributor to weigh in on the status of this issue. I'm unclear what action would be needed to resolve this, or whether it's still relevant since its original filing.

**Comment by cramertj** [comment]
I don't think this issue is still relevant-- if there're more changes wanted here, please file an updated issue. Thanks!
