### ISSUE TITLE
Not all targets support AtomicUsize

### ISSUE THREAD

**Issue by Nemo157** [rust-lang-nursery/futures-rs#842]
https://github.com/rust-lang-nursery/futures-rs/blob/master/futures-core/src/task/atomic_waker.rs requires `AtomicUsize`, unfortunately some targets such as `thumbv6m-none-eabi` lack atomic primitives and so currently don't build `futures 0.2`.

**Comment by Nemo157** [comment]
One solution is to use the `#[cfg(target_has_atomic = "ptr")]` check to avoid compiling the `futures_core::task::atomic_waker` module when not supported, that currently requires using nightly for the unstable `cfg_target_has_atomic` feature:

```diff
diff --git futures-core/src/lib.rs futures-core/src/lib.rs
index edef417d..a3335849 100644
--- futures-core/src/lib.rs
+++ futures-core/src/lib.rs
@@ -4,6 +4,8 @@
 #![deny(missing_docs, missing_debug_implementations, warnings)]
 #![doc(html_root_url = "https://docs.rs/futures-core/0.2")]

+#![feature(cfg_target_has_atomic)]
+
 #[macro_use]
 #[cfg(feature = "std")]
 extern crate std;
diff --git futures-core/src/task/mod.rs futures-core/src/task/mod.rs
index 8a6055af..bca90953 100644
--- futures-core/src/task/mod.rs
+++ futures-core/src/task/mod.rs
@@ -13,7 +13,9 @@ if_not_std! {
     type Exec<'a> = ();
 }

+#[cfg(target_has_atomic = "ptr")]
 mod atomic_waker;
+#[cfg(target_has_atomic = "ptr")]
 pub use self::atomic_waker::AtomicWaker;

 /// Information about the currently-running task.
diff --git futures/src/lib.rs futures/src/lib.rs
index 3096ffe0..409bd32a 100644
--- futures/src/lib.rs
+++ futures/src/lib.rs
@@ -22,6 +22,8 @@
 #![no_std]
 #![doc(html_root_url = "https://docs.rs/futures/0.2")]

+#![feature(cfg_target_has_atomic)]
+
 extern crate futures_core;
 extern crate futures_channel;
 extern crate futures_executor;
@@ -354,9 +356,12 @@ pub mod task {
     //! executors or dealing with synchronization issues around task wakeup.

     pub use futures_core::task::{
-        AtomicWaker, Context, LocalMap, Waker, UnsafeWake,
+        Context, LocalMap, Waker, UnsafeWake,
     };

+    #[cfg(target_has_atomic = "ptr")]
+    pub use futures_core::task::AtomicWaker;
+
     #[cfg(feature = "std")]
     pub use futures_core::task::{LocalKey, Wake};
 ```

**Comment by Nemo157** [comment]
An alternative solution would be to add an extra `atomic` feature to `futures` and `futures-core` to control when this is built, but that doesn't seem very nice to me.

The last solution I thought of is to just tie `futures_core::task::atomic_waker` to the `std` feature. The only [current usage of it within the `futures` facade](https://github.com/rust-lang-nursery/futures-rs/blob/master/futures-util/src/stream/futures_unordered.rs) is itself [only compiled with `std`](https://github.com/rust-lang-nursery/futures-rs/blob/master/futures-util/src/stream/mod.rs#L89).

**Comment by aturon** [comment]
Addressed by https://github.com/rust-lang-nursery/futures-rs/pull/873
