### ISSUE TITLE
task::Context::new is incompatible when `std` feature is enabled/disabled

### ISSUE THREAD

**Issue by Nemo157** [rust-lang-nursery/futures-rs#849]
```rust
// With `std` feature
fn new(map: &'a mut LocalMap, waker: &'a Waker, executor: &'a mut Executor) -> Context<'a> { ... }

// Without `std` feature
fn new(map: &'a mut LocalMap, waker: &'a Waker) -> Context<'a> { ... }
```

I realise that implementing an executor that's supposed to work for both `std` and `no_std` environments is unlikely. But it might be nice for testing purposes to be able to compile it on both without requiring multiple code paths (I have a `no_std` executor, but I have yet to look into testing it).

**Comment by Nemo157** [comment]
Actually, I now realise that when testing it's still fine to compile without `futures-core/std` enabled. Only the tests themselves will need to be not `no_std`. Still, having an API add an extra argument when a feature is enabled seems wrong to me.

**Comment by stbuehler** [comment]
I think it's basically a hint that you shouldn't try to write an executor for both `std` and `no_std`.  Choose one and make it good.

In any case your executor needs to be aware whether it's `std` or `no_std`.

(Also: `Executor` is a trait that doesn't make sense in `no_std` - it would be empty if you would define it for `no_std`.  So again your executor needs to be aware whether it's `std` or `no_std`.)
