### ISSUE TITLE
Errors on AsyncRead/AsyncWrite

### ISSUE THREAD

**Issue by AljoschaMeyer** [rust-lang-nursery/futures-rs#856]
futures 0.2.0 question:

Is an `AsyncRead` or an `AsyncWrite` allowed to emit errors of kind `WouldBlock` or `Interrupted`? Or can I write my my code assuming that all their errors are fatal (or at least non-harmless)?

**Comment by Nemo157** [comment]
Since [`futures_util::io::read_to_end` explictly takes `Interrupted` into account](https://github.com/rust-lang-nursery/futures-rs/blob/e3d7bdf2cedf35ea514ed7e57782121bc161d12d/futures-util/src/io/read_to_end.rs#L80) I believe that error at least is allowed to be emitted by `AsyncRead` implementations.

**Comment by AljoschaMeyer** [comment]
Ugh, I really hoped these traits would hide those. But in any case, this needs to be documented.

**Comment by carllerche** [comment]
`Interrupted` and `WouldBlock` should not be returned from `AsyncRead` / `AsyncWrite` impls.

`WouldBlock` is represented as `Async::Pending` and `Interrupted` is discussed in #803.

**Comment by AljoschaMeyer** [comment]
Is [AllowStdIo](https://docs.rs/futures-util/0.2.0-alpha/futures_util/io/struct.AllowStdIo.html) allowed to wrap io objects that can emit `Interrupted` errors? It currently propagates them, but perhaps it should provide retry logic instead.

**Comment by Nemo157** [comment]
@AljoschaMeyer fixed, and the documentation was updated in https://github.com/rust-lang-nursery/futures-rs/pull/867

**Comment by AljoschaMeyer** [comment]
@Nemo157 Thank you!

I also have a the good old [try_with_interrupt](https://github.com/AljoschaMeyer/atm-io-utils/blob/master/src/macros.rs#L6) macro in a utility crate :). Perhaps it could be exposed in a more "official" crate? I'm not sure it fits into futures-io though, since the whole point of futures-io is not to have to deal with this stuff.

**Comment by aturon** [comment]
Put on 0.2 milestone just because I think we should nail down and state a decision here.

**Comment by cramertj** [comment]
This was fixed and documented in https://github.com/rust-lang-nursery/futures-rs/pull/867
