### ISSUE TITLE
0.2 vs master branch

### ISSUE THREAD

**Issue by Nemo157** [rust-lang-nursery/futures-rs#866]
Should the `0.2` branch exist at the moment? It appears to [only contain the `futures-stable` integration relative to `master`](https://github.com/rust-lang-nursery/futures-rs/compare/master...0.2), and is [missing a lot of the changes that made it into the `0.2.0-alpha` release on `master`](https://github.com/rust-lang-nursery/futures-rs/compare/0.2...0.2.0-alpha).

**Comment by Nemo157** [comment]
cc @cramertj, @withoutboats since https://github.com/rust-lang-nursery/futures-rs/pull/854 made `0.2` and `master` diverge.

**Comment by cramertj** [comment]
Ah, I missed that that change was targeting 0.2 rather than master. Thanks for the heads up, @Nemo157! I've opened https://github.com/rust-lang-nursery/futures-rs/pull/870 for moving the 0.2 changes back into master, after which I'll delete 0.2.
