### ISSUE TITLE
Docs on what can be done without std?

### ISSUE THREAD

**Issue by robomancer-or** [rust-lang-nursery/futures-rs#882]
The readme says that without std there "a significantly reduced API surface", but I haven't found anywhere that lays out what features require std and what features don't.  Does that information exist anywhere besides the source?

**Comment by Nemo157** [comment]
Easy way to see it is `cd futures-rs/futures && cargo doc --no-default-features --open`. There _was_ [a ticket](https://github.com/rust-lang/rust/issues/35903) about adding support for displaying feature dependencies to `rustdoc`, which would allow viewing this on docs.rs as well, but no idea if something like that will ever actually happen.

**Comment by robomancer-or** [comment]
Having to clone a repo just to get a sense of if it could work for me seems inelegant (I suppose I'm preaching to the choir on that one), but it's certainly better than nothing, thanks!  (I'm going to have to keep that trick in my back pocket for other crates)
