### ISSUE TITLE
Re-export futures_core::task::Context at crate level

### ISSUE THREAD

**Issue by partim** [rust-lang-nursery/futures-rs#895]
(I hope this wasn't raised before and I missed the issue.)

When writing an impl for the `Future` trait, one now needs `task::Context`. Unlike `Futures` and `Poll` (or `Async`), `Context` isn't re-exported at crate level, requiring an extra `use` line.

Perhaps it would be possible to re-export `Context` so that one could import everything needed for an impl in one fell swoop?

**Comment by cramertj** [comment]
The intention was that users should use it as `task::Context` rather than just `Context` (which is confusing absent more context :wink: ). The `task` module itself is included in the prelude.
