### ISSUE TITLE
FutureExt::inspect_err() ?

### ISSUE THREAD

**Issue by vorot93** [rust-lang-nursery/futures-rs#898]
In continuation of #700 

Inspecting errors in a future could be quite useful. Since we have the same API in `Stream` perhaps we could include one in `Future` as well?

**Comment by Bert-Proesmans** [comment]
If i understand correctly, this method doesn't exist in the Futures-0.1 release, can/will this be backported?

**Comment by Nemo157** [comment]
It's a pretty trivial method to add, if you/someone opens a PR to add it to 0.1 I'm sure it'll be accepted.
