### ISSUE TITLE
impl Future for SpawnWithHandle is too strict to be useful

### ISSUE THREAD

**Issue by farnoy** [rust-lang-nursery/futures-rs#903]
Hey, on `0.2.0-beta`, you can only use `spawn_with_handle` with Futures returning unit, which isn't very useful for a handle. I think this can be relaxed, but I am not sure.

```rust
impl<F> Future for SpawnWithHandle<F>
    where F: Future<Item = (), Error = Never> + Send + 'static,
          F::Item: Send,
          F::Error: Send,
{
```

Can we make it accept any `Item` and `Error`, as long as they both implement `Send`?

**Comment by Nemo157** [comment]
Yes, that looks like it's a mistake, the only place the restriction is placed is on that implementation, the rest of the code already supports passing the item/error back. I'll open a PR to relax it.
