### ISSUE TITLE
breaking stream::unfold change between 0.1.18 and 0.1.19

### ISSUE THREAD

**Issue by softprops** [rust-lang-nursery/futures-rs#904]
It looks like there was a signature change to stream::unfold ( my favorite futures interface! ) in a recent 0.1 release. My crate had an issue reported reported [here](https://github.com/softprops/hubcaps/issues/112) that a consumer wasn't able to build after doing a cargo update. I was able to confirm myself. 

I took a quickly and it looks like a signature change in futures-rs between [0.1.8](https://docs.rs/futures/0.1.18/futures/stream/fn.unfold.html) and [0.1.9](https://docs.rs/futures/0.1.19/futures/stream/fn.unfold.html). Notable there's [no release notes](https://github.com/rust-lang-nursery/futures-rs/blob/8c949e3daac8cb45f83b70ed0e039bde303e061e/CHANGELOG.md) to indicate the changes but for now docs.rs is a fine way to notice the change.

I can deal with it in my crate but I wanted to drop a note on here in case any down stream consumes of futures-rs may run into the same problem .

I know and understand yall are busy working towards a 0.2.* release so I don't expect a remedy. I hope this note is able to help others in the meantime.

cc @matthiasbeyer

**Comment by bluejekyll** [comment]
This looks like #892 as I see your type has an Option in a return there.

**Comment by softprops** [comment]
Yep. It looks like the signature for unfold went from an option of a future to a future of an option. The sock was just turned inside out :)

**Comment by softprops** [comment]
I think this backwards incompatible change still exists event with that last revert

**Comment by softprops** [comment]
It looks more like a problem. With the method signature that's the problem [0.1.18](https://docs.rs/futures/0.1.18/futures/stream/fn.unfold.html) vs [0.1.20](https://docs.rs/futures/0.1.20/futures/stream/fn.unfold.html). Is there a new from impl I need to import?

**Comment by softprops** [comment]
Any update on a recommended path for this? I could update my crate to adapt to a the breaking change but if the breaking change is going to be revert ill have to republish a new version to undo that.

**Comment by cramertj** [comment]
This is https://github.com/rust-lang-nursery/futures-rs/pull/730, which shouldn't have made it into 0.1. I'll push a revert.

**Comment by cramertj** [comment]
This is done in 0.1.21.

**Comment by vorner** [comment]
The fix in 0.1.21 helped. But would it make sense to yank the 0.1.20 version, or is this considered tiny not to matter?

**Comment by softprops** [comment]
Confirmed 0.1.21 has me back in working order. Thanks so much for this!
