### ISSUE TITLE
Possible to poll moved StableFuture when using #[async_move]

### ISSUE THREAD

**Issue by Nemo157** [rust-lang-nursery/futures-rs#924]
Given this code saved as `futures/examples/foo.rs`:

```rust
#![feature(generators, pin, proc_macro, arbitrary_self_types)]

extern crate futures;

use std::ptr;
use std::mem::Pin;
use futures::{Poll, Async, Future, stable::StableFuture, prelude::{async_move, await}, task};

fn baz() -> impl StableFuture<Item=(), Error=()> {
    #[derive(Debug)]
    struct Baz;

    impl StableFuture for Baz {
        type Item = ();
        type Error = ();

        fn poll(self: Pin<Self>, _cx: &mut task::Context) -> Poll<Self::Item, Self::Error> {
            println!("Poll {:?} at {:?}", *self, &*self as *const Baz);
            Ok(Async::Pending)
        }
    }

    Baz
}

#[async_move]
fn foo() -> Result<(), ()> {
    await!(baz())
}

#[inline(never)]
fn bar<F: Future<Item=(), Error=()>>(mut f: F, cx: &mut task::Context) {
    f.poll(cx).unwrap();
}

fn main() {
    let mut map = task::LocalMap::new();
    let mut waker = NoWake::waker();
    let mut context = task::Context::without_spawn(&mut map, &mut waker);

    let mut future = foo();
    future.poll(&mut context).unwrap();
    bar(future, &mut context);
}


// Not important to the example

struct NoWake;

impl NoWake {
    fn waker() -> task::Waker {
        unsafe { task::Waker::new(ptr::null() as *const NoWake as *const task::UnsafeWake) }
    }
}

unsafe impl task::UnsafeWake for NoWake {
    unsafe fn clone_raw(&self) -> task::Waker { NoWake::waker() }
    unsafe fn drop_raw(&self) {}
    unsafe fn wake(&self) {}
}
```

running it from the `futures` folder with `cargo run --example foo --features nightly` gives:

```
Poll Baz at 0x7ffee1048e98
Poll Baz at 0x7ffee1048e04
```

Which should not be allowed to happen, the pin _must_ point at the same memory location every time.

I believe the error is that the `await!` macro's unsafe pin construction is only valid when it is a part of an `#[async]`  future, when used inside `#[async_move]` there's nothing stopping the generator being moved in between calls to `resume`, causing the pin to point at different memory each time.

CC @withoutboats

**Comment by Nemo157** [comment]
Thinking about it a bit more, I don't believe it will ever be possible to construct and poll `StableFuture` inside `#[async_move]` without going through `PinBox`, when inside a movable generator your stack space is movable so you have nowhere other than the heap on which you can store the `StableFuture` and ensure it never moves.

**Comment by withoutboats** [comment]
> I believe the error is that the await! macro's unsafe pin construction is only valid when it is a part of an #[async] future, when used inside #[async_move] there's nothing stopping the generator being moved in between calls to resume, causing the pin to point at different memory each time.

This is bad! I don't understand your follow up comment in the next post, it seems like you totally can?

**Comment by withoutboats** [comment]
Considering removing async_move as the solution for this for now..

**Comment by Nemo157** [comment]
What I was trying to say was that `#[async_move]` _must_ heap allocate any `StableFuture`s it both constructs and polls. It's possible for it to poll stack allocated `StableFuture`s that are passed into it as a `Pin`, and it's possible for it to construct a `PinBox<StableFuture>` and poll that. But because there's no guarantee that its stack will not move in between calls to `resume`, it cannot use stack pinning of `StableFuture`s like `#[async]` functions do.

**Comment by Nemo157** [comment]
Which is why [my quick attempt to move to stack pinning instead of unsafe pin construction](https://github.com/Nemo157/futures-rs/commit/dfcc57683c38197f169155b7274e6761451ac76e) gives `error[E0626]: borrow may still be in use when generator yields` in the `#[async_move]` tests.

**Comment by Nemo157** [comment]
Idea: if the `await!` macro was locally defined inside each function by `#[async]` then it could use `Future::poll` in `#[async_move]` functions. With an `impl<T: StableFuture> Future for PinBox<T>` and `fn pin_boxed(self) -> PinBox<Self> where Self: StableFuture` then awaiting a `StableFuture` from `#[async_move]` would be just `await!(foo().pin_boxed())?`.

I have to admit, since you added the immovable support I've never used `#[async_move]`. Being able to create immovable low-level futures has been amazing for supporting things like DMA with microcontroller peripherals. So I may not be the best person to comment on whether it's useful to have or not. (IMO, just delete it)
