### ISSUE TITLE
Expose inner Arc from SharedItem & SharedError

### ISSUE THREAD

**Issue by vorner** [rust-lang-nursery/futures-rs#926]
Hello

These are basically just Arc, but less potent (eg. they have much less methods). Furthermore, some APIs expect to work with Arcs and while it's possible to create one from item from ordinary future (because the recipient gets ownership), it is not the case here.

Would it be possible to provide `into_inner` method for them, to convert them to Arc? Or is there a reason why it shouldn't be done?

I'm willing to send the pull request, but I wanted to ask first if it makes sense.

**Comment by cramertj** [comment]
IMO it'd actually make more sense just to yield `Arc`s directly rather than adding a wrapper type. cc @aturon 

It comes at the cost of some backcompat (if we ever want to change the backing store to something other than an `Arc`) but I can't really imagine what changes we'd want to make.

**Comment by cramertj** [comment]
`shared` now operates on arbitrary `clone()` output types
