### ISSUE TITLE
futures_ordered does not preserve order of errors

### ISSUE THREAD

**Issue by ongardie-ebay** [rust-lang-nursery/futures-rs#933]
I was surprised by the behavior of futures_ordered when faced with errors.

Here's what I was trying to do:
- Issue stats gRPC calls to a list of hosts, timing out slow hosts.
- Print the results in order. For hosts that timed out, print "timed out" instead (in order).

I created a vector of futures (one future per host), and wanted to get a vector of Results. I thought futures_ordered would be a nice way to do that. However, it doesn't appear to handle ordering of errors.

Here's an simple test case (against v0.1.20):
```rust
#[test]
fn futures_ordered_error() {
    use futures::future::ok;
    use futures::future::err;
    let stream = futures_ordered(vec![
        ok::<u32, String>(1),
        err::<u32, String>(String::from("second")),
        ok::<u32, String>(3),
    ]);
    let mut iter = stream.wait();
    assert_eq!(Some(Ok(1)), iter.next());
    assert_eq!(Some(Err(String::from("second"))), iter.next());
    assert_eq!(Some(Ok(3)), iter.next());
    assert_eq!(None, iter.next());
}
```

This fails with:
```
---- futures_ordered_error stdout ----
	thread 'futures_ordered_error' panicked at 'assertion failed: `(left == right)`
  left: `Some(Ok(1))`,
 right: `Some(Err("second"))`', tests/futures_ordered.rs:114:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Is this the intended behavior for futures_ordered?

**Comment by cramertj** [comment]
This is definitely intended in the current implementation, but I think it's not an unreasonable ask to change [`queued_results`](https://github.com/rust-lang-nursery/futures-rs/blob/master/futures-util/src/stream/futures_ordered.rs#L91) to store a heap of `Result<T::Item, T::Error>` rather than just `T::Item`.

**Comment by ongardie-ebay** [comment]
I think OrderWrapper would need to be updated too.

More generally, the way Error values are represented throughout the futures library feels a little strange to me. We currently (v0.2) have `Stream::poll_next()` returning:
* "`Ok(Pending)` means that this stream's next value is not ready yet. Implementations will ensure that the current task will be notified when the next value may be ready."
* "`Ok(Ready(Some(val)))` means that the stream has successfully produced a value, val, and may produce further values on subsequent poll_next calls."
* "`Ok(Ready(None))` means that the stream has terminated, and poll_next should not be invoked again."
* "`Err(err)` means that the stream encountered an error while trying to poll_next. Subsequent calls to poll_next are allowed, and may return further values or errors."

This return type feels like the Stream can break at some point in an unrecoverable way, but the documentation says the opposite. With the error semantics as documented, I think it'd be more natural if `Stream::poll_next()` returned:
* `Pending`
* `Ready(Some(Ok(val)))`
* `Ready(Some(Err(val)))`
* `Ready(None)`

Or, perhaps more ergonomically but less like Iterator:
* `Pending`
* `Ready(Ok(val))`
* `Ready(Err(val))`
* `Done`

Admittedly, in any of the 3 representations, I'm left wondering how you'd express a broken Stream with no hope of recovery.

Sorry if this has been discussed elsewhere. I'm new here and haven't done my reading.

**Comment by ongardie-ebay** [comment]
I see the Err option is going away in v0.3, so I'm closing this now.
