### ISSUE TITLE
Provide Stream -> Iterator helper function

### ISSUE THREAD

**Issue by daschl** [rust-lang-nursery/futures-rs#934]
Hi,

I have a use case where for example code (& users running on blocking code only) need to be able to easily convert a stream I provide into a blocking iterator.

Consider the following code: https://github.com/couchbaselabs/couchbase-rs/blob/master/couchbase/examples/views.rs#L21

```rust
    let stream = bucket.query_view(ViewQuery::from("beer", "brewery_beers").limit(3));
    for row in block_on(stream.collect::<Vec<_>>()).expect("Error!") {...}
```

Since it can't infer the type as well it becomes verbose with the collect - if the crate provides a similar freestanding method as `block_on` to convert a stream into an iterator like in the past with wait (it looked much cleaner in 0.1 I think) it would be very helpful and clean things up.

**Comment by cramertj** [comment]
This was done-- the function `block_on_stream` was added to `futures_executor`.

**Comment by daschl** [comment]
oh thanks! I'll try it out :)
