### ISSUE TITLE
AtomicWaker doc example depends on its own explicitly undocumented behavior

### ISSUE THREAD

**Issue by adlerd** [rust-lang-nursery/futures-rs#942]
In `0.2.0-beta` the docs state "**AtomicWaker does not provide any memory ordering guarantees**, as such the user should use caution and use other synchronization primitives to guard the result of the underlying computation." But consider the documentation example (expanded to include a second thread for concreteness, and with the actual Future trait dropped for simplicity):

```rust
struct Flag {
    waker: AtomicWaker,
    set: AtomicBool,
}

impl Flag {
    fn thread1_poll(&mut self, cx: &mut task::Context) -> Poll<(), Never> {
        self.waker.register(cx.waker());

        if self.set.load(SeqCst) {
            Ok(Ready(()))
        } else {
            Ok(Pending)
        }
    }
    fn thread2(&mut self) {
        self.set.store(true, SeqCst);
        self.waker.wake();
    }
}
```

In order for this to work we need either `load` to return `true` or someone to actually wake thread1 (or both) every time these two threads come through. This happens in one of two ways:

1. `wake` observes `register`[0]
2. `load` observes `store`.

This means that every time `wake` does not observe the store in `register`, `store` must *happen before* `load`. That requires that a failed `wake` *inter-thread happens before* `register`, since there's no other synchronization here.[1] But you can't normally get a *inter-thread happens before* relation from a read to a write without another way to synchronize. In fact, the only way I know is to guarantee a total order on all reads and writes of that location. The takeaway point is that `AtomicWaker` explicitly declines to guarantee that total order.

Now, with the current implementation the example works because there is in fact a total order. The two ways to get that are 1. critical sections and 2. doing everything entirely inside SeqCst atomics, and the current implementation uses critical sections. But if, for instance, the implementation of `register`/`wake` switched to using an `AtomicPtr` with any memory ordering less than `SeqCst`, then the example would break. It would be possible for `wake` to read null *and* `load` to read `false`, thus causing `thread1_poll` to return `Async::Pending` without anyone being responsible for waking it up (assuming `thread2()` will never be called again). Before reading the implementation, a user has no way of knowing that there was a total order on `register`/`wake`; therefore, they could not have written the above code safely.

If I'm right about a total ordering being the only way this example works, then the documentation should just document that `AtomicWaker` guarantees it (and `set.load` can use `Relaxed`, for that matter). But if not then at least the example should be updated not to rely on the explicitly unguaranteed behavior.

[0] Or `wake` misses `register` but `register` notices this and thread1 wakes itself. This doesn't impact the analysis. It's not required to make the example work (`register` could just as well block) and since it's not documented it can't be sufficient to solve the undocumented behavior problem either.
[1] The `SeqCst` on `self.set` operations doesn't solve the problem because the seqcst global total order only has to respect other seqcst operations and the *happens before* relation. AtomicWaker is not specified to be seqcst and indeed isn't. As I state later, making AtomicWaker seqcst would make the failed `wake` *happen before* `register` anyways, so I conclude that that's a necessary condition.

**Comment by cramertj** [comment]
cc @carllerche

**Comment by carllerche** [comment]
Alright... I was caught.

@adlerd You are, of course, correct... I am impressed at your write up :)

To be honest, I documented "does not provide any memory ordering guarantees" to skip having to figure out what guarantees to commit to (and I also didn't really expect anyone to read and verify the docs), but I guess now is a good time to start the discussion!

The example and the general pattern works because there is, in fact, a memory ordering happening in the `AtomicTask` `register` / `wakeup` exchange.

* `register` [acquires](https://github.com/rust-lang-nursery/futures-rs/blob/master/futures-core/src/task/atomic_waker.rs#L201).
* `wake` [releases](https://github.com/rust-lang-nursery/futures-rs/blob/master/futures-core/src/task/atomic_waker.rs#L280).

That establishes the needed happens before you described because `set.store` is a write and `set.load` is a read. Any writes that happen before `wakeup` will be visible after `register`.

Also, in the example, `set.load` can be `Acquire` and `set.store` can be `Release` and achieve the necessary ordering... but then that would have obviously required providing better docs 😨 

Now, of course, formally documenting the ordering guarantees provided by `AtomicTask` w/o just saying "read the code, we will (hopefully) not change it" is going to be a bit tricky...

So, a) is my reasoning correct and b) how should it be documented?

**disclaimer**: Of course, as with all things atomic, I am not going to claim 100% certainty until someone gets pencil and paper out and proves it all. So, please correct me if I am wrong.

**Comment by adlerd** [comment]
Acquire -> release doesn't create an ordering, though; and even if it did, the case I'm worried about is when `wake` *doesn't* observe `register`.

After thinking about it some more, I realize I was confused on the bit about a total order on single-location accesses being what's needed, because you get that even with `Relaxed`. I remain confident the current implementation is correct but I'm not sure I can articulate *why* in a way that wouldn't require the docs to commit to almost exactly the current implementation.

However, there's an interesting note in n3797, following §29.3 paragraph 3: "Although it is not explicitly required that *S* [the single total order on all `memory_order_seq_cst` operations] include locks, it can always be extended to an order that does include lock and unlock operations, since the ordering between those is already included in the *happens before* ordering." This is one way of explaining why the current implementation works: there's a single total order on all four accesses, viewing `register`/`wake` as atomic seqcst store/load respectively. So one option is to document `AtomicWaker` as behaving as seqcst in this sense. Is that too much? I believe weakening the guarantee later would require a major version bump for the library, of course. Perhaps another option is to have `register`/`wake` take `Ordering` arguments that are currently ignored, so that if a future implementation finds it useful to provide lesser guarantees, they can be keyed on that argument (with the current impl as a fallback for SeqCst) without a major version bump.

One question I have is whether there are any useful patterns for AtomicWaker other than the one you implemented, up to replacing the `self.set` load/store with zero or more SeqCst or locked operations. If this is the only useful pattern, you could say "this exact pattern works; nothing else is guaranteed". I'm pretty sure that's basically the case today for every user of this library except for me ;).

**Comment by stbuehler** [comment]
Given the abortable combinator uses `Relaxed` atomic ordering to check the `cancel` condition perhaps the example could be updated to use `Relaxed` too instead of `SeqCst` (which probably didn't ever help, given there are no other `SeqCst` operations to order with)?

**Comment by cramertj** [comment]
@stbuehler Seems reasonable to me-- I'd be happy to accept a PR for that.

**Comment by stbuehler** [comment]
Now that #1778 (documenting the memory ordering) got merged I think this issue can be closed (I probably should have done that in the commit message, but well...).

**Comment by cramertj** [comment]
Thanks for the ping! :)
