### ISSUE TITLE
Reconsider `Context::executor` returning `Option`

### ISSUE THREAD

**Issue by carllerche** [rust-lang-nursery/futures-rs#944]
It seems that `Context::executor` was changed to return `Option` because in `no_std` `Executor` is not available.

However, the `executor` fn is not included when `no_std` is enabled. Given that `Context::executor` is present so that all callers can assume that an executor is present, would it be better for it not to return an `Option`?

Maybe if std is present, initializing a `Context` w/o a can panic?

**Comment by aturon** [comment]
Yeah, I think this was a design mistake. I now have a design in mind that is no_std compatible and allows everyone to use executors, but I want to punt it to 0.3 (so we can go ahead and get 0.2 out the door). RFC coming soon.

**Comment by carllerche** [comment]
What is the timeline to 0.3?
