### ISSUE TITLE
0.2: Future trait is not implemented for Future(Result)

### ISSUE THREAD

**Issue by spease** [rust-lang-nursery/futures-rs#954]
```
    fn get_users(r: HttpRequest<AppState>) -> FutureResult<HttpResponse, Error> {
        let users = r.state().users.borrow();
        let c = users.iter().collect::<Vec<_>>();
        result(HttpResponse::Ok().json(&c))
    }
```

```
error[E0277]: the trait bound `futures::future::FutureResult<actix_web::HttpResponse, actix_web::Error>: futures::future::Future` is not satisfied
   --> src/main.rs:251:59
    |
251 |             .resource("/users", |r| r.method(Method::GET).a(AppState::get_users))
    |                                                           ^ the trait `futures::future::Future` is not implemented for `futures::future::FutureResult<actix_web::HttpResponse, actix_web::Error>
```

```
fn get_users(r: HttpRequest<AppState>) -> Box<futures::future::Future<Item=HttpResponse, Error=Error>> {
        let users = r.state().users.borrow();
        let c = users.iter().collect::<Vec<_>>();
        Box::new(futures::future::ok(HttpResponse::Ok().json(&c).unwrap()))
    }
```

```
error[E0277]: the trait bound `futures::Future<Error=actix_web::Error, Item=actix_web::HttpResponse> + 'static: futures::future::Future` is not satisfied
   --> src/main.rs:251:59
    |
251 |             .resource("/users", |r| r.method(Method::GET).a(AppState::get_users))
    |                                                           ^ the trait `futures::future::Future` is not implemented for `futures::Future<Error=actix_web::Error, Item=actix_web::HttpResponse> + 'static`
    |
    = note: required because of the requirements on the impl of `futures::future::Future` for `std::boxed::Box<futures::Future<Error=actix_web::Error, Item=actix_web::HttpResponse> + 'static>`
```

**Comment by Nemo157** [comment]
[`actix_web` is still using `futures` 0.1](https://github.com/actix/actix-web/blob/master/Cargo.toml#L81) (unless you're using a different branch of it?). I can't see any other way that you could get this error message, it also makes sense with the second error message:

> the trait bound `futures::Future<...> + 'static: futures::future::Future` is not satisfied

that's impossible unless the two `Future` traits referred to are different traits.

**Comment by Nemo157** [comment]
> Are the latest versions of futures and tokio-core incompatible?

[Yes](https://github.com/tokio-rs/tokio-core/blob/master/Cargo.toml#L30)

**Comment by Trolldemorted** [comment]
So I am implementing the wrong version of Future (since I depend on futures 2.0), and thus the required version is not implemented?

The compiler error definitely should hint that I am implementing a wrong version of Future imho.

Anyway, are there any executors for futures 2.0 around?

**Comment by xrl** [comment]
@Trolldemorted I have been playing around with futures-preview 0.3 and I am able to use the fahrenheit executor. It's pretty rad.

**Comment by MajorBreakfast** [comment]
Please note that Fahrenheit is for educational purposes. Currently, it is recommended to either use futures 0.1 and Tokio directly or through the compatibility layer (blog post in the works).
