### ISSUE TITLE
Clarify the two usages of TLS

### ISSUE THREAD

**Issue by plumenator** [rust-lang-nursery/futures-rs#957]
I see the abbreviation TLS used in many places in this repo (issues, code, etc.) and it looks like it can stand for:
1. Transport Layer Security
2. Thread Local Storage

I think it's a good idea to define these terms in the README so that new comers to the repo can understand which meaning is implied based on the context.

**Comment by cramertj** [comment]
In this repository it is always used to refer to thread-local storage. I'd happily accept a PR clarifying existing usages.
