### ISSUE TITLE
Namespacing error with #[async(pinned)]

### ISSUE THREAD

**Issue by tdyas** [rust-lang-nursery/futures-rs#958]
When using `#[async(pinned)]` on an async function in my project with `master` as of today (4/11), I get the error:

```
Could not find `boxed` in `__rt`
```
My educated guess is that the error occurs because several lines in the `futures-macro-async` create need to refer to `::futures::__rt::boxed` as `::futures::__rt::std::boxed` (i.e., insert `std` into the path). See https://github.com/rust-lang-nursery/futures-rs/blob/b7731ce388fc2ac1d98ae236aa783ebc58fb968a/futures-macro-async/src/lib.rs#L271 for the error and https://github.com/rust-lang-nursery/futures-rs/blob/b7731ce388fc2ac1d98ae236aa783ebc58fb968a/futures-macro-async/src/lib.rs#L233 for a correct reference.

**Comment by ngg** [comment]
#916 fixes this.
