### ISSUE TITLE
Clarify behaviour of Stream::select

### ISSUE THREAD

**Issue by lukaslueg** [rust-lang-nursery/futures-rs#960]
The docs concerning `Stream::select()` are a little murky to the point of what will happen if both streams are ready to proceed when `select` is called, specifically if `Self` is always guaranteed to yield before `other` is polled.

The docs say "... whichever is ready first." but also "Each stream will be polled in a round-robin fashion", which suggest to me that the aforementioned guarantee is upheld.

**Comment by cramertj** [comment]
I'm happy to take a PR here clarifying the docs!
