### ISSUE TITLE
select_all does O(n) copies

### ISSUE THREAD

**Issue by stuhood** [rust-lang-nursery/futures-rs#969]
Due to using `Vec::remove`, a `select_all` loop that drains a collection might do O(n) copies of the `Vec`.

As a strawman, `select_all_unordered` could use `Vec::swap_remove` and remove the index value from the API?

**Comment by Nemo157** [comment]
Technically `SelectAll` does not guarantee any order on the returned vector, so changing it to `swap_remove` would be allowed...

It would be great to have examples of current `select_all` usage in the wild, depending on how it is actually used in practice it might be better to change it and introduce an alternative API for the use case where keeping the order consistent is necessary.

**Comment by cramertj** [comment]
I'd just change it to use a `slab` or something instead of a `Vec` so that removal isn't so expensive.

**Comment by cramertj** [comment]
Ah, can't change to `slab` because it yields a `Vec`. `swap_remove` it is!
