### ISSUE TITLE
println! does not find any variables inside non-linear async functions

### ISSUE THREAD

**Issue by sdroege** [rust-lang-nursery/futures-rs#983]
See https://github.com/sdroege/gtk-rs-examples/blob/0f6c01eb18517d8db28633a54a5aded3341370fd/src/bin/gio_futures_await.rs#L49

That line fails to compile with
```
error[E0425]: cannot find value `idx` in this scope
 --> <println macros>:3:44
  |
3 | ) => ( print ! ( concat ! ( $ fmt , "\n" ) , $ ( $ arg ) * ) ) ;
  |                                            ^ not found in this scope

error[E0425]: cannot find value `buf` in this scope
 --> <println macros>:3:44
  |
3 | ) => ( print ! ( concat ! ( $ fmt , "\n" ) , $ ( $ arg ) * ) ) ;
  |                                            ^ not found in this scope

error[E0425]: cannot find value `len` in this scope
 --> <println macros>:3:44
  |
3 | ) => ( print ! ( concat ! ( $ fmt , "\n" ) , $ ( $ arg ) * ) ) ;
  |                                            ^ not found in this scope

error: aborting due to 3 previous errors
```

doing the same with a normal function as in the next line works fine though.

Unfortunately I was not able to reproduce this in a stand-alone testcase so far, it's not clear to me what exactly triggers it.

**Comment by Nemo157** [comment]
Sounds very similar to https://github.com/alexcrichton/futures-await/issues/95 which is caused by https://github.com/rust-lang/rust/issues/50061

**Comment by sdroege** [comment]
Yes that's most likely the same. Feel free to close this one

**Comment by sdroege** [comment]
The next nightly should have this fixed, I'll close it once it is available for testing and if it's indeed fixed

**Comment by sdroege** [comment]
Works now indeed, thanks!
