### ISSUE TITLE
ThreadPool requires &mut self to dispatch tasks

### ISSUE THREAD

**Issue by khuey** [rust-lang-nursery/futures-rs#990]
Despite having sufficient internal synchronization (i.e. the relevant methods on `PoolState` take `&self`) `ThreadPool::spawn` requires a `&mut self` to dispatch tasks to it. This method comes from the `Executor` trait which requires `&mut self` for all `Executor` implementations. `LocalExecutor` doesn't actually need `&mut self` internally either so it seems like the trait should be changed.

I'm currently working around this by cloning my `&ThreadPool` into a mutable local to dispatch tasks to it but it's nasty :nauseated_face:

**Comment by cramertj** [comment]
Thanks for the report! `&ThreadPool` should also implement `Executor`.

**Comment by Thomasdezeeuw** [comment]
Closed by  #1324?
