### ISSUE TITLE
Couldn't generate the documentation (extern_prelude)

### ISSUE THREAD

**Issue by adjivas** [rust-lang-nursery/futures-rs#999]
Hello,

When I compile the documentation from futures-channel project, this error append:
```bash
cargo doc
 Documenting futures-channel v0.2.1 (file:///private/tmp/adjivas/futures-rs/futures-channel)
error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  |
  = help: add #![feature(extern_prelude)] to the crate attributes to enable

error: Could not document `futures-channel`.

Caused by:
  process didn't exit successfully: `rustdoc --crate-name futures_channel futures-channel/src/lib.rs -o /private/tmp/adjivas/futures-rs/target/doc --cfg feature="default" --cfg feature="futures-core" --cfg feature="std" -L dependency=/private/tmp/adjivas/futures-rs/target/debug/deps --extern futures_core=/private/tmp/adjivas/futures-rs/target/debug/deps/libfutures_core-670bf32b5273b58b.rmeta` (exit code: 101)
```

Of course if I add `doc = false` to Cargo.toml manifest from futures-channel or `#![feature(extern_prelude)]` to lib.rs that solve the compilation.

My versions are:
* rustc 1.27.0-nightly (8a37c75a3 2018-05-02)
* cargo 1.27.0-nightly (122fd5be5 2018-04-28)

**Comment by Nemo157** [comment]
Was fixed as part of #1003

**Comment by adjivas** [comment]
That right, I close my issue, thank you!

**Comment by adjivas** [comment]
There is any regression ? I have this repetition on this [log](https://travis-ci.org/adjivas/telamon/jobs/383241929)

**Comment by Nemo157** [comment]
There hasn't been a new release of `futures` 0.2 since #1003 was merged, you will either have to wait till that happens, or switch to depending on `futures = { git = "https://github.com/rust-lang-nursery/futures-rs" }` in the meantime.

**Comment by adjivas** [comment]
Okay! Thank's for the information
